'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{FORMATS,parseAnalyzerArtifact,mergeAnalyzerArtifacts}=require('../src/analyzer-adapters');

test('adapter hub exposes supported non-executable formats',()=>{for(const format of ['sarif','gitlab-codequality','junit','cobertura','lcov','compiler','cppcheck','cyclonedx-json','trivy-json','gitleaks-json'])assert.ok(FORMATS.includes(format));});
test('GitLab Code Quality normalizes changed-file findings',()=>{const result=parseAnalyzerArtifact({format:'gitlab-codequality',content:JSON.stringify([{description:'Possible null dereference',check_name:'null-deref',fingerprint:'abc',severity:'major',location:{path:'src/a.c',lines:{begin:7}}}])});assert.equal(result.findings.length,1);assert.equal(result.findings[0].file,'src/a.c');assert.equal(result.findings[0].line,7);});
test('JUnit keeps failing testcase evidence when file is known',()=>{const result=parseAnalyzerArtifact({format:'junit',content:'<testsuites><testsuite tests="2" failures="1"><testcase classname="audio" name="aec" file="tests/aec_test.c" line="12"><failure message="expected clean signal">stack</failure></testcase></testsuite></testsuites>'});assert.equal(result.findings.length,1);assert.equal(result.findings[0].category,'test');assert.equal(result.metadata.failures,1);});
test('coverage adapters emit metadata rather than fabricated source findings',()=>{const cob=parseAnalyzerArtifact({format:'cobertura',content:'<coverage line-rate="0.81" branch-rate="0.5" lines-covered="81" lines-valid="100" />'});assert.equal(cob.findings.length,0);assert.equal(cob.metadata.lineRate,0.81);const lc=parseAnalyzerArtifact({format:'lcov',content:'SF:src/a.c\nLF:10\nLH:8\nend_of_record'});assert.equal(lc.metadata.lineRate,0.8);});
test('compiler cppcheck and scanner findings normalize through Core',()=>{const compiler=parseAnalyzerArtifact({format:'compiler',content:'src/a.c:9:2: error: use of undeclared identifier x'});assert.equal(compiler.findings[0].severity,'high');const cpp=parseAnalyzerArtifact({format:'cppcheck',content:'<results><errors><error id="nullPointer" severity="error" msg="Null pointer"><location file="src/a.c" line="9"/></error></errors></results>'});assert.equal(cpp.findings.length,1);const leaks=parseAnalyzerArtifact({format:'gitleaks-json',content:JSON.stringify([{RuleID:'generic-api-key',Description:'API key',File:'config/dev.env',StartLine:3}])});assert.equal(leaks.findings[0].severity,'critical');assert.equal(mergeAnalyzerArtifacts([compiler,cpp,leaks]).findings.length,3);});
test('artifact byte limit fails closed',()=>{assert.throws(()=>parseAnalyzerArtifact({format:'compiler',content:'x'.repeat(5000),maxBytes:1024}),error=>error.code==='EANALYZERSIZE');});
