'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{normalizeEvent}=require('../src/webhook');
const{assignmentMatch,assignmentChangeRelevant}=require('../src/assignment');
function config(overrides={}){return{gitlabProjectAllowlist:new Set([7]),triggerAssignment:{mode:'reviewer',userIds:[8]},triggerOnOpen:true,triggerOnPush:true,triggerOnReopen:true,botUsername:'bot',...overrides};}
function mr(extra={}){return{object_kind:'merge_request',project:{id:7},reviewers:[],assignees:[],object_attributes:{iid:9,action:'open',last_commit:{id:'head'}},...extra};}

test('reviewer mode uses Reviewer rather than Assignee',()=>{const c=config();assert.equal(normalizeEvent(mr({reviewers:[{id:8}]}),{},c).shouldReview,true);assert.equal(normalizeEvent(mr({assignees:[{id:8}]}),{},c).shouldReview,false);assert.equal(normalizeEvent(mr({reviewers:[{id:9}]}),{},c).shouldReview,false);assert.equal(normalizeEvent(mr(),{},c).shouldReview,false);});
test('empty userIds means any member in the selected role',()=>{const c=config({triggerAssignment:{mode:'reviewer',userIds:[]}});assert.equal(normalizeEvent(mr({reviewers:[{id:99}]}),{},c).shouldReview,true);assert.equal(normalizeEvent(mr(),{},c).shouldReview,false);});
test('assignee, either and always modes are explicit',()=>{assert.equal(assignmentMatch({reviewers:[],assignees:[{id:8}]},{mode:'assignee',userIds:[8]}),true);assert.equal(assignmentMatch({reviewers:[{id:8}],assignees:[]},{mode:'either',userIds:[8]}),true);assert.equal(assignmentMatch({reviewers:[],assignees:[]},{mode:'always',userIds:[]}),true);});
test('adding a matching Reviewer to an existing MR triggers without a source push',()=>{const c=config(),payload=mr({reviewers:[{id:8}],changes:{reviewers:{previous:[],current:[{id:8}]}},object_attributes:{iid:9,action:'update',last_commit:{id:'head'}}});assert.equal(normalizeEvent(payload,{},c).shouldReview,true);});
test('removing Reviewer or unrelated metadata update does not trigger',()=>{const c=config(),removed=mr({reviewers:[],changes:{reviewers:{previous:[{id:8}],current:[]}},object_attributes:{iid:9,action:'update',last_commit:{id:'head'}}}),titleOnly=mr({reviewers:[{id:8}],changes:{title:{previous:'a',current:'b'}},object_attributes:{iid:9,action:'update',last_commit:{id:'head'}}});assert.equal(normalizeEvent(removed,{},c).shouldReview,false);assert.equal(normalizeEvent(titleOnly,{},c).shouldReview,false);});
test('code pushes remain assignment-gated',()=>{const c=config(),push=reviewers=>mr({reviewers,object_attributes:{iid:9,action:'update',oldrev:'old',last_commit:{id:'head'}}});assert.equal(normalizeEvent(push([{id:8}]),{},c).shouldReview,true);assert.equal(normalizeEvent(push([]),{},c).shouldReview,false);});
test('assignment-change relevance follows configured role',()=>{assert.equal(assignmentChangeRelevant({reviewers:{}},'reviewer'),true);assert.equal(assignmentChangeRelevant({assignees:{}},'reviewer'),false);assert.equal(assignmentChangeRelevant({assignees:{}},'assignee'),true);assert.equal(assignmentChangeRelevant({reviewers:{}},'either'),true);assert.equal(assignmentChangeRelevant({reviewers:{}},'always'),false);});
test('manual /codex review is an explicit assignment bypass',()=>{const event={object_kind:'note',project:{id:7},user:{id:12,username:'alice'},merge_request:{iid:9,reviewers:[],assignees:[]},object_attributes:{action:'create',note:'/codex review'}};assert.equal(normalizeEvent(event,{},config()).shouldReview,true);});
