'use strict';
const path=require('node:path');
const test=require('node:test'),assert=require('node:assert/strict');const{filteredEnv,buildCodexArgs,parseJsonl,parseJsonlEvents,checkVersionPolicy,SAFE_CONFIG_OVERRIDES,runtimeFromConfig}=require('../src/codex');

test('Codex child environment excludes GitLab secrets',()=>{const old=process.env.GITLAB_API_TOKEN;process.env.GITLAB_API_TOKEN='secret';try{const env=filteredEnv({codexHome:'/tmp/codex'});assert.equal(env.GITLAB_API_TOKEN,undefined);assert.equal(env.CODEX_HOME,'/tmp/codex');}finally{if(old===undefined)delete process.env.GITLAB_API_TOKEN;else process.env.GITLAB_API_TOKEN=old;}});

test('Safe Contract args disable execution/network capabilities',()=>{const args=buildCodexArgs('/tmp/schema.json','');for(const required of ['--ask-for-approval','never','--ephemeral','--ignore-user-config','--ignore-rules','--sandbox','read-only','--output-schema'])assert.ok(args.includes(required));assert.ok(SAFE_CONFIG_OVERRIDES.includes('web_search="disabled"'));assert.ok(SAFE_CONFIG_OVERRIDES.includes('features.shell_tool=false'));assert.ok(SAFE_CONFIG_OVERRIDES.includes('features.multi_agent=false'));});

test('parses final agent JSONL and latest turn usage',()=>{const stdout=[JSON.stringify({type:'turn.completed',usage:{input_tokens:100,cached_input_tokens:40,cache_write_input_tokens:3,output_tokens:20,reasoning_output_tokens:8}}),JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'{"summary":"ok","findings":[]}'}})].join('\n');const parsed=parseJsonlEvents(stdout);assert.equal(parseJsonl(stdout),'{"summary":"ok","findings":[]}');assert.deepEqual(parsed.usage,{inputTokens:100,cachedInputTokens:40,cacheWriteInputTokens:3,outputTokens:20,reasoningOutputTokens:8});});

test('strict Codex version policy rejects untested version while warn only reports mismatch',()=>{assert.equal(checkVersionPolicy('codex-cli 1.2.3',{codexVersionPolicy:'warn',codexAllowedVersionPattern:'1\\.3\\.'}),false);assert.throws(()=>checkVersionPolicy('codex-cli 1.2.3',{codexVersionPolicy:'strict',codexAllowedVersionPattern:'1\\.3\\.'}),error=>error.code==='ECODEXVERSION');assert.equal(checkVersionPolicy('codex-cli 1.3.1',{codexVersionPolicy:'strict',codexAllowedVersionPattern:'1\\.3\\.'}),true);});

// auth.json is an OS-native local filesystem path; portability tests must not impose POSIX separators on Windows.
test('Provider Contract v2 maps auth.json and private HTTP controls into Core runtime',()=>{const codexHome='/home/liujing/.codex';const runtime=runtimeFromConfig({codexProviderMode:'openai-compatible',codexProviderBaseUrl:'http://192.168.2.109:3000/v1',codexProviderApiKeyEnv:'RELAY_API_KEY',codexProviderCredentialSource:'auth-json',codexProviderAllowInsecureHttp:true,codexHome});assert.equal(runtime.provider.credentialSource,'auth-json');assert.equal(runtime.provider.allowInsecureHttp,true);assert.equal(runtime.provider.authJsonPath,path.join(codexHome,'auth.json'));});
