'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const{parseProjectAllowlist,validateSigningToken,normalizeBaseUrl,loadStructuredConfig,scopeFromInputs}=require('../src/config');
function tempConfig(value){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-config-')),file=path.join(dir,'config.json');fs.writeFileSync(file,JSON.stringify(value));return{file,close(){fs.rmSync(dir,{recursive:true,force:true});}};}
function withEnv(name,value,fn){const old=process.env[name];if(value===undefined)delete process.env[name];else process.env[name]=value;try{return fn();}finally{if(old===undefined)delete process.env[name];else process.env[name]=old;}}

test('parses legacy explicit project allowlist and wildcard',()=>{assert.deepEqual([...parseProjectAllowlist('1, 2,2')],[1,2]);assert.equal(parseProjectAllowlist('*'),null);assert.throws(()=>parseProjectAllowlist(''),/must be/);assert.throws(()=>parseProjectAllowlist('abc'),/invalid/);});
test('validates standard webhook signing token shape',()=>{const token=`whsec_${Buffer.alloc(32,7).toString('base64')}`;assert.equal(validateSigningToken(token),token);assert.throws(()=>validateSigningToken('whsec_YQ=='),/32 bytes/);assert.throws(()=>validateSigningToken('bad'),/whsec_/);});
test('normalizes safe GitLab base URLs',()=>{assert.equal(normalizeBaseUrl('https://gitlab.example.test/','X'),'https://gitlab.example.test');assert.throws(()=>normalizeBaseUrl('https://u:p@gitlab.example.test','X'),/without credentials/);});
test('strict config file parses projects groups concurrency and runner mode',()=>{const t=tempConfig({gitlab:{baseUrl:'https://gitlab.test',projects:[7,7,8],groups:[{id:20,includeSubgroups:true}]},review:{concurrency:4},runner:{mode:'inline'}});try{const loaded=loadStructuredConfig(t.file);assert.equal(loaded.present,true);assert.deepEqual(loaded.value.gitlab.projects,[7,8]);assert.deepEqual(loaded.value.gitlab.groups,[{id:20,includeSubgroups:true}]);assert.equal(loaded.value.review.concurrency,4);assert.equal(loaded.value.runner.mode,'inline');}finally{t.close();}});
test('config file rejects unknown fields and invalid group IDs',()=>{const a=tempConfig({gitlab:{projects:[1],unexpected:true}}),b=tempConfig({gitlab:{projects:[1],groups:[{id:0}]}});try{assert.throws(()=>loadStructuredConfig(a.file),/unsupported field/);assert.throws(()=>loadStructuredConfig(b.file),/positive integer/);}finally{a.close();b.close();}});
test('legacy GITLAB_PROJECT_ALLOWLIST overrides structured scope selection',()=>withEnv('GITLAB_PROJECT_ALLOWLIST','9,10',()=>{const scope=scopeFromInputs({gitlab:{projects:[1],groups:[{id:20,includeSubgroups:true}]}});assert.deepEqual([...scope.projects],[9,10]);assert.deepEqual(scope.groups,[]);assert.equal(scope.source,'legacy-env');}));
test('structured projects and groups are used when legacy env is absent',()=>withEnv('GITLAB_PROJECT_ALLOWLIST',undefined,()=>{const scope=scopeFromInputs({gitlab:{projects:[1,2],groups:[{id:20,includeSubgroups:false}]}});assert.deepEqual([...scope.projects],[1,2]);assert.equal(scope.groups.length,1);assert.equal(scope.source,'config-file');}));
test('wildcard legacy scope is webhook-only',()=>withEnv('GITLAB_PROJECT_ALLOWLIST','*',()=>{const scope=scopeFromInputs({gitlab:{projects:[1],groups:[]}});assert.equal(scope.projects,null);assert.equal(scope.wildcard,true);assert.equal(scope.groups.length,0);}));
