'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const{validateSigningToken,normalizeBaseUrl,loadStructuredConfig,loadConfig,defaultConfigPath,defaultStateDir,defaultRunnerSocket,parseAnalyzerReports,CONFIG_SCHEMA_VERSION}=require('../src/config');
const posixTest=process.platform==='win32'?test.skip:test;
function tempConfig(value){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-config-')),file=path.join(dir,'config.json');fs.writeFileSync(file,JSON.stringify({schemaVersion:CONFIG_SCHEMA_VERSION,...value}));return{file,close(){fs.rmSync(dir,{recursive:true,force:true});}};}
function withEnvs(values,fn){const old=Object.fromEntries(Object.keys(values).map(key=>[key,process.env[key]]));for(const[key,value]of Object.entries(values)){if(value===undefined)delete process.env[key];else process.env[key]=value;}try{return fn();}finally{for(const[key,value]of Object.entries(old)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}}
function baseConfig(extra={}){return{gitlab:{baseUrl:'https://gitlab.test',projects:[7,8],groups:[]},runner:{mode:'inline'},...extra};}
function signingToken(){return`whsec_${Buffer.alloc(32,7).toString('base64')}`;}

test('validates standard webhook signing token shape',()=>{const token=signingToken();assert.equal(validateSigningToken(token),token);assert.throws(()=>validateSigningToken('whsec_YQ=='),/32 bytes/);assert.throws(()=>validateSigningToken('bad'),/whsec_/);assert.throws(()=>validateSigningToken(''),/required/);});
test('normalizes safe GitLab base URLs',()=>{assert.equal(normalizeBaseUrl('https://gitlab.example.test/','X'),'https://gitlab.example.test');assert.throws(()=>normalizeBaseUrl('https://u:p@gitlab.example.test','X'),/without credentials/);});
test('strict canonical config accepts only supported sections and fields',()=>{const t=tempConfig({...baseConfig(),review:{concurrency:4,blockingSeverity:'high',profile:'embedded-linux',analyzerReports:[{format:'junit',job:'test-*',path:'junit.xml'}],testImpactEnabled:true,testPathPrefixes:['test/'],maxTestCandidates:100,maxRecommendedTests:20},publication:{concurrency:3},observability:{serviceName:'review'}});try{const loaded=loadStructuredConfig(t.file);assert.equal(loaded.path,t.file);assert.equal(loaded.schemaVersion,CONFIG_SCHEMA_VERSION);assert.equal(loaded.value.review.concurrency,4);assert.equal(loaded.value.publication.concurrency,3);}finally{t.close();}});
test('config schema is explicit and hard-cut at v5',()=>{const missing=tempConfig({schemaVersion:undefined,...baseConfig()}),future=tempConfig({schemaVersion:6,...baseConfig()}),old=tempConfig({schemaVersion:4,...baseConfig()});try{assert.equal(CONFIG_SCHEMA_VERSION,5);assert.throws(()=>loadStructuredConfig(missing.file),/Unsupported config schema <missing>/);assert.throws(()=>loadStructuredConfig(future.file),/Unsupported config schema 6/);assert.throws(()=>loadStructuredConfig(old.file),/Unsupported config schema 4/);}finally{missing.close();future.close();old.close();}});
test('Config Schema 5 rejects retired sarifFiles and incrementalReviewEnabled and parses bounded analyzer reports',()=>{const legacy=tempConfig({...baseConfig(),review:{sarifFiles:['scan.sarif']}}),incremental=tempConfig({...baseConfig(),review:{incrementalReviewEnabled:true}});try{assert.throws(()=>loadStructuredConfig(legacy.file),/unsupported field: sarifFiles/);assert.throws(()=>loadStructuredConfig(incremental.file),/unsupported field: incrementalReviewEnabled/);const reports=parseAnalyzerReports([{format:'sarif',job:'scan-*',path:'reports/a.sarif',required:true,maxBytes:1024}]);assert.deepEqual(reports,[{format:'sarif',job:'scan-*',path:'reports/a.sarif',required:true,maxBytes:1024}]);assert.throws(()=>parseAnalyzerReports([{format:'unknown',path:'x'}]),/must be one of/);assert.throws(()=>parseAnalyzerReports([{format:'junit',path:'..\/x'}]),/invalid repository-relative path/);}finally{legacy.close();incremental.close();}});
test('profile packs and test impact defaults are product-level deterministic inputs',()=>{const t=tempConfig({...baseConfig()});try{withEnvs({CODEX_REVIEW_CONFIG_FILE:t.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>{const config=loadConfig();assert.equal(config.reviewProfile,'general');assert.equal(config.testImpactEnabled,true);assert.deepEqual(config.testPathPrefixes,['test/','tests/']);assert.equal(config.maxRecommendedTests,40);});}finally{t.close();}});
test('canonical config rejects unknown fields and invalid group IDs',()=>{const a=tempConfig({gitlab:{baseUrl:'https://gitlab.test',projects:[1],unexpected:true}}),b=tempConfig({gitlab:{baseUrl:'https://gitlab.test',projects:[1],groups:[{id:0}]}});try{assert.throws(()=>loadStructuredConfig(a.file),/unsupported field/);withEnvs({CODEX_REVIEW_CONFIG_FILE:b.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>assert.throws(()=>loadConfig(),/positive integer/));}finally{a.close();b.close();}});
test('removed projectPolicyFile config field is rejected fail-closed',()=>{const t=tempConfig({...baseConfig(),review:{projectPolicyFile:'.codex-review.json'}});try{assert.throws(()=>loadStructuredConfig(t.file),/unsupported field: projectPolicyFile/);}finally{t.close();}});
test('triggerAssignment defaults to reviewer and rejects legacy Assignee-only fields',()=>{const t=tempConfig({...baseConfig(),review:{triggerAssignment:{mode:'either',userIds:[8,9]}}}),legacy=tempConfig({...baseConfig(),review:{requiredAssigneeUserIds:[8]}}),legacyManual=tempConfig({...baseConfig(),review:{manualReviewBypassAssignee:true}}),invalid=tempConfig({...baseConfig(),review:{triggerAssignment:{mode:'always',userIds:[8]}}});try{withEnvs({CODEX_REVIEW_CONFIG_FILE:t.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>assert.deepEqual(loadConfig().triggerAssignment,{mode:'either',userIds:[8,9]}));assert.throws(()=>loadStructuredConfig(legacy.file),/unsupported field: requiredAssigneeUserIds/);assert.throws(()=>loadStructuredConfig(legacyManual.file),/unsupported field: manualReviewBypassAssignee/);withEnvs({CODEX_REVIEW_CONFIG_FILE:invalid.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>assert.throws(()=>loadConfig(),/must be empty when mode is always/));}finally{t.close();legacy.close();legacyManual.close();invalid.close();}});
test('triggerAssignment default is reviewer with any Reviewer accepted',()=>{const t=tempConfig({...baseConfig()});try{withEnvs({CODEX_REVIEW_CONFIG_FILE:t.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>assert.deepEqual(loadConfig().triggerAssignment,{mode:'reviewer',userIds:[]}));}finally{t.close();}});
test('config file is mandatory',()=>withEnvs({CODEX_REVIEW_CONFIG_FILE:'/definitely/missing.json'},()=>assert.throws(()=>loadStructuredConfig(),/does not exist/)));
test('loadConfig uses config.json for non-secrets and environment only for secrets',()=>{const t=tempConfig({...baseConfig(),server:{host:'127.0.0.2',port:9999,dataDir:'/tmp/codex-review-test'},review:{concurrency:4},runner:{mode:'isolated',socket:'/run/test.sock'}});try{withEnvs({CODEX_REVIEW_CONFIG_FILE:t.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken(),GITLAB_PROJECT_ALLOWLIST:'999',CODEX_RUNNER_SOCKET:'/run/legacy.sock',HOST:'0.0.0.0'},()=>{const config=loadConfig();assert.equal(config.configSchemaVersion,CONFIG_SCHEMA_VERSION);assert.equal(config.host,'127.0.0.2');assert.equal(config.port,9999);assert.deepEqual([...config.gitlabProjectAllowlist],[7,8]);assert.equal(config.runnerMode,'isolated');assert.equal(config.codexRunnerSocket,'/run/test.sock');});}finally{t.close();}});
posixTest('default paths are unprivileged XDG paths',()=>{assert.equal(defaultConfigPath({HOME:'/home/alice'}),'/home/alice/.config/codex-review/config.json');assert.equal(defaultStateDir({HOME:'/home/alice'}),'/home/alice/.local/state/codex-review');assert.equal(defaultRunnerSocket({HOME:'/home/alice'}),'/home/alice/.local/state/codex-review/runner.sock');assert.equal(defaultConfigPath({HOME:'/home/alice',XDG_CONFIG_HOME:'/srv/alice/config'}),'/srv/alice/config/codex-review/config.json');assert.equal(defaultStateDir({HOME:'/home/alice',XDG_STATE_HOME:'/srv/alice/state'}),'/srv/alice/state/codex-review');assert.equal(defaultRunnerSocket({HOME:'/home/alice',XDG_RUNTIME_DIR:'/run/user/1000'}),'/run/user/1000/codex-review/runner.sock');});
posixTest('relative XDG homes are ignored',()=>{assert.equal(defaultConfigPath({HOME:'/home/alice',XDG_CONFIG_HOME:'relative'}),'/home/alice/.config/codex-review/config.json');assert.equal(defaultStateDir({HOME:'/home/alice',XDG_STATE_HOME:'relative'}),'/home/alice/.local/state/codex-review');assert.equal(defaultRunnerSocket({HOME:'/home/alice',XDG_RUNTIME_DIR:'relative'}),'/home/alice/.local/state/codex-review/runner.sock');});
posixTest('loadConfig defaults dataDir and isolated Runner socket to user-writable XDG paths',()=>{const t=tempConfig({...baseConfig(),runner:{mode:'isolated'}});try{withEnvs({HOME:'/home/alice',XDG_STATE_HOME:'/tmp/alice-state',XDG_RUNTIME_DIR:'/tmp/alice-run',CODEX_REVIEW_CONFIG_FILE:t.file,GITLAB_API_TOKEN:'token',GITLAB_WEBHOOK_SIGNING_TOKEN:signingToken()},()=>{const config=loadConfig();assert.equal(config.dataDir,'/tmp/alice-state/codex-review');assert.equal(config.dbPath,'/tmp/alice-state/codex-review/review-service.sqlite');assert.equal(config.codexRunnerSocket,'/tmp/alice-run/codex-review/runner.sock');});}finally{t.close();}});
test('Flow Tracking defaults off and validates deterministic filters',()=>{const{parseFlowTracking}=require('../src/config'),defaults=parseFlowTracking({});assert.equal(defaults.flowTrackingEnabled,false);assert.deepEqual(defaults.flowPipeline.statuses,['failed']);assert.deepEqual(defaults.flowPipeline.refs,['*']);assert.deepEqual(defaults.flowMergeRequest.actions,['merge']);assert.equal(defaults.flowPush.enabled,false);assert.deepEqual(defaults.flowTag.patterns,['v*']);assert.equal(defaults.flowCommitPush.enabled,false);assert.deepEqual(defaults.flowCommitPush.refs,['main','release/*','hotfix/*']);assert.deepEqual(defaults.flowCommitPush.excludeRefs,[]);assert.equal(defaults.flowCommitPush.maxCommits,8);assert.deepEqual(defaults.flowCommitPush.ignoreUsers,[]);assert.throws(()=>parseFlowTracking({commitPush:{maxCommits:21}}),/between 0 and 20/);assert.throws(()=>parseFlowTracking({pipeline:{statuses:['running']}}),/unsupported value/);assert.throws(()=>parseFlowTracking({unexpected:true}),/unsupported field/);});
