'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{estimateChunkTokens,scoreChunkRisk,adaptiveContextConfig,selectModel,selectChunksWithinByteBudget,changedPathsFromCompare,subsetDiffResult,carryForwardFindings,mergeCarriedFindings,TokenBudgetLedger}=require('../src/cost-planner');

test('estimates prompt/output conservatively before execution',()=>{const estimate=estimateChunkTokens('x'.repeat(3000),2);assert.ok(estimate.input>=1500);assert.ok(estimate.output>=456);assert.equal(estimate.total,estimate.input+estimate.output);});
test('risk score expands context and routes low risk to fast model',()=>{const low={files:[{path:'docs/readme.md'}],diffText:'+ wording'},high={files:[{path:'src/auth/token.js'}],diffText:'+ await mutex.lock();\n+ token = secret;'},config={contextEnabled:true,adaptiveContextEnabled:true,codexModel:'strong',codexFastModel:'fast'},policy={maxContextBytes:262144,maxContextFiles:12,contextLines:20};const lowCfg=adaptiveContextConfig(config,policy,low),highCfg=adaptiveContextConfig(config,policy,high);assert.ok(scoreChunkRisk(high)>scoreChunkRisk(low));assert.ok(highCfg.maxContextBytes>lowCfg.maxContextBytes);assert.equal(selectModel(config,lowCfg.riskScore),'fast');assert.equal(selectModel(config,highCfg.riskScore),'strong');});
test('adaptive context never exceeds configured policy caps',()=>{const cfg=adaptiveContextConfig({contextEnabled:true,adaptiveContextEnabled:true},{maxContextBytes:4096,maxContextFiles:1,contextLines:1},{files:[{path:'docs/readme.md'}],diffText:'+ wording'});assert.equal(cfg.maxContextBytes,4096);assert.equal(cfg.maxContextFiles,1);assert.equal(cfg.contextLines,1);});
test('total diff budget keeps highest-risk chunks, reindexes plan, and fails closed on omissions',()=>{const chunks=[{index:0,bytes:700,files:[{path:'docs/a.md'}],diffText:'+ docs'},{index:1,bytes:700,files:[{path:'src/auth/a.js'}],diffText:'+ token = secret'},{index:2,bytes:700,files:[{path:'src/b.js'}],diffText:'+ value'}],plan=selectChunksWithinByteBudget(chunks,1400);assert.equal(plan.complete,false);assert.ok(plan.chunks.some(c=>c.originalIndex===1));assert.deepEqual(plan.chunks.map(c=>c.index),[0,1]);assert.equal(plan.chunks.length,2);assert.equal(plan.omitted.length,1);});
test('incremental helpers review changed paths and carry untouched findings',()=>{const compare={items:[{old_path:'a.js',new_path:'a.js'}]},paths=changedPathsFromCompare(compare),subset=subsetDiffResult({items:[{old_path:'a.js',new_path:'a.js'},{old_path:'b.js',new_path:'b.js'}]},paths),carried=carryForwardFindings([{fingerprint:'a',file:'a.js',severity:'high',category:'correctness',side:'new',line:1,end_line:1,title:'a',description:'a',suggestion:'',confidence:1},{fingerprint:'b',file:'b.js',severity:'medium',category:'test',side:'new',line:2,end_line:2,title:'b',description:'b',suggestion:'',confidence:.9}],paths);assert.equal(subset.items.length,1);assert.equal(carried.length,1);assert.equal(carried[0].file,'b.js');const merged=mergeCarriedFindings({coverageComplete:true,findings:[],allFindings:[],verdict:'pass',truncatedFindingCount:0},carried,{maxFindings:10,severityThreshold:'info',blockingSeverity:'high'});assert.equal(merged.verdict,'needs_attention');});
test('project token reservations prevent concurrent budget overshoot',()=>{const ledger=new TokenBudgetLedger();ledger.reserve('a',7,60,{budget:100,committed:20});assert.throws(()=>ledger.reserve('b',7,30,{budget:100,committed:20}),error=>error.code==='ETOKENBUDGET');assert.equal(ledger.release('a'),60);ledger.reserve('b',7,30,{budget:100,committed:20});assert.equal(ledger.reservedForProject(7),30);});
