'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{DatabaseSync}=require('node:sqlite');const{Store,SCHEMA_VERSION}=require('../src/db');
function withStore(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-db-')),store=new Store(path.join(dir,'test.sqlite'));try{return fn(store);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}}

test('schema 6 initializes fresh and rejects unsupported pre-migration databases',()=>{
  withStore(store=>{assert.equal(store.schemaVersion(),SCHEMA_VERSION);assert.equal(store.synchronousMode(),2);assert.equal(store.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='notification_outbox'").get().name,'notification_outbox');});
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-hardcut-')),dbPath=path.join(dir,'test.sqlite'),legacy=new DatabaseSync(dbPath);legacy.exec("CREATE TABLE review_jobs(id INTEGER PRIMARY KEY); PRAGMA user_version=4;");legacy.close();try{assert.throws(()=>new Store(dbPath),error=>error?.code==='EDBSCHEMA'&&/expected fresh database, Schema 5 migration source, or Schema 6/.test(error.message));}finally{fs.rmSync(dir,{recursive:true,force:true});}
  const dir2=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-hardcut-zero-')),dbPath2=path.join(dir2,'test.sqlite'),unknown=new DatabaseSync(dbPath2);unknown.exec("CREATE TABLE unexpected(id INTEGER PRIMARY KEY);");unknown.close();try{assert.throws(()=>new Store(dbPath2),error=>error?.code==='EDBSCHEMA');}finally{fs.rmSync(dir2,{recursive:true,force:true});}
});
test('serializes same MR jobs while allowing different MRs',()=>withStore(store=>{store.enqueue({projectId:1,mrIid:2,headSha:'h',trigger:'command',dedupeKey:'c1',maxQueueDepth:10});store.enqueue({projectId:1,mrIid:2,headSha:'h',trigger:'command',dedupeKey:'c2',maxQueueDepth:10});store.enqueue({projectId:1,mrIid:3,headSha:'z',trigger:'open',dedupeKey:'z',maxQueueDepth:10});assert.equal(store.claimNext().mr_iid,2);assert.equal(store.claimNext().mr_iid,3);assert.equal(store.claimNext(),null);}));
test('debounce delays automatic review claim',()=>withStore(store=>{store.enqueue({projectId:1,mrIid:2,headSha:'h',trigger:'open',dedupeKey:'h',maxQueueDepth:10,delayMs:60000});assert.equal(store.claimNext(),null);}));
test('binds snapshot/provider gate identity and deduplicates automatic jobs',()=>withStore(store=>{const a=store.enqueue({projectId:1,mrIid:2,headSha:'',trigger:'open',dedupeKey:'event:a',maxQueueDepth:10});store.bindJobSnapshot(a,{baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat',statusProjectId:9,pipelineId:42});assert.equal(store.getJob(a).pipeline_id,42);const b=store.enqueue({projectId:1,mrIid:2,startSha:'s',headSha:'h',trigger:'reconcile',dedupeKey:'snapshot:s:h',maxQueueDepth:10});assert.equal(store.bindJobSnapshot(b,{baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat'}).status,'duplicate');assert.equal(store.getJob(b).status,'duplicate');}));
test('retry availability and restart recovery remain bounded',()=>withStore(store=>{const id=store.enqueue({projectId:1,mrIid:2,headSha:'h',trigger:'open',dedupeKey:'h',maxQueueDepth:10});assert.equal(store.claimNext().id,id);store.retryJob(id,'E',60000);assert.equal(store.claimNext(),null);store.db.prepare("UPDATE review_jobs SET status='running' WHERE id=?").run(id);assert.equal(store.recoverInterruptedJobs(),1);assert.equal(store.getJob(id).status,'queued');}));
test('new snapshot waits for active same-MR job to exit',()=>withStore(store=>{const oldId=store.enqueue({projectId:1,mrIid:2,startSha:'s1',headSha:'h1',trigger:'open',dedupeKey:'snapshot:s1:h1',maxQueueDepth:10});assert.equal(store.claimNext().id,oldId);const newId=store.enqueue({projectId:1,mrIid:2,startSha:'s2',headSha:'h2',trigger:'update',dedupeKey:'snapshot:s2:h2',maxQueueDepth:10});assert.equal(store.getJob(oldId).status,'running');assert.equal(store.claimNext(),null);store.finishJob(oldId,'superseded');assert.equal(store.claimNext().id,newId);}));
test('target start-SHA change supersedes older queued snapshot with same head',()=>withStore(store=>{const oldId=store.enqueue({projectId:1,mrIid:2,startSha:'s1',headSha:'h',trigger:'reconcile',dedupeKey:'snapshot:s1:h',maxQueueDepth:10}),newId=store.enqueue({projectId:1,mrIid:2,startSha:'s2',headSha:'h',trigger:'reconcile',dedupeKey:'snapshot:s2:h',maxQueueDepth:10});assert.equal(store.getJob(oldId).status,'superseded');assert.equal(store.getJob(newId).status,'queued');}));
test('review run/findings/outbox are committed atomically',()=>withStore(store=>{const jobId=store.enqueue({projectId:1,mrIid:2,startSha:'s',headSha:'h',trigger:'open',dedupeKey:'snapshot:s:h',maxQueueDepth:10}),review={verdict:'needs_attention',summary:'s',coverageComplete:true,codexVersion:'v',codexModel:'m',chunkCount:1,rejectedFindingCount:0,truncatedFindingCount:0,usage:{inputTokens:10,outputTokens:2},findings:[{fingerprint:'fp',severity:'medium',category:'test',file:'a.js',side:'new',line:1,endLine:1,title:'t',description:'d',suggestion:'',confidence:1,anchorHash:'a'}]},policy={source:'test',fingerprint:'p'};const runId=store.saveRunWithOutbox(jobId,review,5,policy,[{projectId:1,mrIid:2,type:'summary',dedupeKey:'j:summary',payload:{headSha:'h'}},{projectId:1,mrIid:2,type:'status',dedupeKey:'j:status',payload:{state:'success'}}]);assert.ok(runId);assert.equal(store.db.prepare('SELECT COUNT(*) count FROM review_findings WHERE run_id=?').get(runId).count,1);assert.equal(store.db.prepare('SELECT COUNT(*) count FROM publication_outbox WHERE run_id=?').get(runId).count,2);assert.equal(store.db.prepare('SELECT input_tokens FROM review_runs WHERE id=?').get(runId).input_tokens,10);}));
test('schema 6 persists notification actions atomically with review publication',()=>withStore(store=>{assert.equal(store.schemaVersion(),SCHEMA_VERSION);const jobId=store.enqueue({projectId:1,mrIid:2,startSha:'s',headSha:'h',trigger:'open',dedupeKey:'notification-run',maxQueueDepth:10}),review={verdict:'pass',summary:'ok',coverageComplete:true,findings:[],usage:{}},policy={source:'service-default',fingerprint:'x'},runId=store.saveRunWithOutbox(jobId,review,1,policy,[{projectId:1,mrIid:2,type:'summary',dedupeKey:'publication-1',payload:{body:'ok'}}],null,[{routeName:'team',provider:'feishu',secretRef:'team',eventType:'review.completed',dedupeKey:'notification-1',payload:{type:'review.completed',projectId:1,mrIid:2,title:'MR title',url:'https://gitlab.example/mr/2'}}]);assert.ok(runId>0);assert.equal(store.publicationDepth(),1);assert.equal(store.notificationDepth(),1);const notification=store.claimNotification();assert.equal(notification.route_name,'team');assert.equal(notification.payload.projectId,1);assert.equal(notification.payload.title,'MR title');store.retryNotification(notification.id,'ENOTIFYNETWORK',0);assert.equal(store.notificationDepth(),1);const retry=store.claimNotification();assert.equal(retry.attempt,2);store.finishNotification(retry.id,'remote');assert.equal(store.notificationDepth(),0);assert.equal(store.db.prepare('SELECT status FROM notification_outbox WHERE id=?').get(retry.id).status,'delivered');}));
test('failed job and notification outbox commit atomically and idempotently',()=>withStore(store=>{const id=store.enqueue({projectId:1,mrIid:2,trigger:'push',dedupeKey:'atomic',maxQueueDepth:10}),action={routeName:'ops',provider:'wecom',secretRef:'ops',eventType:'review.failed',dedupeKey:'job:atomic:ops:review.failed',payload:{type:'review.failed',projectId:1,mrIid:2}};store.finishJobWithNotifications(id,'failed','EFAIL',[action]);assert.equal(store.getJob(id).status,'failed');assert.equal(store.notificationDepth(),1);store.finishJobWithNotifications(id,'failed','EFAIL',[action]);assert.equal(store.notificationDepth(),1);}));
test('notification restart recovery is independent from review and publication',()=>withStore(store=>{const id=store.enqueueNotification({routeName:'ops',provider:'wecom',secretRef:'ops',eventType:'service.degraded',dedupeKey:'system-degraded',payload:{type:'service.degraded'}});const item=store.claimNotification();assert.equal(item.id,id);assert.equal(store.recoverNotifications(),1);assert.equal(store.db.prepare('SELECT status FROM notification_outbox WHERE id=?').get(id).status,'pending');store.failNotification(id,'ENOTIFYREMOTE');assert.equal(store.db.prepare('SELECT status FROM notification_outbox WHERE id=?').get(id).status,'failed');}));
test('outbox preserves per-run ordering and recovers publishing actions',()=>withStore(store=>{const jobId=store.enqueue({projectId:1,mrIid:2,headSha:'h',trigger:'open',dedupeKey:'h',maxQueueDepth:10}),runId=store.saveRunWithOutbox(jobId,{verdict:'pass',summary:'',coverageComplete:true,findings:[],usage:{}},1,{source:'x',fingerprint:'p'},[{projectId:1,mrIid:2,type:'summary',dedupeKey:'a',payload:{}},{projectId:1,mrIid:2,type:'status',dedupeKey:'b',payload:{}}]);const first=store.claimPublication();assert.equal(first.dedupe_key,'a');assert.equal(store.claimPublication(),null);store.finishPublication(first.id);const second=store.claimPublication();assert.equal(second.dedupe_key,'b');store.db.prepare("UPDATE publication_outbox SET status='publishing' WHERE id=?").run(second.id);assert.equal(store.recoverPublications(),1);assert.equal(store.db.prepare('SELECT status FROM publication_outbox WHERE id=?').get(second.id).status,'pending');assert.equal(runId,first.run_id);}));
