'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const crypto=require('node:crypto');
const{createHttpServer}=require('../src/http');
function request(port,body,headers={}){return new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port,path:'/webhooks/gitlab',method:'POST',headers},res=>{let text='';res.on('data',chunk=>text+=chunk);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(text)}));});req.on('error',reject);req.end(body);});}
test('authenticated Pipeline Hook is delegated to FlowTracker without queueing Review',async()=>{const key=Buffer.alloc(32,9),config={webhookMaxBodyBytes:65536,webhookSigningToken:`whsec_${key.toString('base64')}`,webhookMaxSkewSeconds:300,webhookExpectedInstance:'https://gitlab.example.test',requireInstanceHeader:true,gitlabProjectAllowlist:new Set([7]),readinessCacheMs:1000,workerConcurrency:1};let reviewCalls=0,flowCalls=0,observed=null;const store={recordWebhook:()=>true,markWebhookProcessed:()=>{},forgetWebhook:()=>{},queueDepth:()=>0,stats:()=>({jobs:{},notifications:{},flowStates:0,webhookCount:0,findings:0,schemaVersion:7}),ping:()=>true,schemaVersion:()=>7},service={stopping:false,workers:[Promise.resolve()],active:new Map(),handleEvent:event=>{reviewCalls++;assert.equal(event.kind,'ignored');return{status:'ignored'};}},flowTracker={handle(payload,headers,webhookId){flowCalls++;observed={payload,headers,webhookId};return{status:'notified',eventType:'gitlab.pipeline.failed',notifications:1};}},gitlab={getVersion:async()=>{throw new Error('GitLab API must not be called from webhook ingress');}};const server=createHttpServer({config,store,service,flowTracker,gitlab,logger:{error(){},warn(){}}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const body=JSON.stringify({object_kind:'pipeline',project:{id:7},object_attributes:{id:88,status:'failed',ref:'main',source:'push'}}),id='pipeline-webhook-1',timestamp=String(Math.floor(Date.now()/1000)),signature='v1,'+crypto.createHmac('sha256',key).update(`${id}.${timestamp}.${body}`).digest('base64'),result=await request(server.address().port,body,{'content-type':'application/json','webhook-id':id,'webhook-timestamp':timestamp,'webhook-signature':signature,'x-gitlab-instance':'https://gitlab.example.test','x-gitlab-event':'Pipeline Hook'});assert.equal(result.status,202);assert.equal(result.body.status,'notified');assert.equal(reviewCalls,1);assert.equal(flowCalls,1);assert.equal(observed.webhookId,id);assert.equal(observed.payload.object_kind,'pipeline');assert.equal(observed.headers['x-gitlab-event'],'Pipeline Hook');}finally{await new Promise(resolve=>server.close(resolve));}});


test('authenticated ordinary Push Hook is delegated to FlowTracker without Review or GitLab API calls',async()=>{const key=Buffer.alloc(32,10),config={webhookMaxBodyBytes:65536,webhookSigningToken:`whsec_${key.toString('base64')}`,webhookMaxSkewSeconds:300,webhookExpectedInstance:'https://gitlab.example.test',requireInstanceHeader:true,gitlabProjectAllowlist:new Set([7]),readinessCacheMs:1000,workerConcurrency:1};let reviewCalls=0,flowCalls=0;const store={recordWebhook:()=>true,markWebhookProcessed:()=>{},forgetWebhook:()=>{},queueDepth:()=>0,stats:()=>({jobs:{},notifications:{},flowStates:0,webhookCount:0,findings:0,schemaVersion:7}),ping:()=>true,schemaVersion:()=>7},service={stopping:false,workers:[Promise.resolve()],active:new Map(),handleEvent:event=>{reviewCalls++;assert.equal(event.kind,'ignored');return{status:'ignored'};}},flowTracker={handle(payload,headers,webhookId){flowCalls++;assert.equal(payload.object_kind,'push');assert.equal(headers['x-gitlab-event'],'Push Hook');assert.equal(webhookId,'push-webhook-1');return{status:'notified',eventType:'gitlab.push.committed',notifications:1};}},gitlab={getVersion:async()=>{throw new Error('GitLab API must not be called from webhook ingress');}};const server=createHttpServer({config,store,service,flowTracker,gitlab,logger:{error(){},warn(){}}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const body=JSON.stringify({object_kind:'push',project:{id:7},ref:'refs/heads/main',before:'a'.repeat(40),after:'b'.repeat(40),commits:[]}),id='push-webhook-1',timestamp=String(Math.floor(Date.now()/1000)),signature='v1,'+crypto.createHmac('sha256',key).update(`${id}.${timestamp}.${body}`).digest('base64'),result=await request(server.address().port,body,{'content-type':'application/json','webhook-id':id,'webhook-timestamp':timestamp,'webhook-signature':signature,'x-gitlab-instance':'https://gitlab.example.test','x-gitlab-event':'Push Hook'});assert.equal(result.status,202);assert.equal(result.body.status,'notified');assert.equal(reviewCalls,1);assert.equal(flowCalls,1);}finally{await new Promise(resolve=>server.close(resolve));}});
