'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{normalizeFlowEvent,FlowTracker,matches}=require('../src/flow-tracking');
function config(){return{flowTrackingEnabled:true,gitlabProjectAllowlist:new Set([101]),flowPipeline:{enabled:true,statuses:['success','failed','canceled'],refs:['main','release/*'],sources:['push','merge_request_event','web'],jobs:{mode:'failed-only',patterns:['build-*','test-*','security-*'],maxItems:2}},flowMergeRequest:{enabled:true,actions:['merge']},flowTag:{enabled:true,actions:['create'],patterns:['v*']},flowPush:{enabled:true,actions:['delete'],patterns:['release/*']}};}
test('glob matcher is anchored and deterministic',()=>{assert.equal(matches('release/1.0',['release/*']),true);assert.equal(matches('feature/release/1.0',['release/*']),false);assert.equal(matches('main',['main']),true);});
test('pipeline flow tracks terminal status and only selected failed jobs',()=>{const flow=normalizeFlowEvent({object_kind:'pipeline',project:{id:101,web_url:'https://gitlab.example/p/a'},user:{name:'CI User'},object_attributes:{id:77,status:'failed',ref:'main',source:'push',duration:12.5,finished_at:'2026-08-31T01:00:00Z'},builds:[{name:'build-linux',stage:'build',status:'success',duration:2},{name:'test-unit',stage:'test',status:'failed',duration:4,failure_reason:'script_failure',url:'https://gitlab.example/job/1'},{name:'security-sast',stage:'security',status:'failed',duration:3,failure_reason:'script_failure',url:'https://gitlab.example/job/2'},{name:'docs',stage:'docs',status:'failed'}]}, {},config());assert.equal(flow.eventType,'gitlab.pipeline.failed');assert.equal(flow.externalId,'77');assert.equal(flow.url,'https://gitlab.example/p/a/-/pipelines/77');assert.deepEqual(flow.jobs.map(j=>j.name),['test-unit','security-sast']);assert.equal(flow.durationMs,12500);});
test('running pipeline updates state but does not notify',()=>{const flow=normalizeFlowEvent({object_kind:'pipeline',project:{id:101},object_attributes:{id:77,status:'running',ref:'main',source:'push'}},{},config());assert.equal(flow.state,'running');assert.equal(flow.eventType,null);});
test('pipeline ref and source filters suppress unrelated flows',()=>{assert.equal(normalizeFlowEvent({object_kind:'pipeline',project:{id:101},object_attributes:{id:1,status:'failed',ref:'feature/x',source:'push'}},{},config()),null);assert.equal(normalizeFlowEvent({object_kind:'pipeline',project:{id:101},object_attributes:{id:1,status:'failed',ref:'main',source:'schedule'}},{},config()),null);});
test('MR, tag and branch lifecycle subscriptions are explicit',()=>{const c=config();assert.equal(normalizeFlowEvent({object_kind:'merge_request',project:{id:101},object_attributes:{iid:4,action:'open'}},{},c),null);assert.equal(normalizeFlowEvent({object_kind:'merge_request',project:{id:101},object_attributes:{iid:4,action:'merge',title:'Done',source_branch:'x',target_branch:'main'}},{},c).eventType,'gitlab.mr.merged');assert.equal(normalizeFlowEvent({object_kind:'tag_push',project:{id:101},ref:'refs/tags/v1.2.0',before:'0'.repeat(40),after:'a'.repeat(40)},{},c).eventType,'gitlab.tag.created');assert.equal(normalizeFlowEvent({object_kind:'push',project:{id:101},ref:'refs/heads/release/1.2',before:'a'.repeat(40),after:'0'.repeat(40)},{},c).eventType,'gitlab.branch.deleted');});
test('FlowTracker persists every state transition but only routes subscribed terminal event',()=>{const transitions=[],notifications=[],store={transitionFlowState(input){transitions.push(input);if(input.status==='running')return{changed:true,previousStatus:'',revision:1};if(input.status==='failed')return{changed:true,previousStatus:'running',revision:2};return{changed:false,previousStatus:input.status,revision:2};},enqueueNotification(action){notifications.push(action);}};const plan=(cfg,event,key)=>event.type?[{routeName:'ci',provider:'feishu',secretRef:'ci',eventType:event.type,dedupeKey:key,payload:event}]:[];const tracker=new FlowTracker({config:config(),store,planNotificationActions:plan,logger:{info(){}}});const base={object_kind:'pipeline',project:{id:101,web_url:'https://gitlab.example/p/a'},object_attributes:{id:9,ref:'main',source:'push'}};assert.equal(tracker.handle({...base,object_attributes:{...base.object_attributes,status:'running'}},{},'w1').status,'tracked');const result=tracker.handle({...base,object_attributes:{...base.object_attributes,status:'failed'}},{},'w2');assert.equal(result.status,'notified');assert.equal(notifications.length,1);assert.equal(notifications[0].payload.previousStatus,'running');assert.equal(notifications[0].dedupeKey,'flow:101:pipeline:9:2');assert.equal(transitions.length,2);});
test('FlowTracker never routes out-of-scope projects',()=>{let called=false;const tracker=new FlowTracker({config:config(),store:{transitionFlowState(){called=true;}},planNotificationActions(){return[];}});assert.equal(tracker.handle({object_kind:'pipeline',project:{id:999},object_attributes:{id:1,status:'failed',ref:'main',source:'push'}},{},'x').status,'ignored');assert.equal(called,false);});
