'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{normalizeFlowEvent,FlowTracker,matches,selectedCommits}=require('../src/flow-tracking');
function config(){return{flowTrackingEnabled:true,gitlabProjectAllowlist:new Set([101]),flowPipeline:{enabled:true,statuses:['success','failed','canceled'],refs:['main','release/*'],sources:['push','merge_request_event','web'],jobs:{mode:'failed-only',patterns:['build-*','test-*','security-*'],maxItems:2}},flowMergeRequest:{enabled:true,actions:['merge']},flowTag:{enabled:true,actions:['create'],patterns:['v*']},flowPush:{enabled:true,actions:['delete'],patterns:['release/*']},flowCommitPush:{enabled:true,refs:['main','release/*','hotfix/*'],excludeRefs:['release/noisy-*'],maxCommits:2,includeMergeCommits:false,includeCommitMessage:true,ignoreUsers:['release-bot','ci-*']}};}
test('glob matcher is anchored and deterministic',()=>{assert.equal(matches('release/1.0',['release/*']),true);assert.equal(matches('feature/release/1.0',['release/*']),false);assert.equal(matches('main',['main']),true);});
test('pipeline flow tracks terminal status and only selected failed jobs',()=>{const flow=normalizeFlowEvent({object_kind:'pipeline',project:{id:101,web_url:'https://gitlab.example/p/a'},user:{name:'CI User'},object_attributes:{id:77,status:'failed',ref:'main',source:'push',duration:12.5,finished_at:'2026-08-31T01:00:00Z'},builds:[{name:'build-linux',stage:'build',status:'success',duration:2},{name:'test-unit',stage:'test',status:'failed',duration:4,failure_reason:'script_failure',url:'https://gitlab.example/job/1'},{name:'security-sast',stage:'security',status:'failed',duration:3,failure_reason:'script_failure',url:'https://gitlab.example/job/2'},{name:'docs',stage:'docs',status:'failed'}]}, {},config());assert.equal(flow.eventType,'gitlab.pipeline.failed');assert.deepEqual(flow.jobs.map(j=>j.name),['test-unit','security-sast']);assert.equal(flow.durationMs,12500);});
test('running pipeline updates state but does not notify',()=>{const flow=normalizeFlowEvent({object_kind:'pipeline',project:{id:101},object_attributes:{id:77,status:'running',ref:'main',source:'push'}},{},config());assert.equal(flow.state,'running');assert.equal(flow.eventType,null);});
test('MR, tag and branch lifecycle subscriptions are explicit',()=>{const c=config();assert.equal(normalizeFlowEvent({object_kind:'merge_request',project:{id:101},object_attributes:{iid:4,action:'open'}},{},c),null);assert.equal(normalizeFlowEvent({object_kind:'merge_request',project:{id:101},object_attributes:{iid:4,action:'merge'}},{},c).eventType,'gitlab.mr.merged');assert.equal(normalizeFlowEvent({object_kind:'tag_push',project:{id:101},ref:'refs/tags/v1.2.0',before:'0'.repeat(40),after:'a'.repeat(40)},{},c).eventType,'gitlab.tag.created');assert.equal(normalizeFlowEvent({object_kind:'push',project:{id:101},ref:'refs/heads/release/1.2',before:'a'.repeat(40),after:'0'.repeat(40)},{},c).eventType,'gitlab.branch.deleted');});
test('ordinary Push Hook becomes one aggregated commit event',()=>{const flow=normalizeFlowEvent({object_kind:'push',project:{id:101,web_url:'https://gitlab.example/p/a'},ref:'refs/heads/main',before:'a'.repeat(40),after:'b'.repeat(40),event_created_at:'2026-08-31T03:00:00Z',user_name:'Lei',user_username:'lei',total_commits_count:3,commits:[{id:'1'.repeat(40),title:'fix: one',author:{name:'A'}},{id:'2'.repeat(40),message:'Merge branch x',author:{name:'B'}},{id:'3'.repeat(40),message:'feat: three\nbody',author:{name:'C'}}]}, {},config());assert.equal(flow.eventType,'gitlab.push.committed');assert.equal(flow.kind,'commit_push');assert.equal(flow.externalId,'main');assert.equal(flow.state,'b'.repeat(40));assert.equal(flow.commitCount,3);assert.deepEqual(flow.commits.map(c=>c.message),['fix: one','feat: three']);assert.equal(flow.omittedCommitCount,1);assert.match(flow.url,/compare\/a{40}\.\.\.b{40}$/);});
test('commit push filters refs exclusions bot users and branch lifecycle',()=>{const base={object_kind:'push',project:{id:101},before:'a'.repeat(40),after:'b'.repeat(40),commits:[]},c=config();assert.equal(normalizeFlowEvent({...base,ref:'refs/heads/feature/x'},{},c),null);assert.equal(normalizeFlowEvent({...base,ref:'refs/heads/release/noisy-1'},{},c),null);assert.equal(normalizeFlowEvent({...base,ref:'refs/heads/main',user_username:'CI-BUILD'},{},c),null);assert.equal(normalizeFlowEvent({...base,ref:'refs/heads/main',before:'0'.repeat(40)},{},c),null);assert.equal(normalizeFlowEvent({...base,ref:'refs/heads/release/1',after:'0'.repeat(40)},{},c).eventType,'gitlab.branch.deleted');});
test('commit selection honors maxCommits and message privacy',()=>{const picked=selectedCommits([{id:'1'.repeat(40),message:'one'},{id:'2'.repeat(40),message:'two'},{id:'3'.repeat(40),message:'three'}],{maxCommits:2,includeMergeCommits:true,includeCommitMessage:false});assert.equal(picked.length,2);assert.equal(picked[0].message,'');});
test('commit push durable state dedupes same branch head across delivery IDs',()=>{let current='',revision=0,notifications=0;const store={transitionFlowState(input,factory){if(input.status===current)return{changed:false,previousStatus:current,revision};const previousStatus=current;current=input.status;revision++;const actions=factory({changed:true,previousStatus,revision})||[];notifications+=actions.length;return{changed:true,previousStatus,revision,notificationCount:actions.length};}};const tracker=new FlowTracker({config:config(),store,planNotificationActions:(cfg,event,key)=>[{routeName:'dev',provider:'feishu',secretRef:'dev',eventType:event.type,dedupeKey:key,payload:event}],logger:{info(){}}});const payload={object_kind:'push',project:{id:101},ref:'refs/heads/main',before:'a'.repeat(40),after:'b'.repeat(40),user_username:'lei',commits:[]};assert.equal(tracker.handle(payload,{},'d1').status,'notified');assert.equal(tracker.handle(payload,{},'d2').status,'flow_duplicate');assert.equal(notifications,1);});
test('FlowTracker never routes out-of-scope projects',()=>{let called=false;const tracker=new FlowTracker({config:config(),store:{transitionFlowState(){called=true;}},planNotificationActions(){return[];}});assert.equal(tracker.handle({object_kind:'pipeline',project:{id:999},object_attributes:{id:1,status:'failed',ref:'main',source:'push'}},{},'x').status,'ignored');assert.equal(called,false);});
