'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const{createServiceModelRouter,executeRoleAwareReview,shouldAdjudicate}=require('../src/model-routing-runtime');

const registry={revision:'test-registry-1',models:[
  {provider:'relay',model:'scout-fast',class:'fast',roles:['scout'],status:'approved',health:'healthy',qualificationId:'q-scout'},
  {provider:'relay',model:'review-balanced',class:'balanced',roles:['reviewer'],status:'approved',health:'healthy',qualificationId:'q-review'},
  {provider:'relay',model:'judge-frontier',class:'frontier',roles:['adjudicator'],status:'approved',health:'healthy',qualificationId:'q-judge'},
  {provider:'relay',model:'shadow-next',class:'balanced',roles:['reviewer'],status:'shadow',health:'healthy',qualificationId:'q-shadow'}
]};
function config(overrides={}){return{codexProviderMode:'openai-compatible',codexModelSelectionStrategy:'auto',codexModelCompatibilityPolicy:'strict',codexModelCandidates:[],codexFixedModel:'',codexScoutEnabled:true,codexAdjudicatorEnabled:true,codexAdjudicatorMinSeverity:'high',codexShadowCandidate:'relay/shadow-next',...overrides};}
function router(overrides={}){return createServiceModelRouter(config(overrides),{registryResolution:{registry,source:'explicit'},runtimeInspection:{providerId:'relay'}});}
function finding(severity='high',title='finding'){return{severity,category:'correctness',file:'a.js',side:'new',line:1,endLine:1,title,description:'supported',suggestion:'fix',confidence:.95};}

test('routes approved Scout, Reviewer and Adjudicator on one provider and allows shadow-status candidate only for shadow',()=>{const r=router();assert.equal(r.scout().model,'scout-fast');assert.equal(r.reviewer().model,'review-balanced');assert.equal(r.adjudicator().model,'judge-frontier');assert.equal(r.shadow().model,'shadow-next');assert.equal(r.reviewer().selection.crossProviderFallback,false);});
test('cross-provider shadow is rejected',()=>assert.throws(()=>router({codexShadowCandidate:'other/shadow-next'}).shadow(),error=>error.code==='MODEL_CROSS_PROVIDER_FORBIDDEN'));
test('no Registry keeps Auto Reviewer unmanaged but required Adjudicator fails closed and Preference cannot fake routing',()=>{const auto=createServiceModelRouter(config({codexScoutEnabled:false,codexAdjudicatorEnabled:false,codexShadowCandidate:''}),{registryResolution:{registry:null,source:'none'},runtimeInspection:{providerId:'relay'}});assert.equal(auto.reviewer().managed,false);assert.equal(auto.reviewer().model,'');assert.throws(()=>auto.adjudicator(),error=>error.code==='MODEL_UNAVAILABLE');const pref=createServiceModelRouter(config({codexModelSelectionStrategy:'preference',codexModelCandidates:[{provider:'relay',model:'review-balanced'}],codexScoutEnabled:false,codexShadowCandidate:''}),{registryResolution:{registry:null,source:'none'},runtimeInspection:{providerId:'relay'}});assert.throws(()=>pref.reviewer(),error=>error.code==='MODEL_UNAVAILABLE');});
test('high Reviewer finding triggers Adjudicator; shadow never replaces production result',async()=>{const order=[],outputs={scout:[finding('medium','scout')],reviewer:[finding('high','reviewer')],adjudicator:[finding('high','adjudicated')],shadow:[finding('critical','shadow-only')]};const r=router();const runCodexFn=async(prompt,execution)=>{const model=execution.codexModel;let role=model==='scout-fast'?'scout':model==='review-balanced'?'reviewer':model==='judge-frontier'?'adjudicator':'shadow';order.push(role);return{model,usage:{inputTokens:10,outputTokens:2},durationMs:5,parsed:{findings:outputs[role]}};};const result=await executeRoleAwareReview({prompt:'immutable evidence',config:config(),maxFindings:10,router:r,runCodexFn,validateResult:parsed=>({findings:parsed.findings,rejected:0,filtered:0,modelFindingCount:parsed.findings.length})});assert.deepEqual(order,['scout','reviewer','adjudicator','shadow']);assert.equal(result.finalValidated.findings[0].title,'adjudicated');assert.equal(result.shadowComparison.candidateOnly.length,1);assert.equal(result.calls.filter(x=>x.role==='adjudicator').length,1);assert.equal(result.modelEvidence.length,3);});
test('low severity Reviewer result does not invoke Adjudicator',async()=>{const order=[],r=router({codexScoutEnabled:false,codexShadowCandidate:''}),runCodexFn=async(_prompt,execution)=>{order.push(execution.codexModel);return{model:execution.codexModel,usage:{},parsed:{findings:[finding('medium','reviewer')]}};};const result=await executeRoleAwareReview({prompt:'evidence',config:config({codexScoutEnabled:false,codexShadowCandidate:''}),maxFindings:10,router:r,runCodexFn,validateResult:p=>({findings:p.findings,rejected:0,filtered:0,modelFindingCount:p.findings.length})});assert.deepEqual(order,['review-balanced']);assert.equal(result.finalValidated.findings[0].title,'reviewer');assert.equal(shouldAdjudicate(result.finalValidated,'high'),false);});
