'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{discoverProjects,ProjectScopeManager}=require('../src/project-scope');const{ReviewService}=require('../src/service');
function config(overrides={}){return{gitlabScopeWildcard:false,gitlabProjectAllowlist:new Set([1]),gitlabGroups:[{id:20,includeSubgroups:true}],...overrides};}

test('projects and group discoveries are merged and deduplicated',async()=>{const calls=[];const gitlab={paginated:async(path,query)=>(calls.push({path,query}),{complete:true,items:[{id:1},{id:2},{id:3}]})};const result=await discoverProjects(gitlab,config());assert.deepEqual([...result.projects],[1,2,3]);assert.equal(result.explicitProjects,1);assert.equal(result.discoveredProjects,2);assert.equal(result.mode,'projects+groups');assert.equal(calls[0].query.include_subgroups,'true');assert.equal(calls[0].query.archived,'false');assert.equal(calls[0].query.with_merge_requests_enabled,'true');});
test('group without subgroup expansion sends include_subgroups=false',async()=>{let seen;const gitlab={paginated:async(_path,query)=>(seen=query,{complete:true,items:[{id:2}]})};await discoverProjects(gitlab,config({gitlabGroups:[{id:21,includeSubgroups:false}]}));assert.equal(seen.include_subgroups,'false');});
test('incomplete group pagination fails closed',async()=>{const gitlab={paginated:async()=>({complete:false,items:[{id:2}]})};await assert.rejects(()=>discoverProjects(gitlab,config()),error=>error.code==='EPROJECTSCOPEPAGINATION');});
test('group discovery HTTP failure fails closed',async()=>{const gitlab={paginated:async()=>{const error=new Error('down');error.code='EGITLABNETWORK';throw error;}};await assert.rejects(()=>discoverProjects(gitlab,config()),error=>error.code==='EPROJECTSCOPE');});
test('wildcard remains webhook-only and does not call discovery API',async()=>{let calls=0;const result=await discoverProjects({paginated:async()=>{calls++;}},config({gitlabScopeWildcard:true,gitlabProjectAllowlist:null,gitlabGroups:[]}));assert.equal(result.projects,null);assert.equal(result.mode,'webhook-only-wildcard');assert.equal(calls,0);});
test('refresh replaces scope only after complete discovery',async()=>{let fail=false;const gitlab={paginated:async()=>{if(fail)throw Object.assign(new Error('down'),{code:'EGITLABNETWORK'});return{complete:true,items:[{id:2}]};}};const manager=new ProjectScopeManager(gitlab,config());await manager.refresh();assert.deepEqual([...manager.projects],[1,2]);fail=true;await assert.rejects(()=>manager.refresh());assert.deepEqual([...manager.projects],[1,2]);assert.equal(manager.healthy,false);assert.equal(manager.lastError,'EPROJECTSCOPE');});
test('reconciliation immediately follows the refreshed mutable scope',async()=>{const scope=new Set([1]),seen=[],store={enqueue:({projectId})=>(seen.push(projectId),seen.length)},gitlab={listOpenMergeRequests:async projectId=>({complete:true,items:[{iid:projectId,source_branch:'feat',diff_refs:{base_sha:'b',start_sha:`s${projectId}`,head_sha:`h${projectId}`}}]})},service=new ReviewService({config:{gitlabProjectAllowlist:scope,reviewDraftMergeRequests:false,maxQueueDepth:10,reviewDebounceMs:0},store,gitlab,logger:{warn(){}}});await service.reconcile();scope.clear();scope.add(2);await service.reconcile();assert.deepEqual(seen,[1,2]);});
