'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{Store}=require('../src/db');const{Publisher}=require('../src/publication');
function env(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'codex-publish-')),store=new Store(path.join(dir,'db.sqlite'));return{store,close(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function config(){return{maxPublishAttempts:3,retryBaseDelayMs:1,retryMaxDelayMs:10,publisherConcurrency:1,publisherPollIntervalMs:1};}

test('publisher discovers existing unresolved fingerprint instead of duplicating discussion',async()=>{const e=env();const job=e.store.enqueue({projectId:7,mrIid:9,headSha:'h',startSha:'s',trigger:'open',dedupeKey:'x',maxQueueDepth:10});const run=e.store.saveRunWithOutbox(job,{verdict:'needs_attention',summary:'',coverageComplete:true,usage:{},findings:[{fingerprint:'fp',severity:'medium',category:'test',file:'a.js',side:'new',line:1,endLine:1,title:'t',description:'d',suggestion:'',confidence:1,anchorHash:'ah'}]},1,{source:'x',fingerprint:'p'},[{projectId:7,mrIid:9,type:'finding',dedupeKey:'find',payload:{headSha:'h',startSha:'s',finding:{fingerprint:'fp',severity:'medium',title:'t',description:'d',suggestion:'',side:'new',line:1},diffRefs:{base_sha:'b',start_sha:'s',head_sha:'h'},oldPath:'a.js',newPath:'a.js'}}]);let creates=0;const gitlab={getMergeRequest:async()=>({state:'opened',diff_refs:{start_sha:'s',head_sha:'h'}}),findDiscussionByFingerprint:async()=>({id:'existing',notes:[{resolvable:true,resolved:false}]}),createDiscussion:async()=>{creates++;return{id:'new'};}};const publisher=new Publisher({config:config(),store:e.store,gitlab,logger:{warn(){},info(){}}});try{const item=e.store.claimPublication();await publisher.process(item);assert.equal(creates,0);assert.equal(e.store.findingsForRun(run)[0].discussion_id,'existing');assert.equal(e.store.db.prepare('SELECT status FROM publication_outbox WHERE id=?').get(item.id).status,'published');}finally{e.close();}});

test('human-resolved old fingerprint creates a new current discussion',async()=>{const e=env();const job=e.store.enqueue({projectId:7,mrIid:9,headSha:'h',startSha:'s',trigger:'open',dedupeKey:'x',maxQueueDepth:10});e.store.saveRunWithOutbox(job,{verdict:'needs_attention',summary:'',coverageComplete:true,usage:{},findings:[{fingerprint:'fp',severity:'medium',category:'test',file:'a.js',side:'new',line:1,endLine:1,title:'t',description:'d',suggestion:'',confidence:1,anchorHash:'ah'}]},1,{source:'x',fingerprint:'p'},[{projectId:7,mrIid:9,type:'finding',dedupeKey:'find',payload:{headSha:'h',startSha:'s',finding:{fingerprint:'fp',severity:'medium',title:'t',description:'d',suggestion:'',side:'new',line:1},diffRefs:{base_sha:'b',start_sha:'s',head_sha:'h'},oldPath:'a.js',newPath:'a.js'}}]);let creates=0;const gitlab={getMergeRequest:async()=>({state:'opened',diff_refs:{start_sha:'s',head_sha:'h'}}),findDiscussionByFingerprint:async()=>({id:'old',notes:[{resolvable:true,resolved:true}]}),createDiscussion:async()=>{creates++;return{id:'new'};}};const publisher=new Publisher({config:config(),store:e.store,gitlab,logger:{warn(){},info(){}}});try{await publisher.process(e.store.claimPublication());assert.equal(creates,1);}finally{e.close();}});

test('delayed running status is cancelled after job reaches terminal state',async()=>{const e=env();const job=e.store.enqueue({projectId:7,mrIid:9,headSha:'h',startSha:'s',trigger:'open',dedupeKey:'x',maxQueueDepth:10});e.store.bindJobSnapshot(job,{baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat',statusProjectId:7,pipelineId:1});e.store.finishJob(job,'pass');e.store.enqueuePublication({projectId:7,mrIid:9,type:'status',dedupeKey:`job:${job}:status:running`,payload:{statusProjectId:7,headSha:'h',state:'running',ref:'feat',pipelineId:1}});let called=0;const publisher=new Publisher({config:config(),store:e.store,gitlab:{setCommitStatus:async()=>{called++;}},logger:{warn(){},info(){}}});try{const item=e.store.claimPublication();await publisher.process(item);assert.equal(called,0);assert.equal(e.store.db.prepare('SELECT status FROM publication_outbox WHERE id=?').get(item.id).status,'cancelled');}finally{e.close();}});

test('transient publication failure retries without creating another review run',async()=>{const e=env();const job=e.store.enqueue({projectId:7,mrIid:9,headSha:'h',trigger:'open',dedupeKey:'x',maxQueueDepth:10});e.store.saveRunWithOutbox(job,{verdict:'pass',summary:'',coverageComplete:true,usage:{},findings:[]},1,{source:'x',fingerprint:'p'},[{projectId:7,mrIid:9,type:'status',dedupeKey:'final',payload:{statusProjectId:7,headSha:'h',state:'success'}}]);const publisher=new Publisher({config:config(),store:e.store,gitlab:{setCommitStatus:async()=>{const error=new Error('down');error.code='EGITLABNETWORK';throw error;}},logger:{warn(){},info(){}}});try{const item=e.store.claimPublication();await publisher.process(item);assert.equal(e.store.db.prepare('SELECT status FROM publication_outbox WHERE id=?').get(item.id).status,'pending');assert.equal(e.store.db.prepare('SELECT COUNT(*) count FROM review_runs').get().count,1);}finally{e.close();}});
