'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const{ReviewService,retryable,isDraft}=require('../src/service');
const{Store}=require('../src/db');

function tempStore(prefix='codex-review-service-test-'){const dir=fs.mkdtempSync(path.join(os.tmpdir(),prefix)),store=new Store(path.join(dir,'db.sqlite'));return{store,close(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
function config(overrides={}){return{gitlabProjectAllowlist:new Set([7]),maxQueueDepth:10,manualMinAccessLevel:30,maxJobAttempts:2,retryBaseDelayMs:10,retryMaxDelayMs:100,jobTimeoutSeconds:30,maxDiffBytes:4096,maxTotalDiffBytes:4096,maxReviewChunks:2,maxFindings:10,maxPublishedFindings:10,minConfidence:0.7,blockingSeverity:'high',reviewTimeoutSeconds:30,codexPath:'codex',codexModel:'',codexFastModel:'',codexHome:'',workerConcurrency:1,pollIntervalMs:10,autoResolveObsolete:true,reviewDebounceMs:0,reviewDraftMergeRequests:false,triggerAssignment:{mode:'always',userIds:[]},mrMaxTokenBudget:0,projectDailyTokenBudget:0,contextEnabled:false,adaptiveContextEnabled:true,maxContextBytes:0,maxContextFiles:0,contextLines:0,skipGeneratedFiles:true,blockUnreviewableFiles:false,...overrides};}
function policy(overrides={}){return{language:'en',maxDiffBytes:4096,maxReviewChunks:2,maxFindings:10,maxPublishedFindings:10,minConfidence:0.7,blockingSeverity:'high',severityThreshold:'info',timeoutSeconds:30,extraInstructions:'',skipGeneratedFiles:true,blockUnreviewableFiles:false,maxContextBytes:0,maxContextFiles:0,contextLines:0,source:'test',fingerprint:'a'.repeat(64),...overrides};}
const BASE_SHA='b'.repeat(40),START_SHA='c'.repeat(40),HEAD_SHA='d'.repeat(40);
function mr(overrides={}){return{project_id:7,source_project_id:7,target_project_id:7,iid:9,state:'opened',draft:false,source_branch:'feat',target_branch:'main',diff_refs:{base_sha:BASE_SHA,start_sha:START_SHA,head_sha:HEAD_SHA},...overrides};}
function outbox(store){return store.db.prepare('SELECT * FROM publication_outbox ORDER BY id').all().map(row=>({...row,payload:JSON.parse(row.payload_json)}));}

test('webhook event handling is local and debounced without GitLab access',()=>{let gitlabCalls=0;const enqueued=[];const service=new ReviewService({config:config({reviewDebounceMs:3000}),store:{enqueue:value=>(enqueued.push(value),1),cancelMergeRequest:()=>0},gitlab:new Proxy({},{get(){gitlabCalls++;return()=>{};}}),logger:{}});const result=service.handleEvent({projectAllowed:true,shouldReview:true,shouldCancel:false,kind:'merge_request',projectId:7,iid:9,action:'open',startSha:'s',headSha:'h',baseSha:'b',sourceBranch:'feat'},'wid');assert.equal(result.status,'queued');assert.equal(gitlabCalls,0);assert.equal(enqueued[0].dedupeKey,'event:wid');assert.equal(enqueued[0].delayMs,3000);});
test('retry classifier protects non-retryable safety failures',()=>{assert.equal(retryable({code:'EPROJECTPOLICY'}),false);assert.equal(retryable({code:'ETOKENBUDGET'}),false);assert.equal(retryable({code:'EGITLABHTTP',status:403}),false);assert.equal(retryable({code:'EGITLABHTTP',status:429}),true);assert.equal(retryable({code:'EGITLABHTTP',status:503}),true);});
test('draft detection accepts both GitLab fields',()=>{assert.equal(isDraft({draft:true}),true);assert.equal(isDraft({work_in_progress:true}),true);assert.equal(isDraft({draft:false,work_in_progress:false}),false);});
test('reconcile enqueue uses the same Reviewer assignment policy as webhooks',()=>{const enqueued=[],service=new ReviewService({config:config({triggerAssignment:{mode:'reviewer',userIds:[8]}}),store:{enqueue:value=>(enqueued.push(value),1)},gitlab:{},logger:{}}),base=mr();assert.equal(service.enqueueHydratedMr(7,{...base,assignees:[{id:8}],reviewers:[]}),null);assert.equal(service.enqueueHydratedMr(7,{...base,assignees:[],reviewers:[{id:8}]}),1);assert.equal(enqueued.length,1);});

test('review run and GitLab publication plan are persisted separately',async()=>{const db=tempStore();const currentMr=mr();const gitlab={getMergeRequest:async()=>currentMr,getProjectMember:async()=>({access_level:40}),resolveStatusPipeline:async()=>123,listMergeRequestDiffs:async()=>({complete:true,items:[{old_path:'a.js',new_path:'a.js',diff:'@@ -1 +1 @@ fn\n-old\n+new'}]}),validateMergeRequestDiffCoverage:async()=>({complete:true,reason:'complete'})};const service=new ReviewService({config:config(),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>policy(),contextFn:async()=>({blocks:[],bytes:0,complete:true}),runCodexFn:async()=>({version:'test',model:'model-x',usage:{inputTokens:100,outputTokens:20},parsed:{findings:[{severity:'high',category:'correctness',file:'a.js',side:'new',line:1,endLine:1,title:'Regression',description:'The new line regresses behavior.',suggestion:'Fix it.',confidence:0.95}]}})});try{const id=db.store.enqueue({projectId:7,mrIid:9,baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat',trigger:'open',dedupeKey:'snapshot:s:h',maxQueueDepth:10});await service.processJob(db.store.claimNext());assert.equal(db.store.getJob(id).status,'blocked');const run=db.store.db.prepare('SELECT * FROM review_runs WHERE job_id=?').get(id);assert.equal(run.input_tokens,100);assert.equal(run.output_tokens,20);assert.equal(run.codex_model,'model-x');const actions=outbox(db.store);assert.deepEqual(actions.map(a=>a.action_type),['status','summary','finding','status']);assert.equal(actions[0].payload.state,'running');assert.equal(actions.at(-1).payload.state,'failed');assert.equal(actions.at(-1).payload.pipelineId,123);}finally{db.close();}});

test('fork MR final status is planned for source project and pipeline',async()=>{const db=tempStore();const currentMr=mr({source_project_id:99,source_branch:'fork-feature'});const gitlab={getMergeRequest:async()=>currentMr,resolveStatusPipeline:async()=>456,listMergeRequestDiffs:async()=>({complete:true,items:[]}),validateMergeRequestDiffCoverage:async()=>({complete:true,reason:'complete'})};const service=new ReviewService({config:config(),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>policy(),contextFn:async()=>({blocks:[],complete:true}),runCodexFn:async()=>{throw new Error('should not run');}});try{db.store.enqueue({projectId:7,mrIid:9,baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'fork-feature',trigger:'open',dedupeKey:'snapshot:s:h',maxQueueDepth:10});await service.processJob(db.store.claimNext());const statuses=outbox(db.store).filter(a=>a.action_type==='status');assert.equal(statuses.length,2);for(const status of statuses){assert.equal(status.payload.statusProjectId,99);assert.equal(status.payload.pipelineId,456);assert.equal(status.payload.ref,'fork-feature');}}finally{db.close();}});

test('hard provider diff-limit mismatch persists incomplete review and failed final gate',async()=>{const db=tempStore();const currentMr=mr();const gitlab={getMergeRequest:async()=>currentMr,resolveStatusPipeline:async()=>12,listMergeRequestDiffs:async()=>({complete:true,items:[{old_path:'a.js',new_path:'a.js',diff:'@@ -1 +1 @@\n-a\n+b'}]}),validateMergeRequestDiffCoverage:async()=>({complete:false,reason:'diff_version_size_mismatch'})};const service=new ReviewService({config:config(),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>policy(),contextFn:async()=>({blocks:[],complete:true}),runCodexFn:async()=>({version:'test',usage:{},parsed:{findings:[]}})});try{const id=db.store.enqueue({projectId:7,mrIid:9,baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat',trigger:'open',dedupeKey:'snapshot:s:h',maxQueueDepth:10});await service.processJob(db.store.claimNext());assert.equal(db.store.getJob(id).status,'incomplete');const run=db.store.db.prepare('SELECT * FROM review_runs WHERE job_id=?').get(id);assert.equal(run.coverage_complete,0);assert.equal(outbox(db.store).at(-1).payload.state,'failed');}finally{db.close();}});

test('MR token budget blocks the next Core evidence chunk before Codex execution',async()=>{const db=tempStore();const currentMr=mr();const wideDiff=n=>`@@ -1 +1 @@ chunk-${n}\n-${'a'.repeat(1700)}\n+${'b'.repeat(1700)}`;const gitlab={getMergeRequest:async()=>currentMr,resolveStatusPipeline:async()=>1,listMergeRequestDiffs:async()=>({complete:true,items:[{old_path:'a.js',new_path:'a.js',diff:wideDiff(1)},{old_path:'b.js',new_path:'b.js',diff:wideDiff(2)}]}),validateMergeRequestDiffCoverage:async()=>({complete:true})};let calls=0;const service=new ReviewService({config:config({mrMaxTokenBudget:50,maxDiffBytes:4096,maxTotalDiffBytes:8192}),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>policy({maxDiffBytes:4096}),contextFn:async()=>({blocks:[],complete:true}),runCodexFn:async()=>{calls++;return{version:'test',usage:{inputTokens:60,outputTokens:1},parsed:{findings:[]}};}});try{const id=db.store.enqueue({projectId:7,mrIid:9,baseSha:'b',startSha:'s',headSha:'h',sourceBranch:'feat',trigger:'open',dedupeKey:'snapshot:s:h',maxQueueDepth:10});await service.processJob(db.store.claimNext());assert.equal(calls,0);assert.equal(db.store.getJob(id).status,'incomplete');const run=db.store.db.prepare('SELECT * FROM review_runs WHERE job_id=?').get(id);assert.equal(run.coverage_complete,0);assert.equal(run.input_tokens,0);}finally{db.close();}});

test('fresh review never carries historical model findings into a new run',async()=>{const db=tempStore();const previousHead='e'.repeat(40),currentHead='f'.repeat(40),currentMr=mr({diff_refs:{base_sha:BASE_SHA,start_sha:START_SHA,head_sha:currentHead}}),p=policy();const oldJob=db.store.enqueue({projectId:7,mrIid:9,baseSha:BASE_SHA,startSha:START_SHA,headSha:previousHead,sourceBranch:'feat',trigger:'open',dedupeKey:'event:old',maxQueueDepth:10}),oldReview={verdict:'needs_attention',summary:'old',coverageComplete:true,codexVersion:'test',codexModel:'model',chunkCount:1,rejectedFindingCount:0,truncatedFindingCount:0,usage:{inputTokens:100,outputTokens:10},findings:[{fingerprint:'carry-fp',severity:'medium',category:'correctness',file:'b.js',side:'new',line:1,endLine:1,title:'Historical issue',description:'Historical judgment only.',suggestion:'Fix it.',confidence:.95,anchorHash:'anchor-b'}]};db.store.saveRunWithOutbox(oldJob,oldReview,1,p,[]);db.store.finishJob(oldJob,'needs_attention');const fullItems=[{old_path:'a.js',new_path:'a.js',diff:'@@ -1 +1 @@\n-old-a\n+new-a'},{old_path:'b.js',new_path:'b.js',diff:'@@ -1 +1 @@\n-old-b\n+new-b'}],gitlab={getMergeRequest:async()=>currentMr,resolveStatusPipeline:async()=>1,listMergeRequestDiffs:async()=>({complete:true,items:fullItems}),validateMergeRequestDiffCoverage:async()=>({complete:true})};let calls=0,promptText='';const reviewService=new ReviewService({config:config(),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>p,contextFn:async()=>({blocks:[],bytes:0,complete:true}),runCodexFn:async prompt=>{calls++;promptText+=prompt;return{version:'test',model:'model',usage:{inputTokens:20,outputTokens:2},parsed:{findings:[]}};}});try{const id=db.store.enqueue({projectId:7,mrIid:9,baseSha:BASE_SHA,startSha:START_SHA,headSha:currentHead,sourceBranch:'feat',trigger:'update',dedupeKey:'event:new',maxQueueDepth:10});await reviewService.processJob(db.store.claimNext());assert.ok(calls>=1);assert.match(promptText,/a\.js/);assert.match(promptText,/b\.js/);const run=db.store.db.prepare('SELECT * FROM review_runs WHERE job_id=?').get(id);assert.equal(run.finding_count,0);assert.equal(db.store.db.prepare('SELECT COUNT(*) n FROM review_findings WHERE run_id=? AND fingerprint=?').get(run.id,'carry-fp').n,0);}finally{db.close();}});

test('review processing persists status-card create and final update actions',async()=>{const db=tempStore(),currentMr=mr({title:'Status card'}),route={name:'team',provider:'feishu_app',secretRef:'team',statusCard:true,projectIds:[7],events:['review.completed'],branches:[],severities:[],authors:[],reviewers:[],language:'zh-CN',diagnosticsUrl:''},gitlab={getMergeRequest:async()=>currentMr,resolveStatusPipeline:async()=>1,listMergeRequestDiffs:async()=>({complete:true,items:[]}),validateMergeRequestDiffCoverage:async()=>({complete:true})},service=new ReviewService({config:config({notificationEnabled:true,notificationRoutesResolved:[route],notificationEvents:['review.completed'],notificationTopFindings:3}),store:db.store,gitlab,logger:{info(){},warn(){},error(){}},getPolicyFn:async()=>policy(),contextFn:async()=>({blocks:[],complete:true}),runCodexFn:async()=>({version:'test',model:'model',usage:{},parsed:{findings:[]}})});try{const id=db.store.enqueue({projectId:7,mrIid:9,headSha:'h',sourceBranch:'feat',trigger:'open',dedupeKey:'status-e2e',maxQueueDepth:10});await service.processJob(db.store.claimNext());const rows=db.store.db.prepare('SELECT event_type,payload_json FROM notification_outbox ORDER BY id').all();assert.deepEqual(rows.map(row=>row.event_type),['review.started','review.completed']);assert.equal(JSON.parse(rows[1].payload_json)._statusCardOperation,'update');assert.equal(db.store.reviewStatusCard(id,'team').status,'pending');}finally{db.close();}});
