from pathlib import Path
import json

root=Path(__file__).resolve().parents[1]
def read(p): return (root/p).read_text()
def write(p,s): (root/p).write_text(s)
def rep(p,a,b):
    s=read(p)
    if a not in s: raise SystemExit(f'missing replacement in {p}: {a[:120]}')
    write(p,s.replace(a,b))

# Closed configuration schema.
rep('src/config.js',"const TOP_KEYS=new Set(['server','gitlab','webhook','review','codex','runner','publication','lifecycle','observability']);","const TOP_KEYS=new Set(['server','gitlab','webhook','review','codex','runner','publication','notifications','lifecycle','observability']);")
rep('src/config.js',"  publication:new Set(['concurrency','pollIntervalMs','maxAttempts']),","  publication:new Set(['concurrency','pollIntervalMs','maxAttempts']),\n  notifications:new Set(['enabled','concurrency','pollIntervalMs','maxAttempts','retryBaseDelayMs','retryMaxDelayMs','requestTimeoutMs','topFindings','events','routes']),")
marker='function validateSigningToken(value)'
insert="""const NOTIFICATION_EVENTS=Object.freeze(['review.completed','review.blocked','review.failed','service.degraded','service.recovered']);
function parseNotificationEvents(value,label='notifications.events'){if(value===undefined)return['review.blocked','review.failed','service.degraded'];if(!Array.isArray(value)||value.length>NOTIFICATION_EVENTS.length)throw configError(`${label} must be an array`);const out=[];for(const raw of value){const item=stringValue(raw,'',label,64);if(!NOTIFICATION_EVENTS.includes(item))throw configError(`${label} contains unsupported event: ${item}`);if(!out.includes(item))out.push(item);}return out;}
function parseNotificationRoutes(value){if(value===undefined)return[];if(!Array.isArray(value)||value.length>100)throw configError('notifications.routes must be an array');const names=new Set(),routes=[];for(const raw of value){const item=assertObject(raw,'notifications.routes[]');assertKeys(item,new Set(['name','provider','secretRef','projects','groups','events']),'notifications.routes[]');const name=stringValue(item.name,'','notifications.routes[].name',64);if(!/^[a-zA-Z0-9._-]+$/.test(name)||names.has(name))throw configError('notifications.routes[].name must be unique and use [a-zA-Z0-9._-]');names.add(name);const provider=enumValue(item.provider,'','notifications.routes[].provider',['feishu','wecom']),secretRef=stringValue(item.secretRef,'','notifications.routes[].secretRef',64);if(!/^[a-zA-Z0-9._-]+$/.test(secretRef))throw configError('notifications.routes[].secretRef is invalid');routes.push(Object.freeze({name,provider,secretRef,projects:Object.freeze(positiveIds(item.projects,'notifications.routes[].projects')),groups:Object.freeze(positiveIds(item.groups,'notifications.routes[].groups')),events:Object.freeze(parseNotificationEvents(item.events,'notifications.routes[].events'))}));}return routes;}
"""
s=read('src/config.js')
if insert not in s:
    if marker not in s: raise SystemExit('config marker missing')
    write('src/config.js',s.replace(marker,insert+marker))
rep('src/config.js',"c=structured.value.codex,runner=structured.value.runner,pub=structured.value.publication,life=structured.value.lifecycle,obs=structured.value.observability;","c=structured.value.codex,runner=structured.value.runner,pub=structured.value.publication,n=structured.value.notifications,life=structured.value.lifecycle,obs=structured.value.observability;")
rep('src/config.js',"  const runnerMode=enumValue(runner.mode,'inline','runner.mode',['inline','isolated']),runnerSocket=stringValue(runner.socket,defaultRunnerSocket(),'runner.socket',2048);","  const notificationEnabled=boolValue(n.enabled,false,'notifications.enabled'),notificationRoutes=parseNotificationRoutes(n.routes);if(notificationEnabled&&!notificationRoutes.length)throw configError('notifications.enabled requires at least one notifications.routes entry');\n  const runnerMode=enumValue(runner.mode,'inline','runner.mode',['inline','isolated']),runnerSocket=stringValue(runner.socket,defaultRunnerSocket(),'runner.socket',2048);")
rep('src/config.js',"    publisherConcurrency:intValue(pub.concurrency,2,'publication.concurrency',1,8),publisherPollIntervalMs:intValue(pub.pollIntervalMs,500,'publication.pollIntervalMs',50,60000),maxPublishAttempts:intValue(pub.maxAttempts,8,'publication.maxAttempts',1,50),","    publisherConcurrency:intValue(pub.concurrency,2,'publication.concurrency',1,8),publisherPollIntervalMs:intValue(pub.pollIntervalMs,500,'publication.pollIntervalMs',50,60000),maxPublishAttempts:intValue(pub.maxAttempts,8,'publication.maxAttempts',1,50),\n    notificationEnabled,notificationConcurrency:intValue(n.concurrency,2,'notifications.concurrency',1,8),notificationPollIntervalMs:intValue(n.pollIntervalMs,500,'notifications.pollIntervalMs',50,60000),maxNotificationAttempts:intValue(n.maxAttempts,8,'notifications.maxAttempts',1,50),notificationRetryBaseDelayMs:intValue(n.retryBaseDelayMs,5000,'notifications.retryBaseDelayMs',100,600000),notificationRetryMaxDelayMs:intValue(n.retryMaxDelayMs,1800000,'notifications.retryMaxDelayMs',1000,86400000),notificationRequestTimeoutMs:intValue(n.requestTimeoutMs,10000,'notifications.requestTimeoutMs',1000,120000),notificationTopFindings:intValue(n.topFindings,3,'notifications.topFindings',0,10),notificationEvents:Object.freeze(parseNotificationEvents(n.events)),notificationRoutes:Object.freeze(notificationRoutes),")
rep('src/config.js',"module.exports={loadConfig,loadStructuredConfig,validateSigningToken,normalizeBaseUrl,defaultConfigPath,defaultStateDir,defaultRunnerSocket,resolveXdgHome,SEVERITIES,parseGroups,positiveIds,configError};","module.exports={loadConfig,loadStructuredConfig,validateSigningToken,normalizeBaseUrl,defaultConfigPath,defaultStateDir,defaultRunnerSocket,resolveXdgHome,SEVERITIES,parseGroups,positiveIds,configError,parseNotificationEvents,parseNotificationRoutes,NOTIFICATION_EVENTS};")

# SQLite Schema 5 + independent durable notification outbox.
rep('src/db.js','const SCHEMA_VERSION = 4;','const SCHEMA_VERSION = 5;')
rep('src/db.js',"      CREATE TABLE IF NOT EXISTS publication_outbox(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER REFERENCES review_runs(id) ON DELETE CASCADE,project_id INTEGER NOT NULL,mr_iid INTEGER NOT NULL,action_type TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempt INTEGER NOT NULL DEFAULT 0,available_at TEXT NOT NULL,remote_id TEXT,error_code TEXT,created_at TEXT NOT NULL,started_at TEXT,finished_at TEXT);","      CREATE TABLE IF NOT EXISTS publication_outbox(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER REFERENCES review_runs(id) ON DELETE CASCADE,project_id INTEGER NOT NULL,mr_iid INTEGER NOT NULL,action_type TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempt INTEGER NOT NULL DEFAULT 0,available_at TEXT NOT NULL,remote_id TEXT,error_code TEXT,created_at TEXT NOT NULL,started_at TEXT,finished_at TEXT);\n      CREATE TABLE IF NOT EXISTS notification_outbox(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER REFERENCES review_runs(id) ON DELETE CASCADE,project_id INTEGER NOT NULL DEFAULT 0,mr_iid INTEGER NOT NULL DEFAULT 0,route_name TEXT NOT NULL,provider TEXT NOT NULL,secret_ref TEXT NOT NULL,event_type TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempt INTEGER NOT NULL DEFAULT 0,available_at TEXT NOT NULL,remote_id TEXT,error_code TEXT,created_at TEXT NOT NULL,started_at TEXT,finished_at TEXT);")
rep('src/db.js',"CREATE INDEX IF NOT EXISTS idx_outbox_run ON publication_outbox(run_id,id);PRAGMA user_version=${SCHEMA_VERSION};","CREATE INDEX IF NOT EXISTS idx_outbox_run ON publication_outbox(run_id,id);CREATE INDEX IF NOT EXISTS idx_notification_status_available ON notification_outbox(status,available_at,id);CREATE INDEX IF NOT EXISTS idx_notification_run ON notification_outbox(run_id,id);PRAGMA user_version=${SCHEMA_VERSION};")
rep('src/db.js',"  publicationDepth(){return Number(this.db.prepare(\"SELECT COUNT(*) count FROM publication_outbox WHERE status='pending'\").get().count);}","  publicationDepth(){return Number(this.db.prepare(\"SELECT COUNT(*) count FROM publication_outbox WHERE status='pending'\").get().count);}\n  notificationDepth(){return Number(this.db.prepare(\"SELECT COUNT(*) count FROM notification_outbox WHERE status='pending'\").get().count);}")
rep('src/db.js',"  recoverPublications(){return this.db.prepare(\"UPDATE publication_outbox SET status='pending',started_at=NULL,error_code='ESERVICERESTART',available_at=? WHERE status='publishing'\").run(new Date().toISOString()).changes;}","  recoverPublications(){return this.db.prepare(\"UPDATE publication_outbox SET status='pending',started_at=NULL,error_code='ESERVICERESTART',available_at=? WHERE status='publishing'\").run(new Date().toISOString()).changes;}\n  recoverNotifications(){return this.db.prepare(\"UPDATE notification_outbox SET status='pending',started_at=NULL,error_code='ESERVICERESTART',available_at=? WHERE status='delivering'\").run(new Date().toISOString()).changes;}")
rep('src/db.js',"  getJob(id){return this.db.prepare('SELECT * FROM review_jobs WHERE id=?').get(id)||null;}","  claimNotification(){return this.withTransaction(()=>{const now=new Date().toISOString(),row=this.db.prepare(`SELECT * FROM notification_outbox WHERE status='pending' AND available_at<=? ORDER BY id LIMIT 1`).get(now);if(!row)return null;const result=this.db.prepare(\"UPDATE notification_outbox SET status='delivering',started_at=?,attempt=attempt+1 WHERE id=? AND status='pending'\").run(now,row.id);if(result.changes!==1)return null;const value=this.db.prepare('SELECT * FROM notification_outbox WHERE id=?').get(row.id);value.payload=parseJson(value.payload_json);return value;});}\n  getJob(id){return this.db.prepare('SELECT * FROM review_jobs WHERE id=?').get(id)||null;}")
rep('src/db.js',"  saveRunWithOutbox(jobId,review,durationMs,policy,actions,receiptProjection=null){","  saveRunWithOutbox(jobId,review,durationMs,policy,actions,receiptProjection=null,notificationActions=[]){")
rep('src/db.js',"for(const action of actions||[])insertAction.run(runId,action.projectId,action.mrIid,action.type,action.dedupeKey,json(action.payload),now,now);return runId;});}","for(const action of actions||[])insertAction.run(runId,action.projectId,action.mrIid,action.type,action.dedupeKey,json(action.payload),now,now);const insertNotify=this.db.prepare(`INSERT OR IGNORE INTO notification_outbox(run_id,project_id,mr_iid,route_name,provider,secret_ref,event_type,dedupe_key,payload_json,status,available_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,?)`);for(const action of notificationActions||[])insertNotify.run(runId,action.payload?.projectId||0,action.payload?.mrIid||0,action.routeName,action.provider,action.secretRef,action.eventType,action.dedupeKey,json(action.payload),now,now);return runId;});}")
rep('src/db.js',"  finishPublication(id,remoteId=null){","  enqueueNotification({runId=null,routeName,provider,secretRef,eventType,dedupeKey,payload,delayMs=0}){const now=new Date().toISOString();try{const result=this.db.prepare(`INSERT INTO notification_outbox(run_id,project_id,mr_iid,route_name,provider,secret_ref,event_type,dedupe_key,payload_json,status,available_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,?)`).run(runId,payload?.projectId||0,payload?.mrIid||0,routeName,provider,secretRef,eventType,dedupeKey,json(payload),isoAfter(delayMs),now);return Number(result.lastInsertRowid);}catch(error){if(String(error.message).includes('UNIQUE constraint failed'))return null;throw error;}}\n  finishNotification(id,remoteId=null){this.db.prepare(\"UPDATE notification_outbox SET status='delivered',remote_id=?,error_code=NULL,finished_at=? WHERE id=?\").run(remoteId,new Date().toISOString(),id);}\n  retryNotification(id,errorCode,delayMs){this.db.prepare(\"UPDATE notification_outbox SET status='pending',error_code=?,started_at=NULL,available_at=? WHERE id=? AND status='delivering'\").run(errorCode,isoAfter(delayMs),id);}\n  failNotification(id,errorCode){this.db.prepare(\"UPDATE notification_outbox SET status='failed',error_code=?,finished_at=? WHERE id=?\").run(errorCode,new Date().toISOString(),id);}\n  finishPublication(id,remoteId=null){")
rep('src/db.js',"stats(){const jobs=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM review_jobs GROUP BY status').all().map(r=>[r.status,Number(r.count)])),publications=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM publication_outbox GROUP BY status').all().map(r=>[r.status,Number(r.count)])),usage=","stats(){const jobs=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM review_jobs GROUP BY status').all().map(r=>[r.status,Number(r.count)])),publications=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM publication_outbox GROUP BY status').all().map(r=>[r.status,Number(r.count)])),notifications=Object.fromEntries(this.db.prepare('SELECT status,COUNT(*) count FROM notification_outbox GROUP BY status').all().map(r=>[r.status,Number(r.count)])),usage=")
rep('src/db.js',"return{jobs,publications,webhookCount:","return{jobs,publications,notifications,webhookCount:")

# Review transaction and terminal failure notification.
rep('src/service.js',"const{classifyFindingLifecycle}=require('./finding-ledger');","const{classifyFindingLifecycle}=require('./finding-ledger');\nconst{eventForReview,eventForFailure,planNotificationActions}=require('./notification');")
rep('src/service.js',"const actions=this.planPublication(job,snapshot,review,policy),receiptProjection=createServiceReviewReceipt(snapshot,review,policy);this.store.saveRunWithOutbox(job.id,review,Date.now()-started,policy,actions,receiptProjection);","const durationMs=Date.now()-started,actions=this.planPublication(job,snapshot,review,policy),receiptProjection=createServiceReviewReceipt(snapshot,review,policy),notificationEvent=eventForReview({job,mr,snapshot,review,durationMs,topFindings:this.config.notificationTopFindings}),notificationActions=planNotificationActions(this.config,notificationEvent,`run:${job.id}:${snapshot.headSha}`);this.store.saveRunWithOutbox(job.id,review,durationMs,policy,actions,receiptProjection,notificationActions);")
rep('src/service.js',"this.store.finishJob(job.id,'failed',code);this.enqueueStatus(job,'failed',code==='EPROJECTPOLICY'?'Codex review policy is invalid':code==='ETOKENBUDGET'?'Codex review token budget exhausted':'Codex review service failed');","this.store.finishJob(job.id,'failed',code);this.enqueueStatus(job,'failed',code==='EPROJECTPOLICY'?'Codex review policy is invalid':code==='ETOKENBUDGET'?'Codex review token budget exhausted':'Codex review service failed');const failureEvent=eventForFailure(job,code);for(const action of planNotificationActions(this.config,failureEvent,`job:${job.id}`))this.store.enqueueNotification(action);")

# Runtime lifecycle + route refresh + service health alerts.
rep('src/index.js',"const{createHttpServer}=require('./http');const{probeCodexCapabilities}=require('./codex');","const{createHttpServer}=require('./http');const{probeCodexCapabilities}=require('./codex');const{Notifier,prepareNotificationRoutes,systemEvent,planNotificationActions}=require('./notification');")
rep('src/index.js',"recoveredPublications=store.recoverPublications();","recoveredPublications=store.recoverPublications(),recoveredNotifications=store.recoverNotifications();")
rep('src/index.js',"if(recoveredPublications)logger.info({event:'publications_recovered',count:recoveredPublications});","if(recoveredPublications)logger.info({event:'publications_recovered',count:recoveredPublications});if(recoveredNotifications)logger.info({event:'notifications_recovered',count:recoveredNotifications});")
rep('src/index.js',"config=applyProjectScope(config,scopeManager);logger.info({event:'project_scope_ready'","config=applyProjectScope(config,scopeManager);config=await prepareNotificationRoutes(gitlab,config);logger.info({event:'project_scope_ready'")
rep('src/index.js',"publisher=new Publisher({config,store,gitlab,logger});service.startWorkers();publisher.start();const server=createHttpServer({config,store,service,publisher,gitlab,telemetry,logger,startedAt});","publisher=new Publisher({config,store,gitlab,logger}),notifier=new Notifier({config,store,logger});service.startWorkers();publisher.start();notifier.start();const server=createHttpServer({config,store,service,publisher,notifier,gitlab,telemetry,logger,startedAt});")
rep('src/index.js',"publishers:config.publisherConcurrency,schemaVersion","publishers:config.publisherConcurrency,notifiers:config.notificationEnabled?config.notificationConcurrency:0,schemaVersion")
old="const periodic=()=>config.gitlabGroups.length?scopeManager.refresh().then(snapshot=>{logger.info({event:'project_scope_refreshed',mode:snapshot.mode,totalProjects:snapshot.totalProjects,discoveredProjects:snapshot.discoveredProjects});return reconcileOnce();}).catch(error=>logger.error({event:'project_scope_refresh_failed',code:error.code||'EPROJECTSCOPE'})):reconcileOnce();"
new="const enqueueSystem=event=>{for(const action of planNotificationActions(config,event,`system:${event.type}:${Date.now()}`))store.enqueueNotification(action);};let scopeWasHealthy=true;const periodic=()=>config.gitlabGroups.length?scopeManager.refresh().then(async snapshot=>{config=applyProjectScope(config,scopeManager);config=await prepareNotificationRoutes(gitlab,config);service.config=config;publisher.config=config;notifier.refreshConfig(config);if(!scopeWasHealthy){enqueueSystem(systemEvent('service.recovered',{component:'project_scope'}));scopeWasHealthy=true;}logger.info({event:'project_scope_refreshed',mode:snapshot.mode,totalProjects:snapshot.totalProjects,discoveredProjects:snapshot.discoveredProjects});return reconcileOnce();}).catch(error=>{if(scopeWasHealthy){enqueueSystem(systemEvent('service.degraded',{component:'project_scope',code:error.code||'EPROJECTSCOPE'}));scopeWasHealthy=false;}logger.error({event:'project_scope_refresh_failed',code:error.code||'EPROJECTSCOPE'});}):reconcileOnce();"
rep('src/index.js',old,new)
rep('src/index.js',"await service.stop();await publisher.stop();await telemetry.flush();","await service.stop();await publisher.stop();await notifier.stop();await telemetry.flush();")

# Readiness and metrics include notification delivery without making notification failures change review verdicts.
rep('src/http.js',"function renderMetrics(store,service,publisher,telemetry,startedAt)","function renderMetrics(store,service,publisher,notifier,telemetry,startedAt)")
rep('src/http.js',"'# TYPE codex_review_publishers gauge',`codex_review_publishers ${publisher?.workers?.length||0}`","'# TYPE codex_review_publishers gauge',`codex_review_publishers ${publisher?.workers?.length||0}`,'# TYPE codex_review_notifiers gauge',`codex_review_notifiers ${notifier?.workers?.length||0}`,'# TYPE codex_review_notification_queue_depth gauge',`codex_review_notification_queue_depth ${stats.notifications?.pending||0}`")
rep('src/http.js',"lines.push('# TYPE codex_review_webhook_events gauge'","lines.push('# TYPE codex_review_notifications gauge');for(const status of Object.keys(stats.notifications||{}).sort())if(/^[a-z_]+$/.test(status))lines.push(`codex_review_notifications{status=\"${status}\"} ${stats.notifications[status]}`);lines.push('# TYPE codex_review_webhook_events gauge'")
rep('src/http.js',"function createReadiness({config,store,service,publisher,gitlab})","function createReadiness({config,store,service,publisher,notifier,gitlab})")
rep('src/http.js',"publisherOk=!publisher?.stopping&&publisher?.workers?.length===config.publisherConcurrency,circuit=","publisherOk=!publisher?.stopping&&publisher?.workers?.length===config.publisherConcurrency,notifierOk=!config.notificationEnabled||(!notifier?.stopping&&notifier?.workers?.length===config.notificationConcurrency),circuit=")
rep('src/http.js',"ready=gitlabOk&&dbOk&&synchronousFull&&workerOk&&publisherOk&&circuit!=='open'&&scopeOk;","ready=gitlabOk&&dbOk&&synchronousFull&&workerOk&&publisherOk&&notifierOk&&circuit!=='open'&&scopeOk;")
rep('src/http.js',"expectedPublishers:config.publisherConcurrency,queueDepth:store.queueDepth(),publicationDepth:store.publicationDepth(),schemaVersion","expectedPublishers:config.publisherConcurrency,notifiers:notifier?.workers?.length||0,expectedNotifiers:config.notificationEnabled?config.notificationConcurrency:0,queueDepth:store.queueDepth(),publicationDepth:store.publicationDepth(),notificationDepth:store.notificationDepth(),schemaVersion")
rep('src/http.js',"function createHttpServer({config,store,service,publisher,gitlab,telemetry,logger=console,startedAt=Date.now()}){const readiness=createReadiness({config,store,service,publisher,gitlab});","function createHttpServer({config,store,service,publisher,notifier,gitlab,telemetry,logger=console,startedAt=Date.now()}){const readiness=createReadiness({config,store,service,publisher,notifier,gitlab});")
rep('src/http.js',"renderMetrics(store,service,publisher,telemetry,startedAt)","renderMetrics(store,service,publisher,notifier,telemetry,startedAt)")

# Product configuration examples.
notify={"enabled":False,"concurrency":2,"pollIntervalMs":500,"maxAttempts":8,"retryBaseDelayMs":5000,"retryMaxDelayMs":1800000,"requestTimeoutMs":10000,"topFindings":3,"events":["review.blocked","review.failed","service.degraded"],"routes":[{"name":"embedded-review","provider":"feishu","secretRef":"embedded","projects":[101,102],"groups":[],"events":["review.blocked","review.failed"]},{"name":"service-alerts","provider":"wecom","secretRef":"service_alerts","projects":[],"groups":[],"events":["service.degraded","service.recovered"]}]}
for p in ['config.example.json','deploy/systemd/config.example.json']:
    data=json.loads(read(p));data['notifications']=notify;write(p,json.dumps(data,ensure_ascii=False,indent=2)+'\n')
env=read('.env.example')
if 'CODEX_REVIEW_NOTIFY_EMBEDDED_WEBHOOK' not in env:
    env += "\n# Optional IM notification webhook secrets. secretRef maps to CODEX_REVIEW_NOTIFY_<REF>_WEBHOOK.\n# CODEX_REVIEW_NOTIFY_EMBEDDED_WEBHOOK=https://open.feishu.cn/open-apis/bot/v2/hook/...\n# CODEX_REVIEW_NOTIFY_SERVICE_ALERTS_WEBHOOK=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=...\n"
write('.env.example',env)

# Version/release packaging.
pkg=json.loads(read('package.json'));pkg['version']='4.1.0'
for item in ['deploy/docker/Dockerfile','deploy/docker/compose.yaml','deploy/docker/README.md','docs/NOTIFICATIONS.md','docs/NOTIFICATIONS.zh-CN.md','docs/GITLAB_SETUP.md','docs/GITLAB_SETUP.zh-CN.md']:
    if item not in pkg['files']: pkg['files'].append(item)
write('package.json',json.dumps(pkg,indent=2)+'\n')
lock=json.loads(read('package-lock.json'));lock['version']='4.1.0';lock['packages']['']['version']='4.1.0';write('package-lock.json',json.dumps(lock,indent=2)+'\n')
changelog=read('CHANGELOG.md')
if '## 4.1.0' not in changelog:
    changelog=changelog.replace('# Changelog\n','# Changelog\n\n## 4.1.0 - 2026-08-24\n\n- Add durable Feishu/Lark and WeCom notification routes with deterministic cards, retry/idempotency, dead-letter state and notification metrics.\n- Add rootless Docker/Compose deployment and dedicated GitLab/IM setup guides.\n')
write('CHANGELOG.md',changelog)

# Governance updates.
rep('scripts/verify-family-v4.js',"assert.equal(pkg.version, '4.0.4');","assert.equal(pkg.version, '4.1.0');")
rep('scripts/verify-family-v4.js','assert.equal(SCHEMA_VERSION, 4);','assert.equal(SCHEMA_VERSION, 5);')
rep('scripts/verify-family-v4.js',"'docs/ARCHITECTURE.md', 'docs/DEPLOYMENT.md', 'docs/DEPLOYMENT.zh-CN.md', 'src/*.js',","'docs/ARCHITECTURE.md', 'docs/DEPLOYMENT.md', 'docs/DEPLOYMENT.zh-CN.md', 'docs/NOTIFICATIONS.md', 'docs/NOTIFICATIONS.zh-CN.md', 'docs/GITLAB_SETUP.md', 'docs/GITLAB_SETUP.zh-CN.md',\n  'deploy/docker/Dockerfile', 'deploy/docker/compose.yaml', 'deploy/docker/README.md', 'src/*.js',")
rep('scripts/verify-family-v4.js','Codex Review Service 4.0.4 Family v4 deployment','Codex Review Service 4.1.0 Family v4 deployment')
rep('test/docs-governance.test.js',"const docs=['README.md','README.zh-CN.md','OPERATIONS.md','SECURITY.md','LONG_TERM_ASSET.md','docs/ARCHITECTURE.md'];","const docs=['README.md','README.zh-CN.md','OPERATIONS.md','SECURITY.md','LONG_TERM_ASSET.md','docs/ARCHITECTURE.md','docs/NOTIFICATIONS.md','docs/NOTIFICATIONS.zh-CN.md','docs/GITLAB_SETUP.md','docs/GITLAB_SETUP.zh-CN.md'];")
