#!/usr/bin/env node
'use strict';

const admin=require('./admin');
function output(value){process.stdout.write(`${JSON.stringify(value,null,2)}\n`);}
function usage(){throw admin.adminError('Usage: node src/admin-cli.js <status|jobs|publications|notifications|retry-publication ID|retry-notification ID|drain [SECONDS]|reconcile|db-check|backup PATH|backup-verify PATH|restore-check PATH|diagnostics>');}
async function main(argv=process.argv.slice(2)){const [command,arg]=argv;if(command==='reconcile')return output(await admin.reconcile());if(['backup-verify','restore-check'].includes(command)){if(!arg)usage();const result=admin.verifyDatabase(arg);output(result);if(!result.compatible)process.exitCode=2;return;}const store=admin.openStore();try{if(command==='status')return output(admin.status(store));if(command==='jobs')return output(admin.rows(store,'review_jobs',arg));if(command==='publications')return output(admin.rows(store,'publication_outbox',arg));if(command==='notifications')return output(admin.rows(store,'notification_outbox',arg));if(command==='retry-publication'){if(!arg)usage();return output(admin.retryTerminal(store,'publication',arg));}if(command==='retry-notification'){if(!arg)usage();return output(admin.retryTerminal(store,'notification',arg));}if(command==='drain')return output(await admin.drain(store,arg||60));if(command==='db-check')return output(admin.verifyDatabase(admin.requireDbPath()));if(command==='backup'){if(!arg)usage();return output(await admin.createBackup(store,arg));}if(command==='diagnostics')return output(admin.diagnostics(store));return usage();}finally{store.close();}}
if(require.main===module)main().catch(error=>{process.stderr.write(`${JSON.stringify({error:error.code||'EADMIN',message:error.message})}\n`);process.exitCode=1;});
module.exports={main};
