'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{spawn}=require('node:child_process');const{outputSchema}=require('./review');
const REQUIRED_TOP_FLAGS=Object.freeze(['--ask-for-approval']);
const REQUIRED_EXEC_FLAGS=Object.freeze(['--json','--ephemeral','--skip-git-repo-check','--ignore-user-config','--ignore-rules','--sandbox','--output-schema','--config']);
const SAFE_CONFIG_OVERRIDES=Object.freeze(['web_search="disabled"','features.shell_tool=false','features.unified_exec=false','features.shell_snapshot=false','features.apps=false','features.multi_agent=false','features.remote_plugin=false','features.hooks=false','features.goals=false','features.memories=false','features.skill_mcp_dependency_install=false']);
let capabilityCache=null;
function filteredEnv(config){const env={};for(const key of ['PATH','HOME','USERPROFILE','LANG','LC_ALL','TMPDIR','TEMP','TMP'])if(process.env[key])env[key]=process.env[key];if(config.codexHome)env.CODEX_HOME=config.codexHome;if(process.env.OPENAI_API_KEY)env.OPENAI_API_KEY=process.env.OPENAI_API_KEY;return env;}
function buildCodexArgs(schemaPath,model){const args=['--ask-for-approval','never','exec','--json','--ephemeral','--skip-git-repo-check','--ignore-user-config','--ignore-rules','--sandbox','read-only','--output-schema',schemaPath];for(const value of SAFE_CONFIG_OVERRIDES)args.push('--config',value);if(model)args.push('--model',model);args.push('-');return args;}
function killProcessTree(child,signalName){try{if(process.platform!=='win32'&&child.pid)process.kill(-child.pid,signalName);else child.kill(signalName);}catch{}}
function capture(command,args,config,timeoutMs=10000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{env:filteredEnv(config),stdio:['ignore','pipe','pipe']});let stdout='',stderr='',timedOut=false;const timer=setTimeout(()=>{timedOut=true;child.kill('SIGTERM');},timeoutMs);child.stdout.on('data',c=>stdout+=c);child.stderr.on('data',c=>stderr+=c);child.on('error',error=>{clearTimeout(timer);if(!error.code||error.code==='ENOENT')error.code='ECODEXCAPABILITY';reject(error);});child.on('close',code=>{clearTimeout(timer);if(timedOut){const error=new Error('Codex capability probe timed out');error.code='ECODEXCAPABILITY';return reject(error);}if(code===0)return resolve({stdout,stderr});const error=new Error(`Codex capability probe exited with code ${code}`);error.code='ECODEXCAPABILITY';error.stderr=stderr.slice(0,1000);reject(error);});});}
function checkVersionPolicy(version,config){if(config.codexVersionPolicy==='off'||!config.codexAllowedVersionPattern)return true;let matched=false;try{matched=new RegExp(config.codexAllowedVersionPattern).test(version);}catch{const error=new Error('CODEX_ALLOWED_VERSION_PATTERN is not a valid regular expression');error.code='ECODEXVERSION';throw error;}if(!matched&&config.codexVersionPolicy==='strict'){const error=new Error(`Codex version is outside the allowed production policy: ${version}`);error.code='ECODEXVERSION';throw error;}return matched;}
async function probeCodexCapabilities(config,force=false){const cacheKey=`${config.codexPath}\n${config.codexModel||''}\n${config.codexVersionPolicy||''}\n${config.codexAllowedVersionPattern||''}`;if(!force&&capabilityCache?.key===cacheKey)return capabilityCache.value;const[versionResult,top,exec]=await Promise.all([capture(config.codexPath,['--version'],config),capture(config.codexPath,['--help'],config),capture(config.codexPath,['exec','--help'],config)]);const topHelp=`${top.stdout}\n${top.stderr}`,execHelp=`${exec.stdout}\n${exec.stderr}`,missing=[...REQUIRED_TOP_FLAGS.filter(f=>!topHelp.includes(f)).map(f=>`top-level ${f}`),...REQUIRED_EXEC_FLAGS.filter(f=>!execHelp.includes(f)).map(f=>`exec ${f}`)];if(config.codexModel&&!`${topHelp}\n${execHelp}`.includes('--model'))missing.push('--model');if(missing.length){const error=new Error(`Codex CLI does not expose required capabilities: ${missing.join(', ')}`);error.code='ECODEXVERSION';error.missingFlags=missing;throw error;}const version=String(versionResult.stdout||versionResult.stderr).trim()||'unknown',versionMatched=checkVersionPolicy(version,config);const value=Object.freeze({version,versionMatched});capabilityCache={key:cacheKey,value};return value;}
function usageShape(value={}){return{inputTokens:Number(value.input_tokens||0),cachedInputTokens:Number(value.cached_input_tokens||0),cacheWriteInputTokens:Number(value.cache_write_input_tokens||0),outputTokens:Number(value.output_tokens||0),reasoningOutputTokens:Number(value.reasoning_output_tokens||0)};}
function parseJsonlEvents(stdout){let lastAgentMessage='';const errors=[];let usage=usageShape();for(const line of String(stdout||'').split(/\r?\n/).filter(Boolean)){let event;try{event=JSON.parse(line);}catch{throw Object.assign(new Error('Codex --json returned invalid JSONL'),{code:'ECODEXOUTPUT'});}if(event?.type==='item.completed'&&event?.item?.type==='agent_message'&&typeof event.item.text==='string')lastAgentMessage=event.item.text;if(event?.type==='turn.completed'&&event.usage)usage=usageShape(event.usage);if(event?.type==='error')errors.push(event.message||event.error?.message||'Codex error');if(event?.type==='turn.failed')errors.push(event.error?.message||event.message||'Codex turn failed');}if(!lastAgentMessage&&errors.length)throw Object.assign(new Error(errors.join('; ')),{code:'ECODEXTURN'});if(!lastAgentMessage)throw Object.assign(new Error('Codex JSONL did not contain a final agent_message'),{code:'ECODEXOUTPUT'});return{message:lastAgentMessage.trim(),usage};}
function parseJsonl(stdout){return parseJsonlEvents(stdout).message;}
function compatibilityError(stderr){const text=String(stderr||'').toLowerCase();return['unexpected argument','unknown argument','unrecognized option','unknown option','unknown feature','unknown config key','unrecognized config key'].some(f=>text.includes(f));}
function abortReason(signal){return signal?.reason instanceof Error?signal.reason:Object.assign(new Error('Review aborted'),{code:'EABORTED'});}
async function runCodex(prompt,config,signal,maxFindings=config.maxFindings){const capability=await probeCodexCapabilities(config);return new Promise((resolve,reject)=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'codex-review-service-')),schemaPath=path.join(temp,'review-schema.json');fs.writeFileSync(schemaPath,JSON.stringify(outputSchema(maxFindings)),{mode:0o600});const child=spawn(config.codexPath,buildCodexArgs(schemaPath,config.codexModel),{cwd:temp,env:filteredEnv(config),stdio:['pipe','pipe','pipe'],detached:process.platform!=='win32'});let stdout='',stderr='',settled=false,limitExceeded=false,timedOut=false,killTimer=null;const cleanup=()=>{if(killTimer)clearTimeout(killTimer);try{fs.rmSync(temp,{recursive:true,force:true});}catch{}};const stop=()=>{if(settled)return;killProcessTree(child,'SIGTERM');killTimer??=setTimeout(()=>killProcessTree(child,'SIGKILL'),5000);};const timer=setTimeout(()=>{timedOut=true;stop();},config.reviewTimeoutSeconds*1000),onAbort=()=>stop();signal?.addEventListener('abort',onAbort,{once:true});child.stdout.on('data',c=>{stdout+=c;if(Buffer.byteLength(stdout,'utf8')>6*1024*1024){limitExceeded=true;stop();}});child.stderr.on('data',c=>{stderr+=c;if(Buffer.byteLength(stderr,'utf8')>1024*1024){limitExceeded=true;stop();}});child.stdin.on('error',e=>{if(e.code!=='EPIPE'&&!settled)stop();});child.on('error',error=>{settled=true;clearTimeout(timer);signal?.removeEventListener('abort',onAbort);cleanup();if(error.code==='ENOENT')error.code='ECODEXNOTFOUND';reject(error);});child.on('close',code=>{settled=true;clearTimeout(timer);signal?.removeEventListener('abort',onAbort);try{if(signal?.aborted)return reject(abortReason(signal));if(timedOut)return reject(Object.assign(new Error('Codex review timed out'),{code:'ECODEXTIMEOUT'}));if(limitExceeded)return reject(Object.assign(new Error('Codex output exceeded safety limit'),{code:'ECODEXOUTPUT'}));if(code!==0){const error=new Error(`Codex exited with code ${code}`);error.code=compatibilityError(stderr)?'ECODEXVERSION':'ECODEX';error.stderr=stderr.slice(0,1000);return reject(error);}const events=parseJsonlEvents(stdout);let parsed;try{parsed=JSON.parse(events.message);}catch{throw Object.assign(new Error('Codex final agent_message is not valid JSON'),{code:'ECODEXOUTPUT'});}resolve({parsed,version:capability.version,versionMatched:capability.versionMatched,usage:events.usage,model:config.codexModel||''});}catch(error){reject(error);}finally{cleanup();}});child.stdin.end(prompt);});}
module.exports={runCodex,filteredEnv,parseJsonl,parseJsonlEvents,buildCodexArgs,probeCodexCapabilities,SAFE_CONFIG_OVERRIDES,REQUIRED_TOP_FLAGS,REQUIRED_EXEC_FLAGS,killProcessTree,checkVersionPolicy,usageShape};
