'use strict';

const fs=require('node:fs');
const path=require('node:path');
const SEVERITIES=Object.freeze(['critical','high','medium','low','info']);
const TOP_KEYS=new Set(['server','gitlab','webhook','review','codex','runner','publication','lifecycle','observability']);
const SECTION_KEYS={
  server:new Set(['host','port','dataDir']),
  gitlab:new Set(['baseUrl','projects','groups','requestTimeoutMs','maxPages','statusRetries','requestsPerSecond','circuitFailureThreshold','circuitResetMs','statusName','statusTargetUrl','bindStatusPipeline','botUsername','manualMinAccessLevel']),
  webhook:new Set(['expectedInstance','requireInstanceHeader','maxSkewSeconds','maxBodyBytes']),
  review:new Set(['language','timeoutSeconds','jobTimeoutSeconds','maxJobAttempts','retryBaseDelayMs','retryMaxDelayMs','maxDiffBytes','maxReviewChunks','maxFindings','maxPublishedFindings','minConfidence','blockingSeverity','contextEnabled','maxContextBytes','maxContextFiles','contextLines','blockUnreviewableFiles','skipGeneratedFiles','reviewDraftMergeRequests','debounceMs','mrMaxTokenBudget','projectDailyTokenBudget','concurrency','pollIntervalMs','maxQueueDepth','projectPolicyEnabled','projectPolicyMaxBytes','autoResolveObsolete','triggerOnOpen','triggerOnPush','triggerOnReopen']),
  codex:new Set(['path','model','home','versionPolicy','allowedVersionPattern']),
  runner:new Set(['mode','socket']),
  publication:new Set(['concurrency','pollIntervalMs','maxAttempts']),
  lifecycle:new Set(['dataRetentionDays','webhookRetentionDays','maintenanceIntervalMs','reconcileIntervalMs','readinessCacheMs']),
  observability:new Set(['otelEndpoint','serviceName','exportTimeoutMs'])
};
function configError(message){const error=new Error(message);error.code='ECONFIGFILE';return error;}
function assertObject(value,label){if(value===undefined)return{};if(!value||typeof value!=='object'||Array.isArray(value))throw configError(`${label} must be an object`);return value;}
function assertKeys(value,allowed,label){for(const key of Object.keys(value))if(!allowed.has(key))throw configError(`${label} contains unsupported field: ${key}`);}
function stringValue(value,fallback,label,maxLength=4096){const v=value===undefined?fallback:value;if(typeof v!=='string')throw configError(`${label} must be a string`);const out=v.trim();if(out.length>maxLength||/[\r\n\0]/.test(out))throw configError(`${label} is invalid`);return out;}
function intValue(value,fallback,label,min,max){const v=value===undefined?fallback:value;if(!Number.isInteger(v)||v<min||v>max)throw configError(`${label} must be an integer between ${min} and ${max}`);return v;}
function numValue(value,fallback,label,min,max){const v=value===undefined?fallback:value;if(!Number.isFinite(v)||v<min||v>max)throw configError(`${label} must be a number between ${min} and ${max}`);return v;}
function boolValue(value,fallback,label){const v=value===undefined?fallback:value;if(typeof v!=='boolean')throw configError(`${label} must be boolean`);return v;}
function enumValue(value,fallback,label,allowed){const v=stringValue(value,fallback,label,128);if(!allowed.includes(v))throw configError(`${label} must be one of: ${allowed.join(', ')}`);return v;}
function normalizeBaseUrl(value,label){let url;try{url=new URL(value);}catch{throw configError(`${label} must be a valid URL`);}if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw configError(`${label} must be an http(s) base URL without credentials, query, or fragment`);return url.toString().replace(/\/$/,'');}
function positiveIds(value,label){if(value===undefined)return[];if(!Array.isArray(value)||value.length>10000)throw configError(`${label} must be an array`);const ids=[];for(const item of value){if(!Number.isInteger(item)||item<=0)throw configError(`${label} contains an invalid numeric ID`);ids.push(item);}return[...new Set(ids)];}
function parseGroups(value){if(value===undefined)return[];if(!Array.isArray(value)||value.length>1000)throw configError('gitlab.groups must be an array');const seen=new Set(),groups=[];for(const raw of value){const item=assertObject(raw,'gitlab.groups[]');assertKeys(item,new Set(['id','includeSubgroups']),'gitlab.groups[]');if(!Number.isInteger(item.id)||item.id<=0)throw configError('gitlab.groups[].id must be a positive integer');const includeSubgroups=boolValue(item.includeSubgroups,false,'gitlab.groups[].includeSubgroups'),key=`${item.id}:${includeSubgroups}`;if(!seen.has(key)){seen.add(key);groups.push({id:item.id,includeSubgroups});}}return groups;}
function validateSigningToken(value){const token=String(value||'').trim();if(!token)throw new Error('GITLAB_WEBHOOK_SIGNING_TOKEN is required');if(!token.startsWith('whsec_'))throw new Error('GITLAB_WEBHOOK_SIGNING_TOKEN must start with whsec_');const encoded=token.slice(6),key=Buffer.from(encoded,'base64');if(key.length!==32||encoded.replace(/=+$/,'')!==key.toString('base64').replace(/=+$/,''))throw new Error('GITLAB_WEBHOOK_SIGNING_TOKEN must contain valid base64 for exactly 32 bytes');return token;}
function requiredSecret(name){const value=String(process.env[name]||'').trim();if(!value)throw new Error(`${name} is required`);if(/[\r\n\0]/.test(value))throw new Error(`${name} is invalid`);return value;}
function loadStructuredConfig(filePath=process.env.CODEX_REVIEW_CONFIG_FILE||'/etc/codex-review/config.json'){
  if(!fs.existsSync(filePath))throw configError(`Configuration file does not exist: ${filePath}`);
  let root;try{root=JSON.parse(fs.readFileSync(filePath,'utf8'));}catch(cause){const error=configError(`Configuration file is not valid JSON: ${filePath}`);error.cause=cause;throw error;}
  root=assertObject(root,'config');assertKeys(root,TOP_KEYS,'config');
  const sections={};for(const name of Object.keys(SECTION_KEYS)){sections[name]=assertObject(root[name],name);assertKeys(sections[name],SECTION_KEYS[name],name);}
  return{path:filePath,value:sections};
}
function loadConfig(){
  const structured=loadStructuredConfig(),s=structured.value.server,g=structured.value.gitlab,w=structured.value.webhook,r=structured.value.review,c=structured.value.codex,runner=structured.value.runner,pub=structured.value.publication,life=structured.value.lifecycle,obs=structured.value.observability;
  const gitlabBaseUrl=normalizeBaseUrl(stringValue(g.baseUrl,'','gitlab.baseUrl'),'gitlab.baseUrl'),projects=new Set(positiveIds(g.projects,'gitlab.projects')),groups=parseGroups(g.groups);if(!projects.size&&!groups.length)throw configError('Configure at least one gitlab.projects or gitlab.groups entry');
  const runnerMode=enumValue(runner.mode,'inline','runner.mode',['inline','isolated']),runnerSocket=stringValue(runner.socket,'/run/codex-review-runner/runner.sock','runner.socket',2048);if(runnerMode==='isolated'&&!runnerSocket.startsWith('/'))throw configError('runner.socket must be an absolute Unix socket path');
  const dataDir=path.resolve(stringValue(s.dataDir,'/var/lib/codex-review','server.dataDir',2048)),language=enumValue(r.language,'zh-CN','review.language',['zh-CN','en']),blockingSeverity=enumValue(r.blockingSeverity,'high','review.blockingSeverity',SEVERITIES);
  return Object.freeze({
    configFilePath:structured.path,gitlabProjectAllowlist:projects,gitlabGroups:Object.freeze(groups.map(Object.freeze)),
    host:stringValue(s.host,'127.0.0.1','server.host',255)||'127.0.0.1',port:intValue(s.port,8787,'server.port',1,65535),dataDir,dbPath:path.join(dataDir,'review-service.sqlite'),
    gitlabBaseUrl,gitlabApiUrl:`${gitlabBaseUrl}/api/v4`,gitlabToken:requiredSecret('GITLAB_API_TOKEN'),
    gitlabRequestTimeoutMs:intValue(g.requestTimeoutMs,30000,'gitlab.requestTimeoutMs',1000,120000),gitlabMaxPages:intValue(g.maxPages,200,'gitlab.maxPages',1,1000),gitlabStatusRetries:intValue(g.statusRetries,5,'gitlab.statusRetries',1,10),gitlabRequestsPerSecond:intValue(g.requestsPerSecond,20,'gitlab.requestsPerSecond',1,200),gitlabCircuitFailureThreshold:intValue(g.circuitFailureThreshold,8,'gitlab.circuitFailureThreshold',2,100),gitlabCircuitResetMs:intValue(g.circuitResetMs,30000,'gitlab.circuitResetMs',1000,600000),
    statusName:stringValue(g.statusName,'codex-review','gitlab.statusName',255)||'codex-review',statusTargetUrl:stringValue(g.statusTargetUrl,'','gitlab.statusTargetUrl',2048),bindStatusPipeline:boolValue(g.bindStatusPipeline,true,'gitlab.bindStatusPipeline'),botUsername:stringValue(g.botUsername,'','gitlab.botUsername',255),manualMinAccessLevel:intValue(g.manualMinAccessLevel,30,'gitlab.manualMinAccessLevel',0,50),
    webhookSigningToken:validateSigningToken(process.env.GITLAB_WEBHOOK_SIGNING_TOKEN),webhookExpectedInstance:normalizeBaseUrl(stringValue(w.expectedInstance,gitlabBaseUrl,'webhook.expectedInstance',2048)||gitlabBaseUrl,'webhook.expectedInstance'),requireInstanceHeader:boolValue(w.requireInstanceHeader,true,'webhook.requireInstanceHeader'),webhookMaxSkewSeconds:intValue(w.maxSkewSeconds,300,'webhook.maxSkewSeconds',30,3600),webhookMaxBodyBytes:intValue(w.maxBodyBytes,1024*1024,'webhook.maxBodyBytes',4096,10*1024*1024),
    language,runnerMode,codexRunnerSocket:runnerMode==='isolated'?runnerSocket:'',codexPath:stringValue(c.path,'codex','codex.path',1024)||'codex',codexModel:stringValue(c.model,'','codex.model',128),codexHome:stringValue(c.home,'','codex.home',2048),codexVersionPolicy:enumValue(c.versionPolicy,'warn','codex.versionPolicy',['off','warn','strict']),codexAllowedVersionPattern:stringValue(c.allowedVersionPattern,'','codex.allowedVersionPattern',256),
    reviewTimeoutSeconds:intValue(r.timeoutSeconds,180,'review.timeoutSeconds',30,900),jobTimeoutSeconds:intValue(r.jobTimeoutSeconds,900,'review.jobTimeoutSeconds',60,7200),maxJobAttempts:intValue(r.maxJobAttempts,3,'review.maxJobAttempts',1,10),retryBaseDelayMs:intValue(r.retryBaseDelayMs,1000,'review.retryBaseDelayMs',100,60000),retryMaxDelayMs:intValue(r.retryMaxDelayMs,60000,'review.retryMaxDelayMs',1000,15*60*1000),maxDiffBytes:intValue(r.maxDiffBytes,1024*1024,'review.maxDiffBytes',4096,4*1024*1024),maxReviewChunks:intValue(r.maxReviewChunks,8,'review.maxReviewChunks',1,32),maxFindings:intValue(r.maxFindings,40,'review.maxFindings',1,100),maxPublishedFindings:intValue(r.maxPublishedFindings,40,'review.maxPublishedFindings',1,100),minConfidence:numValue(r.minConfidence,0.7,'review.minConfidence',0,1),blockingSeverity,
    contextEnabled:boolValue(r.contextEnabled,true,'review.contextEnabled'),maxContextBytes:intValue(r.maxContextBytes,256*1024,'review.maxContextBytes',0,2*1024*1024),maxContextFiles:intValue(r.maxContextFiles,12,'review.maxContextFiles',0,100),contextLines:intValue(r.contextLines,20,'review.contextLines',0,200),blockUnreviewableFiles:boolValue(r.blockUnreviewableFiles,false,'review.blockUnreviewableFiles'),skipGeneratedFiles:boolValue(r.skipGeneratedFiles,true,'review.skipGeneratedFiles'),reviewDraftMergeRequests:boolValue(r.reviewDraftMergeRequests,false,'review.reviewDraftMergeRequests'),reviewDebounceMs:intValue(r.debounceMs,3000,'review.debounceMs',0,60000),mrMaxTokenBudget:intValue(r.mrMaxTokenBudget,0,'review.mrMaxTokenBudget',0,1000000000),projectDailyTokenBudget:intValue(r.projectDailyTokenBudget,0,'review.projectDailyTokenBudget',0,1000000000),
    workerConcurrency:intValue(r.concurrency,2,'review.concurrency',1,8),pollIntervalMs:intValue(r.pollIntervalMs,1000,'review.pollIntervalMs',100,60000),maxQueueDepth:intValue(r.maxQueueDepth,200,'review.maxQueueDepth',1,10000),projectPolicyEnabled:boolValue(r.projectPolicyEnabled,true,'review.projectPolicyEnabled'),projectPolicyMaxBytes:intValue(r.projectPolicyMaxBytes,64*1024,'review.projectPolicyMaxBytes',1024,1024*1024),autoResolveObsolete:boolValue(r.autoResolveObsolete,true,'review.autoResolveObsolete'),triggerOnOpen:boolValue(r.triggerOnOpen,true,'review.triggerOnOpen'),triggerOnPush:boolValue(r.triggerOnPush,true,'review.triggerOnPush'),triggerOnReopen:boolValue(r.triggerOnReopen,true,'review.triggerOnReopen'),
    publisherConcurrency:intValue(pub.concurrency,2,'publication.concurrency',1,8),publisherPollIntervalMs:intValue(pub.pollIntervalMs,500,'publication.pollIntervalMs',50,60000),maxPublishAttempts:intValue(pub.maxAttempts,8,'publication.maxAttempts',1,50),
    dataRetentionDays:intValue(life.dataRetentionDays,30,'lifecycle.dataRetentionDays',1,3650),webhookRetentionDays:intValue(life.webhookRetentionDays,7,'lifecycle.webhookRetentionDays',1,3650),maintenanceIntervalMs:intValue(life.maintenanceIntervalMs,3600000,'lifecycle.maintenanceIntervalMs',60000,86400000),reconcileIntervalMs:intValue(life.reconcileIntervalMs,300000,'lifecycle.reconcileIntervalMs',60000,86400000),readinessCacheMs:intValue(life.readinessCacheMs,5000,'lifecycle.readinessCacheMs',500,60000),
    otelEndpoint:stringValue(obs.otelEndpoint,'','observability.otelEndpoint',2048),otelServiceName:stringValue(obs.serviceName,'codex-review-service','observability.serviceName',255)||'codex-review-service',otelExportTimeoutMs:intValue(obs.exportTimeoutMs,3000,'observability.exportTimeoutMs',100,60000)
  });
}
module.exports={loadConfig,loadStructuredConfig,validateSigningToken,normalizeBaseUrl,SEVERITIES,parseGroups,positiveIds,configError};
