'use strict';

const SEVERITY_ORDER=Object.freeze({critical:5,high:4,medium:3,low:2,info:1});
const HIGH_RISK_PATHS=[/(^|\/)(auth|security|crypto|secrets?|permissions?|iam)(\/|\.|$)/i,/(^|\/)(migrations?|schema)(\/|\.|$)/i,/\.(c|cc|cpp|h|hpp|rs)$/i];
const MEDIUM_RISK_PATHS=[/(^|\/)(api|db|database|storage|network|http|runner|worker|scheduler)(\/|\.|$)/i,/Dockerfile$/i,/\.ya?ml$/i];
const HIGH_RISK_TEXT=/\b(mutex|semaphore|atomic|lock|race|deadlock|use-after-free|double[- ]free|malloc|calloc|realloc|free\s*\(|password|secret|token|signature|authorization|authentication|sql|transaction|rollback|exec\s*\(|spawn\s*\(|eval\s*\(|deserialize|prototype pollution)\b/i;
const MEDIUM_RISK_TEXT=/\b(timeout|retry|cache|stream|socket|file descriptor|promise|async|await|thread|process|memory|resource|permission|migration|schema|api|backward compat|breaking)\b/i;

function byteLength(value){return Buffer.byteLength(String(value||''),'utf8');}
function estimateTextTokens(value,bytesPerToken=3){return Math.max(1,Math.ceil(byteLength(value)/Math.max(1,bytesPerToken)));}
function estimateChunkTokens(prompt,maxFindings=1){const input=estimateTextTokens(prompt);const output=Math.max(96,96+Math.max(1,Number(maxFindings)||1)*180);return Object.freeze({input,output,total:input+output});}

function scoreChunkRisk(chunk){let score=0;const paths=(chunk?.files||[]).map(file=>String(file.path||''));for(const path of paths){if(HIGH_RISK_PATHS.some(pattern=>pattern.test(path)))score+=5;else if(MEDIUM_RISK_PATHS.some(pattern=>pattern.test(path)))score+=2;if(/(^|\/)(test|tests|fixtures?|docs?)(\/|\.|$)/i.test(path))score-=1;}const text=String(chunk?.diffText||'');if(HIGH_RISK_TEXT.test(text))score+=5;if(MEDIUM_RISK_TEXT.test(text))score+=2;const changedLines=(text.match(/^[+-](?![+-])/gm)||[]).length;if(changedLines>300)score+=2;else if(changedLines>100)score+=1;return Math.max(0,score);}

function adaptiveContextConfig(config,policy,chunk){const enabled=Boolean(config.contextEnabled)&&Number(policy.maxContextBytes||0)>0;if(!enabled)return{...config,...policy,contextEnabled:false,maxContextBytes:0,maxContextFiles:0,contextLines:0,riskScore:scoreChunkRisk(chunk)};const riskScore=scoreChunkRisk(chunk);if(config.adaptiveContextEnabled===false)return{...config,...policy,riskScore};const factor=riskScore>=8?1:riskScore>=4?0.5:0.25;const bounded=(value,min=0)=>value<=0?0:Math.max(min,Math.floor(value*factor));return{...config,...policy,riskScore,maxContextBytes:bounded(Number(policy.maxContextBytes||0),16*1024),maxContextFiles:bounded(Number(policy.maxContextFiles||0),1),contextLines:bounded(Number(policy.contextLines||0),4)};}

function selectModel(config,riskScore){const fast=String(config.codexFastModel||'').trim();if(fast&&riskScore<4)return fast;return String(config.codexModel||'').trim();}

function selectChunksWithinByteBudget(chunks,maxBytes){const values=Array.isArray(chunks)?chunks:[];const budget=Number(maxBytes)||0;if(!budget)return{chunks:values,omitted:[],bytes:values.reduce((sum,item)=>sum+Number(item.bytes||0),0),complete:true};const total=values.reduce((sum,item)=>sum+Number(item.bytes||0),0);if(total<=budget)return{chunks:values,omitted:[],bytes:total,complete:true};const ranked=values.map(chunk=>({chunk,risk:scoreChunkRisk(chunk)})).sort((a,b)=>b.risk-a.risk||a.chunk.index-b.chunk.index);const selected=[],omitted=[];let bytes=0;for(const item of ranked){const size=Number(item.chunk.bytes||0);if(size<=budget-bytes){selected.push(item.chunk);bytes+=size;}else omitted.push(item.chunk);}selected.sort((a,b)=>a.index-b.index);omitted.sort((a,b)=>a.index-b.index);return{chunks:selected,omitted,bytes,complete:omitted.length===0};}

function normalizePath(entry){return String(entry?.new_path||entry?.old_path||entry?.path||'').replace(/\\/g,'/');}
function changedPathsFromCompare(compare){const paths=new Set();for(const entry of compare?.items||compare?.diffs||[]){const oldPath=String(entry.old_path||'').replace(/\\/g,'/'),newPath=String(entry.new_path||'').replace(/\\/g,'/');if(oldPath)paths.add(oldPath);if(newPath)paths.add(newPath);}return paths;}
function subsetDiffResult(diffResult,paths){const wanted=paths instanceof Set?paths:new Set(paths||[]);return{complete:true,profile:diffResult?.profile||'incremental',items:(diffResult?.items||[]).filter(entry=>wanted.has(normalizePath(entry))||wanted.has(String(entry.old_path||'').replace(/\\/g,'/')))};}
function dbFindingToReview(row){return{fingerprint:String(row.fingerprint||''),severity:String(row.severity||'info'),category:String(row.category||'other'),file:String(row.file||''),side:String(row.side||'new'),line:Number(row.line||1),endLine:Number(row.end_line||row.line||1),title:String(row.title||''),description:String(row.description||''),suggestion:String(row.suggestion||''),confidence:Number(row.confidence||0),anchorHash:String(row.anchor_hash||''),discussionId:row.discussion_id||null};}
function carryForwardFindings(rows,changedPaths){const changed=changedPaths instanceof Set?changedPaths:new Set(changedPaths||[]);return(rows||[]).filter(row=>!changed.has(String(row.file||'').replace(/\\/g,'/'))).map(dbFindingToReview);}
function passesThreshold(severity,threshold){return(SEVERITY_ORDER[severity]||0)>=(SEVERITY_ORDER[threshold]||0);}
function mergeCarriedFindings(review,carried,policy){if(!carried?.length)return review;const deduped=new Map();for(const finding of[...(review.allFindings||review.findings||[]),...carried]){const previous=deduped.get(finding.fingerprint);if(!previous||Number(finding.confidence||0)>Number(previous.confidence||0))deduped.set(finding.fingerprint,finding);}const uncapped=[...deduped.values()].sort((a,b)=>(SEVERITY_ORDER[b.severity]||0)-(SEVERITY_ORDER[a.severity]||0)||Number(b.confidence||0)-Number(a.confidence||0)||String(a.file).localeCompare(String(b.file)));const blocking=uncapped.some(f=>passesThreshold(f.severity,policy.blockingSeverity)),truncatedFindingCount=Math.max(0,uncapped.length-policy.maxFindings),allFindings=uncapped.slice(0,policy.maxFindings),findings=allFindings.filter(f=>passesThreshold(f.severity,policy.severityThreshold));return{...review,allFindings,findings,truncatedFindingCount:Math.max(Number(review.truncatedFindingCount||0),truncatedFindingCount),verdict:review.coverageComplete===false?'incomplete':blocking?'block':findings.length?'needs_attention':'pass',carriedFindingCount:carried.length};}

class TokenBudgetLedger{
  constructor(){this.byKey=new Map();this.byProject=new Map();}
  reservedForProject(projectId){return Number(this.byProject.get(Number(projectId))||0);}
  reservedForKey(key){return Number(this.byKey.get(String(key))?.tokens||0);}
  reserve(key,projectId,tokens,{budget=0,committed=0}={}){const amount=Math.max(0,Math.ceil(Number(tokens)||0));if(!amount)return this.reservedForKey(key);const id=String(key),project=Number(projectId),current=this.byKey.get(id)||{projectId:project,tokens:0};if(current.projectId!==project)throw new Error('Token reservation project mismatch');const projectReserved=this.reservedForProject(project);if(budget&&Number(committed||0)+projectReserved+amount>budget){const error=new Error('Project daily Codex token budget would be exceeded by the next chunk');error.code='ETOKENBUDGET';error.committed=Number(committed||0);error.reserved=projectReserved;error.requested=amount;throw error;}current.tokens+=amount;this.byKey.set(id,current);this.byProject.set(project,projectReserved+amount);return current.tokens;}
  release(key){const id=String(key),current=this.byKey.get(id);if(!current)return 0;const projectReserved=this.reservedForProject(current.projectId),remaining=Math.max(0,projectReserved-current.tokens);if(remaining)this.byProject.set(current.projectId,remaining);else this.byProject.delete(current.projectId);this.byKey.delete(id);return current.tokens;}
}

module.exports={estimateTextTokens,estimateChunkTokens,scoreChunkRisk,adaptiveContextConfig,selectModel,selectChunksWithinByteBudget,changedPathsFromCompare,subsetDiffResult,carryForwardFindings,mergeCarriedFindings,TokenBudgetLedger,normalizePath};
