'use strict';

const core=require('./codex-safe-core');
const SEVERITY_ORDER=Object.freeze({critical:5,high:4,medium:3,low:2,info:1});

function estimateTextTokens(value,bytesPerToken=2){return core.estimateTextTokens(value,bytesPerToken);}
function estimateChunkTokens(prompt,maxFindings=1){const estimatedOutputTokens=Math.max(96,96+Math.max(1,Number(maxFindings)||1)*180),estimate=core.estimateRequestTokens(prompt,{estimatedOutputTokens});return Object.freeze({input:estimate.inputTokens,output:estimate.outputTokens,total:estimate.totalTokens});}
function scoreChunkRisk(chunk){return core.scoreEvidenceRisk({paths:(chunk?.files||[]).map(file=>String(file.path||'')),text:String(chunk?.diffText||'')});}
function adaptiveContextConfig(config,policy,chunk){const riskScore=scoreChunkRisk(chunk),enabled=Boolean(config.contextEnabled)&&Number(policy.maxContextBytes||0)>0;if(!enabled)return{...config,...policy,contextEnabled:false,maxContextBytes:0,maxContextFiles:0,contextLines:0,riskScore};if(config.adaptiveContextEnabled===false)return{...config,...policy,riskScore};return{...config,...policy,riskScore,maxContextBytes:core.adaptiveBudget(policy.maxContextBytes,riskScore,{min:16*1024}),maxContextFiles:core.adaptiveBudget(policy.maxContextFiles,riskScore,{min:1}),contextLines:core.adaptiveBudget(policy.contextLines,riskScore,{min:4})};}
function selectModel(config,riskScore){return core.selectModel({model:config.codexModel,fastModel:config.codexFastModel,riskScore});}
function selectChunksWithinByteBudget(chunks,maxBytes){return core.selectChunksWithinByteBudget(chunks,maxBytes,{riskFn:scoreChunkRisk});}
function normalizePath(entry){return String(entry?.new_path||entry?.old_path||entry?.path||'').replace(/\\/g,'/');}
function changedPathsFromCompare(compare){const paths=new Set();for(const entry of compare?.items||compare?.diffs||[]){const oldPath=String(entry.old_path||'').replace(/\\/g,'/'),newPath=String(entry.new_path||'').replace(/\\/g,'/');if(oldPath)paths.add(oldPath);if(newPath)paths.add(newPath);}return paths;}
function subsetDiffResult(diffResult,paths){const wanted=paths instanceof Set?paths:new Set(paths||[]);return{complete:true,profile:diffResult?.profile||'incremental',items:(diffResult?.items||[]).filter(entry=>wanted.has(normalizePath(entry))||wanted.has(String(entry.old_path||'').replace(/\\/g,'/')))};}
function dbFindingToReview(row){return{fingerprint:String(row.fingerprint||''),severity:String(row.severity||'info'),category:String(row.category||'other'),file:String(row.file||''),side:String(row.side||'new'),line:Number(row.line||1),endLine:Number(row.end_line||row.line||1),title:String(row.title||''),description:String(row.description||''),suggestion:String(row.suggestion||''),confidence:Number(row.confidence||0),anchorHash:String(row.anchor_hash||''),discussionId:row.discussion_id||null};}
function carryForwardFindings(rows,changedPaths){const changed=changedPaths instanceof Set?changedPaths:new Set(changedPaths||[]);return(rows||[]).filter(row=>!changed.has(String(row.file||'').replace(/\\/g,'/'))).map(dbFindingToReview);}
function passesThreshold(severity,threshold){return(SEVERITY_ORDER[severity]||0)>=(SEVERITY_ORDER[threshold]||0);}
function mergeCarriedFindings(review,carried,policy){if(!carried?.length)return review;const deduped=new Map();for(const finding of[...(review.allFindings||review.findings||[]),...carried]){const previous=deduped.get(finding.fingerprint);if(!previous||Number(finding.confidence||0)>Number(previous.confidence||0))deduped.set(finding.fingerprint,finding);}const uncapped=[...deduped.values()].sort((a,b)=>(SEVERITY_ORDER[b.severity]||0)-(SEVERITY_ORDER[a.severity]||0)||Number(b.confidence||0)-Number(a.confidence||0)||String(a.file).localeCompare(String(b.file))),blocking=uncapped.some(f=>passesThreshold(f.severity,policy.blockingSeverity)),truncatedFindingCount=Math.max(0,uncapped.length-policy.maxFindings),allFindings=uncapped.slice(0,policy.maxFindings),findings=allFindings.filter(f=>passesThreshold(f.severity,policy.severityThreshold));return{...review,allFindings,findings,truncatedFindingCount:Math.max(Number(review.truncatedFindingCount||0),truncatedFindingCount),verdict:review.coverageComplete===false?'incomplete':blocking?'block':findings.length?'needs_attention':'pass',carriedFindingCount:carried.length};}

module.exports={estimateTextTokens,estimateChunkTokens,scoreChunkRisk,adaptiveContextConfig,selectModel,selectChunksWithinByteBudget,changedPathsFromCompare,subsetDiffResult,carryForwardFindings,mergeCarriedFindings,TokenBudgetLedger:core.TokenBudgetLedger,normalizePath};
