'use strict';
const{loadConfig}=require('./config');const{Store}=require('./db');const{GitLabClient}=require('./gitlab');const{ReviewService}=require('./service');const{Publisher}=require('./publication');const{Telemetry}=require('./telemetry');const{createHttpServer}=require('./http');const{probeCodexCapabilities}=require('./codex');
function log(level,value){const record=typeof value==='object'&&value?value:{message:String(value)};process.stdout.write(`${JSON.stringify({ts:new Date().toISOString(),level,...record})}\n`);}
async function listen(server,port,host){await new Promise((resolve,reject)=>{const onError=e=>{server.off('listening',onListening);reject(e);},onListening=()=>{server.off('error',onError);resolve();};server.once('error',onError);server.once('listening',onListening);server.listen(port,host);});}
async function main(){
  const startedAt=Date.now(),config=loadConfig(),logger={info:v=>log('info',v),warn:v=>log('warn',v),error:v=>log('error',v)},telemetry=new Telemetry({logger,endpoint:process.env.OTEL_EXPORTER_OTLP_ENDPOINT||'',serviceName:process.env.OTEL_SERVICE_NAME||'codex-review-service',timeoutMs:Number(process.env.OTEL_EXPORT_TIMEOUT_MS||3000)});
  const capability=await probeCodexCapabilities(config);logger.info({event:'codex_ready',version:capability.version,versionMatched:capability.versionMatched});if(capability.versionMatched===false)logger.warn({event:'codex_version_policy_warning',version:capability.version});
  const store=new Store(config.dbPath),recoveredJobs=store.recoverInterruptedJobs(),recoveredPublications=store.recoverPublications();if(recoveredJobs)logger.info({event:'jobs_recovered',count:recoveredJobs});if(recoveredPublications)logger.info({event:'publications_recovered',count:recoveredPublications});
  const gitlab=new GitLabClient(config),service=new ReviewService({config,store,gitlab,logger,telemetry}),publisher=new Publisher({config,store,gitlab,logger});service.startWorkers();publisher.start();
  const server=createHttpServer({config,store,service,publisher,gitlab,telemetry,logger,startedAt});await listen(server,config.port,config.host);logger.info({event:'service_started',host:config.host,port:config.port,workers:config.workerConcurrency,publishers:config.publisherConcurrency,schemaVersion:store.schemaVersion(),synchronous:store.synchronousMode()});
  const maintenance=setInterval(()=>{try{const pruned=store.prune(config);store.checkpoint();if(pruned.webhooks||pruned.jobs)logger.info({event:'data_pruned',...pruned});}catch(error){logger.warn({event:'maintenance_failed',code:error.code||'EMAINTENANCE'});}},config.maintenanceIntervalMs);maintenance.unref?.();
  const reconcile=setInterval(()=>{service.reconcile().then(result=>{if(result.enqueued)logger.info({event:'reconcile_enqueued',...result});}).catch(error=>logger.warn({event:'reconcile_failed',code:error.code||'ERECONCILE'}));},config.reconcileIntervalMs);reconcile.unref?.();if(config.gitlabProjectAllowlist)setTimeout(()=>service.reconcile().catch(()=>{}),Math.min(5000,config.pollIntervalMs)).unref?.();else logger.warn({event:'reconcile_disabled',reason:'GITLAB_PROJECT_ALLOWLIST=* cannot be exhaustively reconciled'});
  let shuttingDown=false;const shutdown=async signal=>{if(shuttingDown)return;shuttingDown=true;logger.info({event:'shutdown',signal});clearInterval(maintenance);clearInterval(reconcile);await new Promise(resolve=>server.close(resolve));await service.stop();await publisher.stop();await telemetry.flush();store.checkpoint();store.close();};
  process.on('SIGTERM',()=>{shutdown('SIGTERM').catch(()=>process.exit(1));});process.on('SIGINT',()=>{shutdown('SIGINT').catch(()=>process.exit(1));});process.on('unhandledRejection',error=>logger.error({event:'unhandled_rejection',code:error?.code||'EUNHANDLED'}));
}
main().catch(error=>{log('error',{event:'startup_failed',code:error.code||'ESTART',message:error.message});process.exitCode=1;});
