'use strict';

const crypto=require('node:crypto');
const{FLOW_EVENTS}=require('./flow-tracking');
const EVENTS=Object.freeze(['review.completed','review.blocked','review.failed','service.degraded','service.recovered',...FLOW_EVENTS]);
function notifyError(message,code='ENOTIFY'){const error=new Error(message);error.code=code;return error;}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
function canonicalUtc(value=new Date()){const date=value instanceof Date?value:new Date(value);if(Number.isNaN(date.getTime()))throw notifyError('Notification event time is invalid','ENOTIFYEVENT');return date.toISOString();}
function counts(findings=[]){const out={critical:0,high:0,medium:0,low:0,info:0};for(const f of findings)if(Object.hasOwn(out,f.severity))out[f.severity]++;return out;}
function cardText(value,max=300){return String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').replace(/[<>&`*_~\[\](){}|]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);}
function cardUrl(value){let url;try{url=new URL(String(value||''));}catch{return'';}return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password&&!url.hash?url.toString():'';}
function secretEnvName(ref){return `CODEX_REVIEW_NOTIFY_${String(ref).toUpperCase().replace(/[^A-Z0-9]+/g,'_')}_WEBHOOK`;}
function signingEnvName(ref){return `CODEX_REVIEW_NOTIFY_${String(ref).toUpperCase().replace(/[^A-Z0-9]+/g,'_')}_SIGNING_SECRET`;}
function signingSecretFor(route,env=process.env){return route.provider==='feishu'?String(env[signingEnvName(route.secretRef)]||'').trim():'';}
function feishuSignature(secret,timestamp=Math.floor(Date.now()/1000)){const stringToSign=`${timestamp}\n${secret}`,sign=crypto.createHmac('sha256',stringToSign).update('').digest('base64');return{timestamp:String(timestamp),sign};}
function webhookFor(route,env=process.env){const name=secretEnvName(route.secretRef),value=String(env[name]||'').trim();if(!value)throw notifyError(`${name} is required for notification route ${route.name}`,'ENOTIFYSECRET');let url;try{url=new URL(value);}catch{throw notifyError(`${name} must be a valid HTTPS URL`,'ENOTIFYSECRET');}if(url.protocol!=='https:'||url.username||url.password||url.hash)throw notifyError(`${name} must be a credential-free HTTPS URL`,'ENOTIFYSECRET');const host=url.hostname.toLowerCase();if(route.provider==='feishu'&&!['open.feishu.cn','open.larksuite.com'].includes(host))throw notifyError(`${name} must use an official Feishu/Lark bot host`,'ENOTIFYSECRET');if(route.provider==='wecom'&&host!=='qyapi.weixin.qq.com')throw notifyError(`${name} must use qyapi.weixin.qq.com`,'ENOTIFYSECRET');return value;}
async function prepareNotificationRoutes(gitlab,config){if(!config.notificationEnabled)return Object.freeze({...config,notificationRoutesResolved:Object.freeze([])});const resolved=[];for(const route of config.notificationRoutes){const projectIds=new Set(route.projects);for(const groupId of route.groups){const page=await gitlab.paginated(`/groups/${encodeURIComponent(groupId)}/projects`,{include_subgroups:'true',archived:'false',with_merge_requests_enabled:'true',simple:'true'});if(!page?.complete)throw notifyError(`Notification route ${route.name} group ${groupId} discovery incomplete`,'ENOTIFYROUTE');for(const project of page.items||[]){const id=Number(project?.id||0);if(Number.isInteger(id)&&id>0)projectIds.add(id);}}if(!route.projects.length&&!route.groups.length)for(const id of config.gitlabProjectAllowlist||[])projectIds.add(Number(id));for(const id of projectIds)if(config.gitlabProjectAllowlist&&!config.gitlabProjectAllowlist.has(Number(id)))throw notifyError(`Notification route ${route.name} includes out-of-scope project ${id}`,'ENOTIFYROUTE');const finalRoute=Object.freeze({...route,projectIds:Object.freeze([...projectIds].sort((a,b)=>a-b))});webhookFor(finalRoute);resolved.push(finalRoute);}return Object.freeze({...config,notificationRoutesResolved:Object.freeze(resolved)});}
function eventForReview({job,mr,snapshot,review,durationMs,topFindings=3,occurredAt}){const type=review.verdict==='block'||review.verdict==='incomplete'?'review.blocked':'review.completed';return Object.freeze({type,occurredAt:canonicalUtc(occurredAt),projectId:Number(job.project_id),mrIid:Number(job.mr_iid),title:cardText(mr?.title||snapshot?.title||'',300),url:cardUrl(mr?.web_url||''),author:cardText(mr?.author?.name||mr?.author?.username||'',120),sourceBranch:cardText(snapshot?.sourceBranch||job.source_branch||'',200),targetBranch:cardText(snapshot?.targetBranch||mr?.target_branch||'',200),headSha:cardText(snapshot?.headSha||job.head_sha||'',64),verdict:cardText(review.verdict||'',40),coverageComplete:review.coverageComplete!==false,findingCounts:counts(review.findings),findingCount:Number(review.findings?.length||0),topFindings:(review.findings||[]).slice(0,topFindings).map(f=>({severity:cardText(f.severity,20),title:cardText(f.title,180),file:cardText(f.file,300),line:Number(f.line||0)})),durationMs:Number(durationMs||0)});}
function eventForFailure(job,code){return Object.freeze({type:'review.failed',occurredAt:canonicalUtc(),projectId:Number(job.project_id),mrIid:Number(job.mr_iid),title:'',url:'',author:'',sourceBranch:cardText(job.source_branch||'',200),targetBranch:'',headSha:cardText(job.head_sha||'',64),verdict:'failed',coverageComplete:false,findingCounts:counts([]),findingCount:0,topFindings:[],durationMs:0,errorCode:cardText(code||'EUNKNOWN',80)});}
function systemEvent(type,details={}){if(!EVENTS.includes(type)||!type.startsWith('service.'))throw notifyError(`Unsupported system notification event: ${type}`,'ENOTIFYEVENT');return Object.freeze({type,occurredAt:canonicalUtc(),projectId:0,mrIid:0,title:'Codex Review Service',url:'',author:'',sourceBranch:'',targetBranch:'',headSha:'',verdict:type==='service.recovered'?'recovered':'degraded',coverageComplete:false,findingCounts:counts([]),findingCount:0,topFindings:[],durationMs:0,details:Object.freeze(Object.fromEntries(Object.entries(details).map(([key,value])=>[cardText(key,80),cardText(value,200)])))});}
function planNotificationActions(config,event,runKey){if(!config.notificationEnabled)return[];const actions=[];for(const route of config.notificationRoutesResolved||[]){const events=route.events.length?route.events:config.notificationEvents;if(!events.includes(event.type))continue;if(!event.type.startsWith('service.')&&!route.projectIds.includes(Number(event.projectId)))continue;actions.push({routeName:route.name,provider:route.provider,secretRef:route.secretRef,eventType:event.type,dedupeKey:`${runKey}:${route.name}:${event.type}`,payload:event});}return actions;}
function titleFor(event){if(event.type==='review.blocked')return'🔴 Codex Review Blocked';if(event.type==='review.failed')return'⚠️ Codex Review Failed';if(event.type==='service.degraded')return'⚠️ Codex Review Service Degraded';if(event.type==='service.recovered')return'🟢 Codex Review Service Recovered';if(event.type==='gitlab.pipeline.failed')return'🔴 GitLab Pipeline Failed';if(event.type==='gitlab.pipeline.succeeded')return'🟢 GitLab Pipeline Succeeded';if(event.type==='gitlab.pipeline.canceled'||event.type==='gitlab.pipeline.skipped')return'⚪ GitLab Pipeline Terminal';if(event.type==='gitlab.mr.merged')return'🟢 GitLab MR Merged';if(event.type.startsWith('gitlab.mr.'))return'GitLab MR Lifecycle';if(event.type.startsWith('gitlab.tag.'))return'GitLab Tag Lifecycle';if(event.type.startsWith('gitlab.branch.'))return'GitLab Branch Lifecycle';return'🟢 Codex Review Completed';}
function summaryLines(event){const lines=[];if(String(event.type||'').startsWith('gitlab.')){if(event.projectId)lines.push(`Project: ${event.projectId}`);if(event.occurredAt)lines.push(`Time (UTC): ${event.occurredAt}`);if(event.flowKind==='pipeline'){lines.push(`Pipeline: #${event.externalId}`,`Ref: ${event.ref||'-'}`,`Status: ${event.status}`);if(event.source)lines.push(`Source: ${event.source}`);}else if(event.flowKind==='merge_request'){lines.push(`MR: !${event.mrIid} ${event.title||''}`.trim(),`Status: ${event.status}`);if(event.sourceBranch||event.targetBranch)lines.push(`Branches: ${event.sourceBranch||'-'} → ${event.targetBranch||'-'}`);}else{lines.push(`${event.flowKind==='tag'?'Tag':'Branch'}: ${event.ref||event.externalId}`,`Status: ${event.status}`);}if(event.actor)lines.push(`Actor: ${event.actor}`);if(event.durationMs)lines.push(`Duration: ${(event.durationMs/1000).toFixed(1)}s`);return lines;}const c=event.findingCounts||counts([]);if(event.projectId)lines.push(`Project: ${event.projectId}`,`MR: !${event.mrIid}${event.title?` ${event.title}`:''}`);if(event.occurredAt)lines.push(`Time (UTC): ${event.occurredAt}`);lines.push(`Verdict: ${event.verdict}`);if(event.errorCode)lines.push(`Error: ${event.errorCode}`);if(event.headSha)lines.push(`HEAD: ${event.headSha.slice(0,12)}`);if(event.projectId)lines.push(`Findings: Critical ${c.critical} · High ${c.high} · Medium ${c.medium} · Low ${c.low}`);if(event.durationMs)lines.push(`Duration: ${(event.durationMs/1000).toFixed(1)}s`);return lines;}
function feishuPayload(event,signature=null){const elements=[{tag:'div',text:{tag:'lark_md',content:summaryLines(event).join('\n')}}];if(event.jobs?.length)elements.push({tag:'div',text:{tag:'lark_md',content:`Failed jobs\n${event.jobs.map((job,i)=>`${i+1}. ${job.stage||'-'} · ${job.name} · ${job.failureReason||job.status}`).join('\n')}`}});if(event.topFindings?.length)elements.push({tag:'div',text:{tag:'lark_md',content:`Top findings\n${event.topFindings.map((f,i)=>`${i+1}. ${f.severity.toUpperCase()} · ${f.title} (${f.file}:${f.line})`).join('\n')}`}});if(event.url)elements.push({tag:'action',actions:[{tag:'button',text:{tag:'plain_text',content:'View Merge Request'},url:event.url,type:'primary'}]});return{...(signature||{}),msg_type:'interactive',card:{header:{title:{tag:'plain_text',content:titleFor(event)}},elements}};}
function wecomPayload(event){const horizontal_content_list=summaryLines(event).filter(line=>!line.startsWith('Project: ')).slice(0,6).map(line=>{const idx=line.indexOf(':');return{keyname:cardText(idx>0?line.slice(0,idx):'Status',5),value:cardText(idx>0?line.slice(idx+1).trim():line,26)};});const actionUrl=event.url||'https://work.weixin.qq.com/',card={card_type:'text_notice',source:{desc:'Codex Review'},main_title:{title:cardText(titleFor(event),26),desc:cardText(event.title||'',30)},horizontal_content_list,card_action:{type:1,url:actionUrl}};if(event.jobs?.length)card.sub_title_text=cardText(event.jobs.map((job,i)=>`${i+1}. ${job.stage||'-'}/${job.name}: ${job.failureReason||job.status}`).join(' · '),112);else if(event.topFindings?.length)card.sub_title_text=cardText(event.topFindings.map((f,i)=>`${i+1}. [${f.severity}] ${f.title} ${f.file}:${f.line}`).join(' · '),112);if(event.url)card.jump_list=[{type:1,url:event.url,title:'View MR'}];return{msgtype:'template_card',template_card:card};}
function payloadFor(provider,event,route=null,env=process.env){if(provider==='feishu'){const secret=route?signingSecretFor(route,env):'',signature=secret?feishuSignature(secret):null;return feishuPayload(event,signature);}if(provider==='wecom')return wecomPayload(event);throw notifyError(`Unsupported notification provider: ${provider}`,'ENOTIFYPROVIDER');}
async function postWebhook(url,payload,timeoutMs){let response;try{response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(timeoutMs)});}catch(cause){const error=notifyError('Notification network request failed','ENOTIFYNETWORK');error.cause=cause;throw error;}let body={};try{body=await response.json();}catch{}if(!response.ok){const error=notifyError(`Notification HTTP ${response.status}`,'ENOTIFYHTTP');error.status=response.status;throw error;}if(Object.hasOwn(body,'errcode')&&Number(body.errcode)!==0)throw notifyError(`WeCom rejected notification: ${body.errcode}`,'ENOTIFYREMOTE');if((Object.hasOwn(body,'code')&&Number(body.code)!==0)||(Object.hasOwn(body,'StatusCode')&&Number(body.StatusCode)!==0))throw notifyError('Feishu rejected notification','ENOTIFYREMOTE');return body;}
function retryableNotification(error){if(!error)return true;if(error.code==='ENOTIFYHTTP'){const s=Number(error.status);return[408,409,425,429].includes(s)||s>=500;}return error.code==='ENOTIFYNETWORK';}
function notificationDelay(config,item){const base=Math.min(config.notificationRetryMaxDelayMs,config.notificationRetryBaseDelayMs*(2**Math.max(0,item.attempt-1)));return Math.round(base*(0.85+Math.random()*0.3));}
class Notifier{constructor({config,store,logger=console,env=process.env}){this.config=config;this.store=store;this.logger=logger;this.env=env;this.stopping=false;this.workers=[];this.routes=new Map((config.notificationRoutesResolved||[]).map(r=>[r.name,r]));}refreshConfig(config){this.config=config;this.routes=new Map((config.notificationRoutesResolved||[]).map(r=>[r.name,r]));}async execute(item){const route=this.routes.get(item.route_name);if(!route)throw notifyError(`Notification route disappeared: ${item.route_name}`,'ENOTIFYROUTE');await postWebhook(webhookFor(route,this.env),payloadFor(route.provider,item.payload,route,this.env),this.config.notificationRequestTimeoutMs);return{remoteId:`${route.provider}:${route.name}`};}async process(item){try{const result=await this.execute(item);this.store.finishNotification(item.id,result.remoteId);this.logger.info?.({event:'notification_delivered',outboxId:item.id,route:item.route_name,provider:item.provider,eventType:item.event_type,attempt:item.attempt});}catch(error){const retry=item.attempt<this.config.maxNotificationAttempts&&retryableNotification(error)&&!this.stopping;this.logger.warn?.({event:retry?'notification_retry':'notification_failed',outboxId:item.id,route:item.route_name,provider:item.provider,eventType:item.event_type,attempt:item.attempt,code:error.code||'ENOTIFY',status:error.status||null});if(retry)this.store.retryNotification(item.id,error.code||'ENOTIFY',notificationDelay(this.config,item));else this.store.failNotification(item.id,error.code||'ENOTIFY');}}async workerLoop(){while(!this.stopping){const item=this.store.claimNotification();if(!item){await sleep(this.config.notificationPollIntervalMs);continue;}await this.process(item);}}start(){if(!this.config.notificationEnabled||this.workers.length)return this.workers;this.workers=Array.from({length:this.config.notificationConcurrency},()=>this.workerLoop());return this.workers;}async stop(){this.stopping=true;await Promise.allSettled(this.workers);}}
module.exports={EVENTS,Notifier,prepareNotificationRoutes,eventForReview,eventForFailure,systemEvent,planNotificationActions,payloadFor,feishuPayload,wecomPayload,cardText,cardUrl,secretEnvName,signingEnvName,signingSecretFor,feishuSignature,webhookFor,retryableNotification,notificationDelay,postWebhook};
