'use strict';

const { discussionResolved }=require('./gitlab');
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
function retryablePublication(error){if(!error)return true;if(error.code==='EGITLABHTTP'){const status=Number(error.status);if([408,409,425,429].includes(status)||status>=500)return true;if(status>=400)return false;}return['EGITLABNETWORK','EGITLABCIRCUIT','EGITLABPAGINATION'].includes(error.code)||!error.code;}
function retryDelay(config,item,error){if(Number.isFinite(error?.retryAfterMs))return Math.min(config.retryMaxDelayMs,error.retryAfterMs);const base=Math.min(config.retryMaxDelayMs,config.retryBaseDelayMs*(2**Math.max(0,item.attempt-1)));return Math.round(base*(0.85+Math.random()*0.3));}
class Publisher{
  constructor({config,store,gitlab,logger=console}){this.config=config;this.store=store;this.gitlab=gitlab;this.logger=logger;this.stopping=false;this.workers=[];}
  projectAllowed(item){return !this.config.gitlabProjectAllowlist||this.config.gitlabProjectAllowlist.has(Number(item.project_id));}
  async currentSnapshot(item){const p=item.payload||{};if(!p.headSha||!p.startSha)return true;const mr=await this.gitlab.getMergeRequest(item.project_id,item.mr_iid),head=String(mr.diff_refs?.head_sha||mr.sha||''),start=String(mr.diff_refs?.start_sha||'');return mr.state==='opened'&&head===String(p.headSha)&&start===String(p.startSha);}
  async publishSummary(item){if(!(await this.currentSnapshot(item)))return{cancelled:true};const result=await this.gitlab.upsertSummary(item.project_id,item.mr_iid,item.payload.body);return{remoteId:String(result?.id||'')};}
  async publishFinding(item){if(!(await this.currentSnapshot(item)))return{cancelled:true};const p=item.payload,finding=p.finding;const existing=await this.gitlab.findDiscussionByFingerprint(item.project_id,item.mr_iid,finding.fingerprint);if(existing&&discussionResolved(existing)===false){this.store.setDiscussionIdByFingerprint(item.run_id,finding.fingerprint,String(existing.id));return{remoteId:String(existing.id)};}const created=await this.gitlab.createDiscussion(item.project_id,item.mr_iid,finding,p.diffRefs,p.oldPath,p.newPath);this.store.setDiscussionIdByFingerprint(item.run_id,finding.fingerprint,String(created.id));return{remoteId:String(created.id)};}
  async resolveDiscussion(item){const p=item.payload,discussion=await this.gitlab.getDiscussion(item.project_id,item.mr_iid,p.discussionId);if(!discussion)return{remoteId:String(p.discussionId)};if(discussionResolved(discussion)===false)await this.gitlab.setDiscussionResolved(item.project_id,item.mr_iid,p.discussionId,true);return{remoteId:String(p.discussionId)};}
  staleRunningStatus(item){if(item.payload?.state!=='running')return false;const match=String(item.dedupe_key||'').match(/^job:(\d+):status:running$/);if(!match)return false;const job=this.store.getJob(Number(match[1]));return !job||job.status!=='running';}
  async publishStatus(item){if(this.staleRunningStatus(item))return{cancelled:true};const p=item.payload,result=await this.gitlab.setCommitStatus(p.statusProjectId,p.headSha,p.state,p.description,p.ref||'',p.pipelineId||null);return{remoteId:String(result?.id||'')};}
  async execute(item){if(!this.projectAllowed(item))return{cancelled:true,reason:'project_scope'};switch(item.action_type){case'summary':return this.publishSummary(item);case'finding':return this.publishFinding(item);case'resolve':return this.resolveDiscussion(item);case'status':case'cancel_status':return this.publishStatus(item);default:{const error=new Error(`Unknown publication action: ${item.action_type}`);error.code='EPUBLISHCONFIG';throw error;}}}
  async process(item){try{const result=await this.execute(item);if(result?.cancelled)this.store.cancelPublication(item.id,result.reason==='project_scope'?'EPROJECTNOTALLOWED':'ESTALEPUBLICATION');else this.store.finishPublication(item.id,result?.remoteId||null);}catch(error){const code=error?.code||'EPUBLISH',retry=item.attempt<this.config.maxPublishAttempts&&retryablePublication(error)&&!this.stopping;this.logger.warn?.({event:retry?'publication_retry':'publication_failed',outboxId:item.id,runId:item.run_id,projectId:item.project_id,mrIid:item.mr_iid,action:item.action_type,attempt:item.attempt,code,status:error?.status||null});if(retry)this.store.retryPublication(item.id,code,retryDelay(this.config,item,error));else this.store.failPublication(item.id,code);}}
  async workerLoop(workerId){while(!this.stopping){const item=this.store.claimPublication();if(!item){await sleep(this.config.publisherPollIntervalMs);continue;}this.logger.info?.({event:'publication_started',workerId,outboxId:item.id,runId:item.run_id,action:item.action_type});await this.process(item);}}
  start(){if(this.workers.length)return this.workers;this.workers=Array.from({length:this.config.publisherConcurrency},(_,index)=>this.workerLoop(index+1).catch(error=>{this.logger.error?.({event:'publisher_crashed',workerId:index+1,code:error.code||'EPUBLISHER'});throw error;}));return this.workers;}
  async stop(){this.stopping=true;await Promise.allSettled(this.workers);}
}
module.exports={Publisher,retryablePublication,retryDelay};
