'use strict';

const fs=require('node:fs');
const http=require('node:http');
const os=require('node:os');
const path=require('node:path');
const{loadStructuredConfig}=require('./config');
const{hydrateSecretEnv}=require('./secrets');
const{runCodexLocal,probeCodexRuntimeLocal,probeCodexCapabilitiesLocal}=require('./codex');
const{SAFE_CORE_VERSION,SAFE_CONTRACT_VERSION,REVIEW_RECEIPT_SCHEMA_VERSION,REVIEW_PROMPT_CONTRACT_VERSION}=require('./codex-safe-core/safe-contract');
function str(value,fallback,label){const v=value===undefined?fallback:value;if(typeof v!=='string'||/[\r\n\0]/.test(v))throw new Error(`${label} is invalid`);return v.trim();}
function integer(value,fallback,label,min,max){const v=value===undefined?fallback:value;if(!Number.isInteger(v)||v<min||v>max)throw new Error(`${label} is invalid`);return v;}
function runnerConfig(){const value=loadStructuredConfig().value,runner=value.runner||{},codex=value.codex||{},review=value.review||{},mode=str(runner.mode,'inline','runner.mode');if(mode!=='isolated')throw new Error('runner.mode must be isolated when starting codex-review-runner');const socket=str(runner.socket,'/run/codex-review-runner/runner.sock','runner.socket');if(!socket.startsWith('/'))throw new Error('runner.socket must be an absolute path');const versionPolicy=str(codex.versionPolicy,'warn','codex.versionPolicy');if(!['off','warn','strict'].includes(versionPolicy))throw new Error('codex.versionPolicy is invalid');return{socket,maxBodyBytes:8*1024*1024,codexPath:str(codex.path,'codex','codex.path')||'codex',codexHome:str(codex.home,'','codex.home'),codexModel:str(codex.model,'','codex.model'),codexVersionPolicy:versionPolicy,codexAllowedVersionPattern:str(codex.allowedVersionPattern,'','codex.allowedVersionPattern'),codexProviderMode:str(codex.providerMode,'auto','codex.providerMode'),codexProviderBaseUrl:str(codex.providerBaseUrl,'','codex.providerBaseUrl'),codexProviderApiKeyEnv:str(codex.apiKeyEnv,codex.providerMode==='openai-compatible'?'CODEX_PROVIDER_API_KEY':'OPENAI_API_KEY','codex.apiKeyEnv'),codexProviderCredentialSource:str(codex.credentialSource,'auto','codex.credentialSource'),codexProviderAllowInsecureHttp:Boolean(codex.allowInsecureHttp),codexConnectTimeoutSeconds:integer(codex.connectTimeoutSeconds,15,'codex.connectTimeoutSeconds',1,120),codexRequestTimeoutSeconds:integer(codex.requestTimeoutSeconds,180,'codex.requestTimeoutSeconds',10,900),codexStreamIdleTimeoutSeconds:integer(codex.streamIdleTimeoutSeconds,60,'codex.streamIdleTimeoutSeconds',5,600),reviewTimeoutSeconds:integer(review.timeoutSeconds,180,'review.timeoutSeconds',30,900)};}
function json(res,status,body){const data=Buffer.from(JSON.stringify(body));res.writeHead(status,{'Content-Type':'application/json','Content-Length':data.length,'Cache-Control':'no-store'});res.end(data);}
function readBody(req,maxBytes){return new Promise((resolve,reject)=>{const chunks=[];let size=0;req.on('data',chunk=>{size+=chunk.length;if(size>maxBytes){reject(Object.assign(new Error('runner request too large'),{status:413}));req.destroy();return;}chunks.push(chunk);});req.on('end',()=>resolve(Buffer.concat(chunks).toString('utf8')));req.on('error',reject);});}
function capabilityEnvelope(config, capability){return Object.freeze({ok:true,version:capability.version,versionMatched:capability.versionMatched,safeCoreVersion:SAFE_CORE_VERSION,safeContractVersion:SAFE_CONTRACT_VERSION,reviewReceiptSchemaVersion:REVIEW_RECEIPT_SCHEMA_VERSION,promptContractVersion:REVIEW_PROMPT_CONTRACT_VERSION,os:process.platform,arch:process.arch,hostname:os.hostname(),model:config.codexModel||'',maxConcurrency:1});}
async function main(){hydrateSecretEnv();const config=runnerConfig(),socket=config.socket;const startupCapability=await probeCodexCapabilitiesLocal(config,true);fs.mkdirSync(path.dirname(socket),{recursive:true});try{fs.unlinkSync(socket);}catch(error){if(error.code!=='ENOENT')throw error;}const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/health'){const capability=await probeCodexCapabilitiesLocal(config);return json(res,200,capabilityEnvelope(config,capability));}if(req.method==='POST'&&req.url==='/probe'){const runtime=await probeCodexRuntimeLocal(config,true);return json(res,200,runtime);}if(req.method!=='POST'||req.url!=='/review')return json(res,404,{error:'not_found'});const raw=await readBody(req,config.maxBodyBytes);let payload;try{payload=JSON.parse(raw);}catch{return json(res,400,{error:'invalid_json'});}if(typeof payload?.prompt!=='string'||payload.prompt.length===0)return json(res,400,{error:'invalid_prompt'});if(payload?.promptContractVersion!==REVIEW_PROMPT_CONTRACT_VERSION)return json(res,409,{error:'ERUNNERCONTRACT',message:'Runner prompt contract mismatch'});const controller=new AbortController();req.on('close',()=>{if(!res.writableEnded)controller.abort(Object.assign(new Error('controller disconnected'),{code:'ERUNNERDISCONNECT'}));});const execution={...config,reviewTimeoutSeconds:Math.min(config.reviewTimeoutSeconds,Number(payload.reviewTimeoutSeconds)||config.reviewTimeoutSeconds),codexModel:typeof payload.model==='string'?payload.model:config.codexModel},result=await runCodexLocal(payload.prompt,execution,controller.signal,Number(payload.maxFindings)||40);return json(res,200,result);}catch(error){return json(res,error.status||500,{error:error.code||'ERUNNER',message:String(error.message||'runner failure').slice(0,300)});}});server.listen(socket,()=>{fs.chmodSync(socket,0o660);process.stdout.write(`${JSON.stringify({event:'runner_started',socket,capability:capabilityEnvelope(config,startupCapability)})}\n`);});let closing=false;const shutdown=(code=0)=>{if(closing)return;closing=true;server.close(()=>{try{fs.unlinkSync(socket);}catch{}process.exit(code);});};process.on('SIGTERM',()=>shutdown(0));process.on('SIGINT',()=>shutdown(0));process.on('unhandledRejection',error=>{process.stderr.write(`${JSON.stringify({event:'runner_fatal',kind:'unhandledRejection',code:error?.code||'EUNHANDLED'})}\n`);shutdown(1);});process.on('uncaughtException',error=>{process.stderr.write(`${JSON.stringify({event:'runner_fatal',kind:'uncaughtException',code:error?.code||'EUNHANDLED'})}\n`);shutdown(1);});}
if(require.main===module)main().catch(error=>{process.stderr.write(`${JSON.stringify({event:'runner_startup_failed',code:error.code||'ERUNNER',message:error.message})}\n`);process.exitCode=1;});
module.exports={runnerConfig,readBody,capabilityEnvelope};
