'use strict';

const crypto=require('node:crypto');
const{buildSnapshot,buildPrompt,validateChunkResult,consolidateReviews,emptyReview,formatSummary,createServiceReviewReceipt}=require('./review');
const{runCodex}=require('./codex');
const{getEffectivePolicy}=require('./policy');
const{buildReviewContext}=require('./context');
const{classifyFindingLifecycle}=require('./finding-ledger');
const{eventForReview,eventForFailure,planNotificationActions}=require('./notification');
const NON_RETRYABLE_ERRORS=new Set(['ECODEXVERSION','ECODEXOUTPUT','ECODEXNOTFOUND','EPROJECTPOLICY','EJOBTIMEOUT','EUNAUTHORIZED','ETOKENBUDGET']);
function abortError(code,message){return Object.assign(new Error(message),{code});}
function retryable(error){if(!error)return true;if(NON_RETRYABLE_ERRORS.has(error.code))return false;if(error.code==='EGITLABHTTP'){const status=Number(error.status);if([408,409,425,429].includes(status)||status>=500)return true;if(status>=400)return false;}return !['EPROJECTNOTALLOWED'].includes(error.code);}
function retryDelay(config,job,error){if(Number.isFinite(error?.retryAfterMs))return Math.min(config.retryMaxDelayMs,error.retryAfterMs);const base=Math.min(config.retryMaxDelayMs,config.retryBaseDelayMs*(2**Math.max(0,job.attempt-1)));return Math.round(base*(0.85+Math.random()*0.3));}
function usageAdd(total,next={}){for(const key of['inputTokens','cachedInputTokens','cacheWriteInputTokens','outputTokens','reasoningOutputTokens'])total[key]=(total[key]||0)+Number(next[key]||0);return total;}
function usageTotal(usage){return Number(usage.inputTokens||0)+Number(usage.outputTokens||0);}
function utcDayStart(){const d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())).toISOString();}
function isDraft(mr){return mr?.draft===true||mr?.work_in_progress===true;}

class ReviewService{
  constructor({config,store,gitlab,logger=console,telemetry=null,runCodexFn=runCodex,getPolicyFn=getEffectivePolicy,contextFn=buildReviewContext}){this.config=config;this.store=store;this.gitlab=gitlab;this.logger=logger;this.telemetry=telemetry;this.runCodexFn=runCodexFn;this.getPolicyFn=getPolicyFn;this.contextFn=contextFn;this.active=new Map();this.stopping=false;this.workers=[];}
  key(projectId,iid){return`${projectId}:${iid}`;}
  traceId(value=''){return this.telemetry?.traceId(value)||crypto.createHash('md5').update(value||crypto.randomUUID()).digest('hex');}
  ensureAllowedProject(projectId){if(this.config.gitlabProjectAllowlist&&!this.config.gitlabProjectAllowlist.has(Number(projectId))){const error=new Error('GitLab project is not allowed');error.code='EPROJECTNOTALLOWED';throw error;}}
  handleEvent(event,webhookId){if(!event.projectAllowed||!event.projectId)return{status:'ignored'};this.ensureAllowedProject(event.projectId);if(event.shouldCancel&&event.iid){this.store.cancelMergeRequest(event.projectId,event.iid,'cancelled');const active=this.active.get(this.key(event.projectId,event.iid));active?.controller.abort(abortError('ECANCELLED',`Merge request ${event.action}`));return{status:'cancelled'};}if(!event.shouldReview)return{status:'ignored'};const manual=event.kind==='note',snapshotKey=event.startSha&&event.headSha?`snapshot:${event.startSha}:${event.headSha}`:event.headSha?`head:${event.headSha}`:`event:${webhookId}`,dedupeKey=manual?`command:${webhookId}`:snapshotKey;const jobId=this.store.enqueue({projectId:event.projectId,mrIid:event.iid,baseSha:event.baseSha||'',startSha:event.startSha||'',headSha:event.headSha||'',sourceBranch:event.sourceBranch||'',trigger:manual?'command':event.action,dedupeKey,requestedByUserId:manual?event.userId:null,requestWebhookId:webhookId,maxQueueDepth:this.config.maxQueueDepth,delayMs:manual?0:this.config.reviewDebounceMs,traceId:this.traceId(String(webhookId))});const active=this.active.get(this.key(event.projectId,event.iid)),changed=active&&((event.headSha&&active.headSha&&event.headSha!==active.headSha)||(event.startSha&&active.startSha&&event.startSha!==active.startSha));if(changed)active.controller.abort(abortError('ESUPERSEDED','A newer merge request snapshot arrived'));return{status:jobId?'queued':'duplicate',jobId};}
  enqueueHydratedMr(projectId,mr,trigger='reconcile'){if(isDraft(mr)&&!this.config.reviewDraftMergeRequests)return null;const headSha=String(mr.diff_refs?.head_sha||mr.sha||'').trim(),startSha=String(mr.diff_refs?.start_sha||'').trim();if(!headSha||!startSha)return null;const jobId=this.store.enqueue({projectId,mrIid:Number(mr.iid),baseSha:String(mr.diff_refs?.base_sha||''),startSha,headSha,sourceBranch:String(mr.source_branch||''),trigger,dedupeKey:`snapshot:${startSha}:${headSha}`,maxQueueDepth:this.config.maxQueueDepth,delayMs:this.config.reviewDebounceMs,traceId:this.traceId(`${projectId}:${mr.iid}:${startSha}:${headSha}`)});const active=this.active.get(this.key(projectId,Number(mr.iid)));if(active&&((active.headSha&&active.headSha!==headSha)||(active.startSha&&active.startSha!==startSha)))active.controller.abort(abortError('ESUPERSEDED','Reconciliation found a newer merge request snapshot'));return jobId;}
  async reconcile(){if(!this.config.gitlabProjectAllowlist||this.stopping)return{projects:0,enqueued:0};let enqueued=0;for(const projectId of this.config.gitlabProjectAllowlist){try{const result=await this.gitlab.listOpenMergeRequests(projectId);if(!result.complete)this.logger.warn?.({event:'reconcile_incomplete',projectId});for(const mr of result.items)if(this.enqueueHydratedMr(projectId,mr))enqueued++;}catch(error){this.logger.warn?.({event:'reconcile_failed',projectId,code:error.code||'EUNKNOWN',status:error.status||null});}}return{projects:this.config.gitlabProjectAllowlist.size,enqueued};}
  async authorizeManual(job){if(job.trigger!=='command')return true;if(!job.requested_by_user_id)return false;if(this.config.manualMinAccessLevel<=0)return true;const member=await this.gitlab.getProjectMember(job.project_id,job.requested_by_user_id);return Boolean(member&&Number(member.access_level)>=this.config.manualMinAccessLevel);}
  async hydrateJob(job){const mr=await this.gitlab.getMergeRequest(job.project_id,job.mr_iid);if(mr.state!=='opened')return{mr,terminal:'cancelled'};if(isDraft(mr)&&!this.config.reviewDraftMergeRequests)return{mr,terminal:'skipped'};const headSha=String(mr.diff_refs?.head_sha||mr.sha||'').trim(),startSha=String(mr.diff_refs?.start_sha||'').trim(),baseSha=String(mr.diff_refs?.base_sha||'').trim();if(!headSha||!startSha||!baseSha){const error=new Error('Merge request diff refs are not ready');error.code='EDIFFREFS';throw error;}let statusProjectId=Number(mr.source_project_id||job.project_id);if(!Number.isInteger(statusProjectId)||statusProjectId<=0)statusProjectId=job.project_id;const sourceBranch=String(mr.source_branch||''),pipelineId=await this.gitlab.resolveStatusPipeline(statusProjectId,job.project_id,job.mr_iid,headSha,sourceBranch,mr);const bound=this.store.bindJobSnapshot(job.id,{baseSha,startSha,headSha,sourceBranch,statusProjectId,pipelineId});if(bound.status==='duplicate')return{mr,terminal:'duplicate'};const active=this.active.get(this.key(job.project_id,job.mr_iid));if(active){active.headSha=headSha;active.startSha=startSha;active.statusProjectId=statusProjectId;active.pipelineId=pipelineId;active.sourceBranch=sourceBranch;}return{mr,terminal:null,statusProjectId,pipelineId};}
  checkProjectBudget(projectId){if(!this.config.projectDailyTokenBudget)return;const used=this.store.tokenUsageSince(projectId,utcDayStart());if(used>=this.config.projectDailyTokenBudget){const error=new Error('Project daily Codex token budget exhausted');error.code='ETOKENBUDGET';throw error;}}
  enqueueStatus(job,state,description,type='status'){if(!job.head_sha||!job.status_project_id)return null;return this.store.enqueuePublication({runId:null,projectId:job.project_id,mrIid:job.mr_iid,type,dedupeKey:`job:${job.id}:status:${state}`,payload:{statusProjectId:job.status_project_id,headSha:job.head_sha,state,description,ref:job.source_branch||'',pipelineId:job.pipeline_id||null}});}
  async reviewSnapshot(mr,diffs,policy,controller){const snapshot=buildSnapshot(mr,diffs,policy);if(!snapshot.chunks.length)return{snapshot,review:emptyReview(snapshot)};const perChunkFindings=Math.max(1,Math.ceil(policy.maxFindings/snapshot.chunks.length)),results=[],usage={inputTokens:0,cachedInputTokens:0,cacheWriteInputTokens:0,outputTokens:0,reasoningOutputTokens:0};let version='unknown',model='';for(const chunk of snapshot.chunks){if(controller.signal.aborted)throw controller.signal.reason;const contextConfig={...this.config,...policy},context=await this.contextFn(this.gitlab,mr,chunk,contextConfig);if(!context.complete)snapshot.advisories.push(`context:${context.reason||'partial'}`);const prompt=buildPrompt(snapshot,chunk,policy,context),executionConfig={...this.config,reviewTimeoutSeconds:policy.timeoutSeconds},result=await this.runCodexFn(prompt,executionConfig,controller.signal,perChunkFindings);version=result.version;model=result.model||this.config.codexModel||'';usageAdd(usage,result.usage);results.push(validateChunkResult(result.parsed,chunk,policy));if(this.config.mrMaxTokenBudget&&usageTotal(usage)>=this.config.mrMaxTokenBudget&&results.length<snapshot.chunks.length){snapshot.coverageGaps.push('token_budget');snapshot.coverageComplete=false;break;}}const review=consolidateReviews(snapshot,results,policy);review.codexVersion=version;review.codexModel=model;review.usage=usage;return{snapshot,review};}
  async assertCurrentSnapshot(job,snapshot){const latest=await this.gitlab.getMergeRequest(job.project_id,job.mr_iid),head=String(latest.diff_refs?.head_sha||latest.sha||''),start=String(latest.diff_refs?.start_sha||'');if(latest.state!=='opened'||head!==snapshot.headSha||start!==snapshot.startSha)throw abortError('ESUPERSEDED','Merge request diff snapshot changed during review');}
  planPublication(job,snapshot,review,policy){const actions=[],prefix=`job:${job.id}`,previous=this.store.priorFindings(job.project_id,job.mr_iid),findingLifecycle=classifyFindingLifecycle(review.findings,previous),lifecycleCounts=findingLifecycle.counts,lifecycleText=policy.language==='zh-CN'?`Finding 生命周期：新增 ${lifecycleCounts.new} · 持续 ${lifecycleCounts.persistent} · 已解决 ${lifecycleCounts.resolved} · 回归 ${lifecycleCounts.regressed}`:`Finding lifecycle: new ${lifecycleCounts.new} · persistent ${lifecycleCounts.persistent} · resolved ${lifecycleCounts.resolved} · regressed ${lifecycleCounts.regressed}`;review.findingLifecycle=findingLifecycle;actions.push({projectId:job.project_id,mrIid:job.mr_iid,type:'summary',dedupeKey:`${prefix}:summary`,payload:{headSha:snapshot.headSha,startSha:snapshot.startSha,body:`${formatSummary(review,snapshot,policy)}\n\n${lifecycleText}`}});const previousByFingerprint=new Map();for(const old of previous)if(!previousByFingerprint.has(old.fingerprint))previousByFingerprint.set(old.fingerprint,old);const current=new Set(review.findings.map(f=>f.fingerprint));if(this.config.autoResolveObsolete)for(const old of previousByFingerprint.values())if(old.discussion_id&&!current.has(old.fingerprint))actions.push({projectId:job.project_id,mrIid:job.mr_iid,type:'resolve',dedupeKey:`${prefix}:resolve:${old.discussion_id}`,payload:{headSha:snapshot.headSha,startSha:snapshot.startSha,discussionId:old.discussion_id}});for(const finding of review.findings.slice(0,policy.maxPublishedFindings)){const file=snapshot.files.find(f=>f.path===finding.file&&!f.skipped);if(!file)continue;actions.push({projectId:job.project_id,mrIid:job.mr_iid,type:'finding',dedupeKey:`${prefix}:finding:${finding.fingerprint}`,payload:{headSha:snapshot.headSha,startSha:snapshot.startSha,finding,diffRefs:snapshot.diffRefs,oldPath:file.old_path,newPath:file.new_path}});}const state=review.verdict==='block'||review.verdict==='incomplete'?'failed':'success',description=review.verdict==='pass'?'No substantive findings':review.verdict==='incomplete'?'Review coverage incomplete':`${review.findings.length} finding(s)`;actions.push({projectId:job.project_id,mrIid:job.mr_iid,type:'status',dedupeKey:`${prefix}:status:final`,payload:{statusProjectId:job.status_project_id||job.project_id,headSha:snapshot.headSha,state,description,ref:snapshot.sourceBranch,pipelineId:job.pipeline_id||null}});return actions;}
  async processJob(job){const key=this.key(job.project_id,job.mr_iid),controller=new AbortController();this.active.set(key,{headSha:job.head_sha||'',startSha:job.start_sha||'',controller,jobId:job.id,statusProjectId:job.status_project_id||job.project_id,pipelineId:job.pipeline_id||null,sourceBranch:job.source_branch||''});const started=Date.now(),timer=setTimeout(()=>controller.abort(abortError('EJOBTIMEOUT','Review job exceeded JOB_TIMEOUT_SECONDS')),this.config.jobTimeoutSeconds*1000);const run=async()=>{this.ensureAllowedProject(job.project_id);if(!(await this.authorizeManual(job))){this.store.finishJob(job.id,'unauthorized','EUNAUTHORIZED');return;}const hydrated=await this.hydrateJob(job);if(hydrated.terminal){if(hydrated.terminal!=='duplicate')this.store.finishJob(job.id,hydrated.terminal,hydrated.terminal==='skipped'?'EDRAFT':null);return;}job=this.store.getJob(job.id)||job;this.checkProjectBudget(job.project_id);this.enqueueStatus(job,'running','Codex review is running');const mr=hydrated.mr,policy=await this.getPolicyFn(this.gitlab,job.project_id,mr,this.config),diffResult=await this.gitlab.listMergeRequestDiffs(job.project_id,job.mr_iid),hard=await this.gitlab.validateMergeRequestDiffCoverage(job.project_id,job.mr_iid,mr,diffResult);if(!hard.complete){diffResult.complete=false;diffResult.coverageReason=hard.reason;this.logger.warn?.({event:'diff_coverage_incomplete',traceId:job.trace_id,jobId:job.id,projectId:job.project_id,mrIid:job.mr_iid,reason:hard.reason});}const{snapshot,review}=await this.reviewSnapshot(mr,diffResult,policy,controller);if(!snapshot.coverageComplete){review.coverageComplete=false;review.verdict='incomplete';}await this.assertCurrentSnapshot(job,snapshot);const durationMs=Date.now()-started,actions=this.planPublication(job,snapshot,review,policy),receiptProjection=createServiceReviewReceipt(snapshot,review,policy),notificationEvent=eventForReview({job,mr,snapshot,review,durationMs,topFindings:this.config.notificationTopFindings}),notificationActions=planNotificationActions(this.config,notificationEvent,`run:${job.id}:${snapshot.headSha}`);this.store.saveRunWithOutbox(job.id,review,durationMs,policy,actions,receiptProjection,notificationActions);this.store.finishJob(job.id,review.verdict==='block'?'blocked':review.verdict);};
    try{if(this.telemetry)await this.telemetry.span(job.trace_id||this.traceId(),'review.job',{projectId:job.project_id,mrIid:job.mr_iid,jobId:job.id},run);else await run();}
    catch(error){const code=error?.code||'EUNKNOWN';if(code==='ESUPERSEDED'||code==='ECANCELLED'){job=this.store.getJob(job.id)||job;this.enqueueStatus(job,'canceled',code==='ESUPERSEDED'?'Review superseded':'Review canceled','cancel_status');this.store.finishJob(job.id,code==='ESUPERSEDED'?'superseded':'cancelled',code);return;}if(code==='ESHUTDOWN'){this.store.requeueRunningJob(job.id,code);return;}const shouldRetry=job.attempt<this.config.maxJobAttempts&&retryable(error)&&!this.stopping;this.logger.error?.({event:shouldRetry?'review_retry':'review_failed',traceId:job.trace_id,jobId:job.id,projectId:job.project_id,mrIid:job.mr_iid,attempt:job.attempt,code,status:error?.status||null});if(shouldRetry)this.store.retryJob(job.id,code,retryDelay(this.config,job,error));else{job=this.store.getJob(job.id)||job;this.store.finishJob(job.id,'failed',code);this.enqueueStatus(job,'failed',code==='EPROJECTPOLICY'?'Codex review policy is invalid':code==='ETOKENBUDGET'?'Codex review token budget exhausted':'Codex review service failed');const notificationEvent=eventForFailure(job,code);for(const action of planNotificationActions(this.config,notificationEvent,`job:${job.id}`))this.store.enqueueNotification(action);}}
    finally{clearTimeout(timer);if(this.active.get(key)?.controller===controller)this.active.delete(key);}}
  async workerLoop(workerId){while(!this.stopping){const job=this.store.claimNext();if(!job){await new Promise(resolve=>setTimeout(resolve,this.config.pollIntervalMs));continue;}this.logger.info?.({event:'job_started',traceId:job.trace_id,workerId,jobId:job.id,projectId:job.project_id,mrIid:job.mr_iid});await this.processJob(job);}}
  startWorkers(){if(this.workers.length)return this.workers;this.workers=Array.from({length:this.config.workerConcurrency},(_,index)=>this.workerLoop(index+1).catch(error=>{this.logger.error?.({event:'worker_crashed',workerId:index+1,code:error.code||'EWORKER'});throw error;}));return this.workers;}
  async stop(){this.stopping=true;for(const active of this.active.values())active.controller.abort(abortError('ESHUTDOWN','Service is shutting down'));await Promise.allSettled(this.workers);}
}
module.exports={ReviewService,NON_RETRYABLE_ERRORS,retryable,retryDelay,abortError,usageAdd,usageTotal,isDraft};