'use strict';

const crypto=require('node:crypto');
function hex(bytes){return crypto.randomBytes(bytes).toString('hex');}
function safeAttr(value){if(typeof value==='number'||typeof value==='boolean')return value;return String(value??'').slice(0,512);}
function otlpValue(value){if(typeof value==='boolean')return{boolValue:value};if(typeof value==='number')return Number.isInteger(value)?{intValue:String(value)}:{doubleValue:value};return{stringValue:String(value)};}
function genAiUsageAttributes(usage={},extra={}){return Object.freeze({'gen_ai.usage.input_tokens':Number(usage.inputTokens||0),'gen_ai.usage.cache_read.input_tokens':Number(usage.cachedInputTokens||0),'gen_ai.usage.cache_creation.input_tokens':Number(usage.cacheWriteInputTokens||0),'gen_ai.usage.output_tokens':Number(usage.outputTokens||0),'gen_ai.usage.reasoning.output_tokens':Number(usage.reasoningOutputTokens||0),...extra});}
function genAiClientAttributes({operation='review',provider='',model=''}={}){return Object.freeze({'gen_ai.operation.name':String(operation||'review').slice(0,64),'gen_ai.provider.name':String(provider||'').slice(0,128),'gen_ai.request.model':String(model||'').slice(0,256)});}
function otlpAttrs(attrs={}){return Object.entries(attrs).filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([key,value])=>({key,value:otlpValue(safeAttr(value))}));}
function histogramPoint(value,attrs,start,time){return{attributes:otlpAttrs(attrs),startTimeUnixNano:String(start),timeUnixNano:String(time),count:'1',sum:Number(value)||0,bucketCounts:['1'],explicitBounds:[]};}
class Metrics{
  constructor(){this.counters=new Map();this.histograms=new Map();}
  inc(name,value=1){this.counters.set(name,(this.counters.get(name)||0)+value);}
  observe(name,value,buckets=[0.1,0.25,0.5,1,2,5,10,30,60,120,300]){let h=this.histograms.get(name);if(!h){h={count:0,sum:0,buckets:[...buckets],counts:Array(buckets.length).fill(0)};this.histograms.set(name,h);}h.count++;h.sum+=value;for(let i=0;i<h.buckets.length;i++)if(value<=h.buckets[i])h.counts[i]++;}
  render(){const lines=[];for(const[name,value]of [...this.counters.entries()].sort())lines.push(`# TYPE ${name} counter`,`${name} ${value}`);for(const[name,h]of [...this.histograms.entries()].sort()){lines.push(`# TYPE ${name} histogram`);for(let i=0;i<h.buckets.length;i++)lines.push(`${name}_bucket{le="${h.buckets[i]}"} ${h.counts[i]}`);lines.push(`${name}_bucket{le="+Inf"} ${h.count}`,`${name}_sum ${h.sum}`,`${name}_count ${h.count}`);}return lines.length?`${lines.join('\n')}\n`:'';}
}
class Telemetry{
  constructor({logger=console,endpoint='',serviceName='codex-review-service',timeoutMs=3000}={}){this.logger=logger;this.endpoint=String(endpoint||'').replace(/\/$/,'');this.serviceName=serviceName;this.timeoutMs=timeoutMs;this.metrics=new Metrics();this.pending=new Set();}
  traceId(value=''){return /^[0-9a-f]{32}$/i.test(value)?value.toLowerCase():hex(16);}
  async span(traceId,name,attrs,fn){const spanId=hex(8),started=process.hrtime.bigint(),startUnix=BigInt(Date.now())*1000000n;let status={code:1};try{return await fn({traceId,spanId});}catch(error){status={code:2,message:String(error?.code||error?.message||'error').slice(0,256)};throw error;}finally{const elapsed=Number(process.hrtime.bigint()-started)/1e9;this.metrics.observe('codex_review_span_duration_seconds',elapsed);this.logger.info?.({event:'trace_span',traceId,spanId,name,durationMs:Math.round(elapsed*1000),...attrs,status:status.code===1?'ok':'error'});if(this.endpoint)this.exportSpan({traceId,spanId,name,attrs,status,startUnix,endUnix:startUnix+BigInt(Math.max(1,Math.round(elapsed*1e9))) });}}
  recordGenAiClient({operation='review',provider='',model='',durationSeconds=0,usage={}}={}){const attrs=genAiClientAttributes({operation,provider,model}),duration=Math.max(0,Number(durationSeconds)||0),input=Math.max(0,Number(usage.inputTokens||0)),output=Math.max(0,Number(usage.outputTokens||0));this.metrics.observe('gen_ai_client_operation_duration_seconds',duration);this.metrics.observe('gen_ai_client_input_token_usage',input,[100,500,1000,5000,10000,50000,100000,250000]);this.metrics.observe('gen_ai_client_output_token_usage',output,[10,50,100,500,1000,5000,10000]);if(this.endpoint)this.exportGenAiMetrics({attrs,duration,input,output});}
  exportGenAiMetrics(record){const task=(async()=>{try{const url=this.endpoint.endsWith('/v1/metrics')?this.endpoint:`${this.endpoint}/v1/metrics`,time=BigInt(Date.now())*1000000n,start=time-1000000n,metrics=[{name:'gen_ai.client.operation.duration',unit:'s',histogram:{aggregationTemporality:1,dataPoints:[histogramPoint(record.duration,record.attrs,start,time)]}},{name:'gen_ai.client.token.usage',unit:'{token}',histogram:{aggregationTemporality:1,dataPoints:[histogramPoint(record.input,{...record.attrs,'gen_ai.token.type':'input'},start,time),histogramPoint(record.output,{...record.attrs,'gen_ai.token.type':'output'},start,time)]}}],body={resourceMetrics:[{resource:{attributes:[{key:'service.name',value:{stringValue:this.serviceName}}]},scopeMetrics:[{scope:{name:'codex-review-service'},metrics}]}]};await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(this.timeoutMs)});}catch(error){this.logger.warn?.({event:'otel_metrics_export_failed',code:error?.code||'EOTELMETRICS'});}})();this.pending.add(task);task.finally(()=>this.pending.delete(task));}
  exportSpan(span){const task=(async()=>{try{const url=this.endpoint.endsWith('/v1/traces')?this.endpoint:`${this.endpoint}/v1/traces`;const attributes=Object.entries(span.attrs||{}).filter(([,v])=>v!==undefined&&v!==null).map(([key,value])=>({key,value:otlpValue(safeAttr(value))}));const body={resourceSpans:[{resource:{attributes:[{key:'service.name',value:{stringValue:this.serviceName}}]},scopeSpans:[{scope:{name:'codex-review-service'},spans:[{traceId:span.traceId,spanId:span.spanId,name:span.name,kind:1,startTimeUnixNano:String(span.startUnix),endTimeUnixNano:String(span.endUnix),attributes,status:span.status}]}]}]};await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(this.timeoutMs)});}catch(error){this.logger.warn?.({event:'otel_export_failed',code:error?.code||'EOTEL'});}})();this.pending.add(task);task.finally(()=>this.pending.delete(task));}
  async flush(){await Promise.allSettled([...this.pending]);}
}
module.exports={Telemetry,Metrics,genAiUsageAttributes,genAiClientAttributes};
