'use strict';

const crypto=require('node:crypto');
function safeEqual(a,b){const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
function normalizeUrl(value){try{return new URL(String(value)).toString().replace(/\/$/,'');}catch{return'';}}
function verifyInstance(headers,config){const actual=String(headers['x-gitlab-instance']||'').trim();if(!actual)return config.requireInstanceHeader?{ok:false,reason:'missing_instance'}:{ok:true};return normalizeUrl(actual)===normalizeUrl(config.webhookExpectedInstance)?{ok:true}:{ok:false,reason:'wrong_instance'};}
function verifySignedWebhook(headers,rawBody,config,webhookId,nowMs){const timestamp=String(headers['webhook-timestamp']||'').trim(),signatures=String(headers['webhook-signature']||'').trim();if(!timestamp||!signatures)return{ok:false,reason:'missing_signature'};const seconds=Number(timestamp);if(!Number.isFinite(seconds))return{ok:false,reason:'invalid_timestamp'};if(Math.abs(nowMs-seconds*1000)>config.webhookMaxSkewSeconds*1000)return{ok:false,reason:'stale_timestamp'};const rawKey=Buffer.from(config.webhookSigningToken.slice('whsec_'.length),'base64'),digest=crypto.createHmac('sha256',rawKey).update(`${webhookId}.${timestamp}.${rawBody}`).digest('base64'),expected=`v1,${digest}`;return signatures.split(/\s+/).some(signature=>safeEqual(expected,signature))?{ok:true,webhookId,mode:'hmac'}:{ok:false,reason:'bad_signature'};}
function classicWebhookId(headers,rawBody){const event=String(headers['x-gitlab-event']||'unknown').trim().slice(0,128);return`classic:${event}:${crypto.createHash('sha256').update(String(rawBody)).digest('hex')}`;}
function verifyClassicWebhook(headers,rawBody,config){const token=String(headers['x-gitlab-token']||'').trim();if(!token)return{ok:false,reason:'missing_classic_token'};if(!safeEqual(token,config.webhookSigningToken))return{ok:false,reason:'bad_classic_token'};return{ok:true,webhookId:classicWebhookId(headers,rawBody),mode:'classic-token'};}
function verifyWebhook(headers,rawBody,config,nowMs=Date.now()){
  if(config.webhookAuthMode==='classic-token')return verifyClassicWebhook(headers,rawBody,config);
  const webhookId=String(headers['webhook-id']||headers['idempotency-key']||headers['x-gitlab-event-uuid']||'').trim();if(!webhookId)return{ok:false,reason:'missing_webhook_id'};if(webhookId.length>255||/[\r\n\0]/.test(webhookId))return{ok:false,reason:'invalid_webhook_id'};const instance=verifyInstance(headers,config);if(!instance.ok)return instance;return verifySignedWebhook(headers,rawBody,config,webhookId,nowMs);
}
function normalizeEvent(payload,headers,config){const event=String(headers['x-gitlab-event']||payload.event_type||payload.object_kind||'unknown'),projectId=Number(payload.project?.id||payload.project_id||0)||null,projectAllowed=Boolean(projectId&&config.gitlabProjectAllowlist.has(projectId));if(payload.object_kind==='merge_request'){const attrs=payload.object_attributes||{},iid=Number(attrs.iid||0)||null,action=String(attrs.action||''),headSha=String(attrs.last_commit?.id||attrs.diff_refs?.head_sha||attrs.sha||'').trim(),baseSha=String(attrs.diff_refs?.base_sha||'').trim(),startSha=String(attrs.diff_refs?.start_sha||'').trim(),sourceBranch=String(attrs.source_branch||'').trim(),codeUpdate=action==='update'&&typeof attrs.oldrev==='string'&&attrs.oldrev.length>0,shouldReview=projectAllowed&&iid&&((action==='open'&&config.triggerOnOpen)||(action==='reopen'&&config.triggerOnReopen)||(codeUpdate&&config.triggerOnPush));return{event,kind:'merge_request',projectId,iid,action,headSha,baseSha,startSha,sourceBranch,shouldReview:Boolean(shouldReview),shouldCancel:Boolean(projectAllowed&&iid&&['close','merge'].includes(action)),projectAllowed};}if(payload.object_kind==='note'&&payload.merge_request){const attrs=payload.object_attributes||{},author=String(payload.user?.username||'').trim(),userId=Number(payload.user?.id||attrs.author_id||0)||null,note=String(attrs.note||'').trim(),action=String(attrs.action||''),iid=Number(payload.merge_request?.iid||0)||null,command=action==='create'&&/^\/codex\s+review\s*$/i.test(note),self=Boolean(config.botUsername)&&author.toLowerCase()===config.botUsername.toLowerCase();return{event,kind:'note',projectId,iid,author,userId,action,command,shouldReview:Boolean(projectAllowed&&iid&&userId&&command&&!self),shouldCancel:false,projectAllowed};}return{event,kind:'ignored',projectId,iid:null,shouldReview:false,shouldCancel:false,projectAllowed};}
module.exports={verifyWebhook,normalizeEvent,safeEqual,verifyInstance,normalizeUrl,classicWebhookId};
